import { Container,Graphics } from 'pixi.js'
import { RESOURCES,resourceProduction,BUILDINGS } from '../data/buildings.js'
import { findResearch } from '../data/research.js'
import { researchBonus } from '../systems/research.js'
import { panel,text,button,fmt,fmtTime } from './ui/primitives.js'
import { QuestHud } from './ui/QuestHud.js'
import { BuildingSheet } from './ui/BuildingSheet.js'
import { ResearchSheet } from './ui/ResearchSheet.js'
export class Hud extends Container{
 constructor(game){super();this.game=game;this.resourceTexts={};this.rateTexts={};this.makeStatic();this.quest=new QuestHud(game);this.detail=new BuildingSheet(game);this.researchPanel=new ResearchSheet(game);this.addChild(this.quest,this.detail,this.researchPanel);window.addEventListener('resize',()=>this.layout());this.layout()}
 makeStatic(){this.profile=panel(172,58,.94,0x112f3d,16);this.addChild(this.profile);const title=text('BUILD',18,0xffffff,'900');title.position.set(14,8);this.power=text('',11,0xffd777,'800');this.power.position.set(14,34);this.profile.addChild(title,this.power);this.top=panel(560,58,.88,0x112f3d,16);this.addChild(this.top);let x=10;for(const [k,r] of Object.entries(RESOURCES)){this.top.addChild(new Graphics().circle(x+11,17,8).fill(r.color).stroke({color:0xffffff,alpha:.5,width:1}));const t=text('',11);t.position.set(x+24,6);const rate=text('',8,0xa6e6b5);rate.position.set(x+24,29);this.top.addChild(t,rate);this.resourceTexts[k]=t;this.rateTexts[k]=rate;x+=136}this.queueBox=panel(274,54,.88,0x112f3d,14);this.addChild(this.queueBox);this.queue=text('',10);this.queue.position.set(12,8);this.queueBox.addChild(this.queue);this.cityBtn=button('CITY',104,44,0x496e7d);this.cityBtn.on('pointertap',()=>this.game.clearSelection());this.researchBtn=button('RESEARCH',112,44);this.researchBtn.on('pointertap',()=>this.openResearch());this.helpBtn=button('ALLIANCE',128,44,0x558a68);this.helpBtn.on('pointertap',()=>this.game.helpConstruction());this.addChild(this.cityBtn,this.researchBtn,this.helpBtn)}
 layout(){const w=window.innerWidth,h=window.innerHeight;this.profile.position.set(12,12);this.top.scale.set(1);this.top.position.set(Math.max(198,(w-560)/2),12);this.quest.scale.set(1);this.quest.position.set(12,82);this.queueBox.scale.set(1);this.queueBox.position.set(12,h-126);const total=364,start=Math.max(10,(w-total)/2);this.cityBtn.position.set(start,h-56);this.researchBtn.position.set(start+114,h-56);this.helpBtn.position.set(start+236,h-56);if(w<760){const ts=Math.min(1,(w-20)/560);this.top.scale.set(ts);this.top.position.set(10,76);const qs=Math.min(1,(w-20)/350);this.quest.scale.set(qs);this.quest.position.set(10,76+58*ts+8);this.queueBox.scale.set(.86);this.queueBox.position.set(10,h-116)}if(this.detail.visible)this.detail.position.set(w<760?Math.max(10,(w-this.detail.sheetW)/2):w-this.detail.sheetW-14,w<760?h-this.detail.sheetH-66:88);if(this.researchPanel.visible)this.researchPanel.position.set(w<760?Math.max(10,(w-this.researchPanel.sheetW)/2):w-this.researchPanel.sheetW-14,w<760?h-this.researchPanel.sheetH-66:82)}
 refresh(){const prod=resourceProduction(this.game.state),all=1+researchBonus(this.game.state,'allOutput');for(const k of Object.keys(this.resourceTexts)){const bonus=1+researchBonus(this.game.state,`${k}Output`);this.resourceTexts[k].text=`${RESOURCES[k].short}  ${fmt(this.game.state.resources[k]??0)}`;this.rateTexts[k].text=`+${(prod[k]*all*bonus).toFixed(1)}/s`}this.power.text=`POWER  ${fmt(this.game.state.power)}`;const c=this.game.state.construction,r=this.game.state.researchJob;this.queue.text=`BUILD  ${c?`${BUILDINGS[c.id].name} ${c.target} · ${fmtTime(c.finishAt-Date.now())}`:'Idle'}\nRESEARCH  ${r?`${findResearch(r.id)?.name??r.id} ${r.target} · ${fmtTime(r.finishAt-Date.now())}`:'Idle'}`;this.quest.refresh()}
 showBuilding(id){this.researchPanel.visible=false;this.detail.open(id);this.layout()}
 openResearch(){this.detail.visible=false;this.researchPanel.open();this.layout()}
}
