import { Container,Graphics,Text } from 'pixi.js'
import { BUILDINGS,buildingRequirements,nextBuildingLevel } from '../data/buildings.js'
import { RESEARCH,findResearch,researchCost } from '../data/research.js'

const text=(s,size=15,color=0xffffff,weight='700')=>new Text({text:s,style:{fontFamily:'Arial',fontSize:size,fill:color,fontWeight:weight}})
const panel=(w,h,a=.88)=>new Graphics().roundRect(0,0,w,h,18).fill({color:0x18313f,alpha:a}).stroke({color:0xffffff,alpha:.2,width:1})
function button(label,w=120,h=42){const c=new Container();const g=new Graphics().roundRect(0,0,w,h,13).fill(0x2f86c9).stroke({color:0xffffff,alpha:.3,width:2});const t=text(label,13);t.anchor.set(.5);t.position.set(w/2,h/2);c.addChild(g,t);c.eventMode='static';c.cursor='pointer';return c}
export class Hud extends Container{
 constructor(game){super();this.game=game;this.resourceTexts={};this.detail=new Container();this.researchPanel=new Container();this.addChild(this.detail,this.researchPanel);this.makeStatic();window.addEventListener('resize',()=>this.layout());this.layout()}
 makeStatic(){this.top=panel(520,58,.86);this.addChild(this.top);let x=14;for(const k of ['wood','food','coal','iron']){const t=text('',13);t.position.set(x,19);this.top.addChild(t);this.resourceTexts[k]=t;x+=126}this.power=text('Power 0',14,0xffd471);this.addChild(this.power)
 this.queue=text('',12,0xffffff);this.addChild(this.queue)
 this.buildBtn=button('BUILDINGS',118,44);this.buildBtn.on('pointertap',()=>this.game.clearSelection());this.addChild(this.buildBtn)
 this.researchBtn=button('RESEARCH',118,44);this.researchBtn.on('pointertap',()=>this.openResearch());this.addChild(this.researchBtn)
 this.helpBtn=button('ALLIANCE HELP',130,44);this.helpBtn.on('pointertap',()=>this.game.helpConstruction());this.addChild(this.helpBtn)
 }
 layout(){const w=window.innerWidth,h=window.innerHeight;this.top.position.set(Math.max(10,(w-520)/2),10);this.power.position.set(16,78);this.queue.position.set(16,102);this.buildBtn.position.set(Math.max(12,w/2-190),h-60);this.researchBtn.position.set(Math.max(136,w/2-60),h-60);this.helpBtn.position.set(Math.max(260,w/2+70),h-60);if(this.detail.visible)this.detail.position.set(Math.max(12,w-350),140);if(this.researchPanel.visible)this.researchPanel.position.set(Math.max(12,w-390),120)}
 refresh(){for(const k of Object.keys(this.resourceTexts))this.resourceTexts[k].text=`${k.toUpperCase()} ${Math.floor(this.game.state.resources[k]??0)}`;this.power.text=`Power ${Math.floor(this.game.state.power).toLocaleString()}`;const c=this.game.state.construction,r=this.game.state.researchJob;const left=j=>j?Math.max(0,(j.finishAt-Date.now())/1000).toFixed(1)+'s':'idle';this.queue.text=`Build: ${c?BUILDINGS[c.id].name+' '+c.target:'idle'} ${left(c)}   Research: ${r?(findResearch(r.id)?.name??r.id)+' '+r.target:'idle'} ${left(r)}`}
 showBuilding(id){this.researchPanel.visible=false;this.detail.removeChildren();this.detail.visible=true;const d=BUILDINGS[id],lvl=this.game.state.buildings[id]??0,target=nextBuildingLevel(this.game.state,id);const p=panel(330,250,.94);this.detail.addChild(p);const title=text(`${d.name} · Lv. ${lvl}`,20,0xffffff);title.position.set(18,16);p.addChild(title);const info=text(target>10?'Maximum level reached':`Next level: ${target}`,13,0xcfe8f4);info.position.set(18,52);p.addChild(info);if(d.levels[target]){const req=buildingRequirements(this.game.state,id,target);const cost=d.levels[target].cost;const costText=text(`Wood ${cost.wood}  Food ${cost.food}\nCoal ${cost.coal}  Iron ${cost.iron}`,13,0xffffff);costText.position.set(18,82);p.addChild(costText);const rq=text(req.length?`Requires: ${req.join(', ')}`:'Requirements met',12,req.length?0xffb0a0:0x9fe2af);rq.position.set(18,126);p.addChild(rq);const up=button(lvl===0?'CONSTRUCT':'UPGRADE',135,44);up.position.set(18,180);up.on('pointertap',()=>this.game.upgradeBuilding(id));p.addChild(up)}const close=button('CLOSE',120,44);close.position.set(180,180);close.on('pointertap',()=>{this.detail.visible=false});p.addChild(close);this.layout()}
 openResearch(){this.detail.visible=false;this.researchPanel.removeChildren();this.researchPanel.visible=true;const p=panel(370,Math.min(620,window.innerHeight-150),.96);this.researchPanel.addChild(p);const title=text('RESEARCH CENTER',20);title.position.set(18,14);p.addChild(title);let y=52;for(const [branch,b] of Object.entries(RESEARCH)){const h=text(b.label.toUpperCase(),13,0xffd471);h.position.set(18,y);p.addChild(h);y+=24;for(const [id,d] of Object.entries(b.items)){const lvl=this.game.state.research[id]??0;const row=button(`${d.name}  ${lvl}/${d.max}`,320,38);row.position.set(18,y);row.on('pointertap',()=>this.game.research(id));p.addChild(row);y+=44}y+=8}const close=button('CLOSE',110,40);close.position.set(242,14);close.on('pointertap',()=>this.researchPanel.visible=false);p.addChild(close);this.layout()}
}
