import { Application,Container } from 'pixi.js'
import { CityScene } from './CityScene.js'
import { WorldScene } from './WorldScene.js'
import { Hud } from './Hud.js'
import { loadVisualAssets } from './AssetLibrary.js'
import { loadState,saveState,resetState } from '../systems/state.js'
import { startConstruction,tickConstruction,allianceHelp } from '../systems/construction.js'
import { startResearch,tickResearch,researchBonus } from '../systems/research.js'
import { BUILDINGS,resourceProduction } from '../data/buildings.js'
import {worldTile,parseTile,adjacentTo} from '../data/world.js'

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n))
const has=(r,c)=>Object.entries(c).every(([k,v])=>(r[k]??0)>=v)
const spend=(r,c)=>Object.entries(c).forEach(([k,v])=>r[k]-=v)
export class StrategyGame{
 constructor(mount){this.mount=mount;this.state=loadState();this.lastResourceTick=performance.now();this.drag=null;this.pinch=null;this.pointers=new Map();this.toastTimer=null;this.mode='city'}
 async start(){this.applyOfflineProduction();this.app=new Application();await this.app.init({resizeTo:window,antialias:true,background:0x789daa,resolution:Math.min(devicePixelRatio,2),autoDensity:true});this.mount.appendChild(this.app.canvas);await loadVisualAssets();this.world=new Container();this.city=new CityScene(this);this.worldMap=new WorldScene(this);this.worldMap.visible=false;this.world.addChild(this.city,this.worldMap);this.app.stage.addChild(this.world);this.fitWorld();this.hud=new Hud(this);this.app.stage.addChild(this.hud);this.setupCamera();this.app.ticker.add(()=>this.update());window.addEventListener('resize',()=>{if(!this.drag&&!this.pinch)this.fitWorld(false);this.hud.layout()});this.hud.refresh();saveState(this.state)}
 fitWorld(resetScale=true){const target=this.mode==='world'?clamp(window.innerWidth/760,.45,.86):clamp(window.innerWidth/900,.42,.72);if(resetScale||!this.world?.scale?.x)this.world.scale.set(target);this.world.position.set(window.innerWidth/2,window.innerHeight/2+(this.mode==='world'?55:120))}
 setupCamera(){const s=this.app.stage;s.eventMode='static';s.hitArea=this.app.screen;const point=e=>({x:e.global.x,y:e.global.y})
  s.on('pointerdown',e=>{this.pointers.set(e.pointerId,point(e));if(this.pointers.size===1)this.drag={id:e.pointerId,x:e.global.x,y:e.global.y,wx:this.world.x,wy:this.world.y};else if(this.pointers.size===2){const [a,b]=[...this.pointers.values()];this.pinch={dist:Math.hypot(a.x-b.x,a.y-b.y),scale:this.world.scale.x};this.drag=null}})
  s.on('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;this.pointers.set(e.pointerId,point(e));if(this.pointers.size>=2&&this.pinch){const [a,b]=[...this.pointers.values()],dist=Math.hypot(a.x-b.x,a.y-b.y);this.world.scale.set(clamp(this.pinch.scale*(dist/Math.max(1,this.pinch.dist)),.30,1.45));return}if(this.drag&&this.drag.id===e.pointerId)this.world.position.set(this.drag.wx+e.global.x-this.drag.x,this.drag.wy+e.global.y-this.drag.y)})
  const end=e=>{this.pointers.delete(e.pointerId);this.pinch=null;if(this.pointers.size===1){const [id,p]=[...this.pointers.entries()][0];this.drag={id,x:p.x,y:p.y,wx:this.world.x,wy:this.world.y}}else this.drag=null};s.on('pointerup',end);s.on('pointerupoutside',end);s.on('pointercancel',end);this.app.canvas.addEventListener('wheel',e=>{e.preventDefault();this.world.scale.set(clamp(this.world.scale.x*(e.deltaY>0?.9:1.1),.30,1.45))},{passive:false})
 }
 showCity(){this.mode='city';this.city.visible=true;this.worldMap.visible=false;this.clearSelection();this.fitWorld();this.hud.refresh()}
 showWorld(){this.mode='world';this.city.visible=false;this.worldMap.visible=true;this.clearSelection();this.fitWorld();this.worldMap.refresh();this.hud.refresh()}
 selectBuilding(id){if(this.mode!=='city')return;this.hud.showBuilding(id)}
 selectWorldTile(id){if(this.mode!=='world')return;this.hud.showWorldTile(id)}
 clearSelection(){if(!this.hud)return;this.hud.detail.visible=false;this.hud.researchPanel.visible=false;this.hud.worldPanel.visible=false}
 focusBuilding(id){if(this.mode!=='city')this.showCity();const p=this.city.getBuildingPosition(id);if(!p)return;this.clearSelection();const z=this.world.scale.x;this.world.position.set(window.innerWidth/2-p.x*z,window.innerHeight/2+80-p.y*z);this.city.focus(id);this.toast(`${BUILDINGS[id].name} located`)}
 upgradeBuilding(id){const r=startConstruction(this.state,id);this.toast(r.ok?`${BUILDINGS[id].name} construction started`:r.error);saveState(this.state);this.city.refresh();this.hud.refresh()}
 helpConstruction(){const ok=allianceHelp(this.state);this.toast(ok?'Alliance help applied':'No construction in progress');saveState(this.state)}
 research(id){const r=startResearch(this.state,id);this.toast(r.ok?'Research started':r.error);saveState(this.state);this.hud.refresh()}
 isCollectReady(id){return Date.now()>=(this.state.collectReady?.[id]??0)}
 collectResource(id){const def=BUILDINGS[id],lvl=this.state.buildings[id]??0;if(!def?.production||!lvl||!this.isCollectReady(id))return;const bonus=1+researchBonus(this.state,'allOutput')+researchBonus(this.state,`${def.production.resource}Output`),amount=Math.max(1,Math.round(def.production.base*lvl*45*bonus));this.state.resources[def.production.resource]=(this.state.resources[def.production.resource]??0)+amount;this.state.collectReady[id]=Date.now()+30000;this.toast(`+${amount} ${def.production.resource.toUpperCase()}`);saveState(this.state);this.city.refresh();this.hud.refresh()}
 armyPower(){const b=this.state.buildings;return Math.round((this.state.world.armyPower??0)+(b.infantryCamp??0)*230+(b.lancerCamp??0)*280+(b.marksmanCamp??0)*310)}
 worldNodeReady(id){return Date.now()>=(this.state.world.nodeReady?.[id]??0)}
 scoutTile(id){const w=this.state.world;if(w.scouted.includes(id)||!adjacentTo(id,w.scouted))return;const cost={meat:35,wood:20};if(!has(this.state.resources,cost)){this.toast('Need 35 meat and 20 wood to scout');return}spend(this.state.resources,cost);w.scouted.push(id);this.worldMap.refresh();saveState(this.state);this.hud.showWorldTile(id);this.toast('Territory explored')}
 claimTile(id){const [x,y]=parseTile(id),d=worldTile(x,y),w=this.state.world;if(w.owned.includes(id)||!w.scouted.includes(id)||d.kind==='camp'||!adjacentTo(id,w.owned))return;const cost={wood:80,coal:25,iron:5};if(!has(this.state.resources,cost)){this.toast('Need wood, coal and iron to expand');return}spend(this.state.resources,cost);w.owned.push(id);this.state.power+=55;this.worldMap.refresh();saveState(this.state);this.hud.showWorldTile(id);this.toast('Territory claimed')}
 attackTile(id){const [x,y]=parseTile(id),d=worldTile(x,y),w=this.state.world;if(d.kind!=='camp'||w.defeated.includes(id)||!w.scouted.includes(id)||!adjacentTo(id,w.owned))return;if(this.armyPower()<d.strength){this.toast(`Enemy ${d.strength} > army ${this.armyPower()}`);return}const food=Math.ceil(d.strength*.12);if((this.state.resources.meat??0)<food){this.toast(`Need ${food} meat for the march`);return}this.state.resources.meat-=food;w.defeated.push(id);if(!w.owned.includes(id))w.owned.push(id);for(const [k,v] of Object.entries(d.reward))this.state.resources[k]=(this.state.resources[k]??0)+v;w.armyPower+=Math.round(d.strength*.07);this.state.power+=Math.round(d.strength*.1);this.worldMap.refresh();saveState(this.state);this.hud.showWorldTile(id);this.toast(`Raider camp defeated · +${Math.round(d.strength*.07)} army power`)}
 gatherTile(id){const [x,y]=parseTile(id),d=worldTile(x,y),w=this.state.world;if(d.kind!=='resource'||!w.owned.includes(id)||!this.worldNodeReady(id))return;const amount=Math.round(d.yield*(1+researchBonus(this.state,'allOutput')));this.state.resources[d.resource]=(this.state.resources[d.resource]??0)+amount;w.nodeReady[id]=Date.now()+30000;saveState(this.state);this.hud.showWorldTile(id);this.toast(`+${amount} ${d.resource.toUpperCase()} from territory`)}
 claimChapter(chapter){if(!chapter||this.state.claimedChapters?.[chapter.id])return;for(const [k,v] of Object.entries(chapter.reward))this.state.resources[k]=(this.state.resources[k]??0)+v;this.state.claimedChapters[chapter.id]=true;this.toast('Chapter reward claimed');saveState(this.state);this.hud.refresh()}
 toast(message){this.hud.queue.text=message;clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>this.hud.refresh(),1700)}
 productionRates(){const base=resourceProduction(this.state),all=1+researchBonus(this.state,'allOutput');for(const k of Object.keys(base))base[k]*=all*(1+researchBonus(this.state,`${k}Output`));return base}
 applyOfflineProduction(){const last=this.state.lastSavedAt??Date.now(),seconds=Math.min(8*3600,Math.max(0,(Date.now()-last)/1000));if(seconds<3)return;const rates=this.productionRates();for(const [k,v] of Object.entries(rates))this.state.resources[k]=(this.state.resources[k]??0)+v*seconds}
 update(){const now=performance.now(),dt=Math.min(1,(now-this.lastResourceTick)/1000);this.lastResourceTick=now;const rates=this.productionRates();for(const [k,v] of Object.entries(rates))this.state.resources[k]=(this.state.resources[k]??0)+v*dt;const changed=Boolean(tickConstruction(this.state)|tickResearch(this.state));if(changed){this.city.refresh();saveState(this.state);if(this.hud.researchPanel.visible)this.hud.openResearch()}if(this.city.visible)this.city.animate();if(this.worldMap.visible)this.worldMap.animate();this.hud.refresh();if(Math.floor(now)%1800<20)saveState(this.state)}
 reset(){this.state=resetState();this.city.refresh();this.worldMap.refresh();this.showCity();saveState(this.state)}
}
