import { Application,Container } from 'pixi.js'
import { CityScene } from './CityScene.js'
import { WorldScene } from './WorldScene.js'
import { Hud } from './Hud.js'
import { loadVisualAssets } from './AssetLibrary.js'
import { loadState,saveState,resetState } from '../systems/state.js'
import { startConstruction,tickConstruction,allianceHelp } from '../systems/construction.js'
import { startResearch,tickResearch,researchBonus } from '../systems/research.js'
import { BUILDINGS,resourceProduction } from '../data/buildings.js'
import {worldTile,parseTile,adjacentTo,BASE_TILE} from '../data/world.js'

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n))
const has=(r,c)=>Object.entries(c).every(([k,v])=>(r[k]??0)>=v)
const spend=(r,c)=>Object.entries(c).forEach(([k,v])=>r[k]-=v)
const TROOP_POWER={infantry:7,lancer:8,marksman:9}
const CAMP_BY_TROOP={infantry:'infantryCamp',lancer:'lancerCamp',marksman:'marksmanCamp'}
const manhattan=id=>{const [x,y]=parseTile(id),[bx,by]=parseTile(BASE_TILE);return Math.abs(x-bx)+Math.abs(y-by)}

export class StrategyGame{
 constructor(mount){this.mount=mount;this.state=loadState();this.lastResourceTick=performance.now();this.drag=null;this.pinch=null;this.pointers=new Map();this.toastTimer=null;this.mode='city'}
 async start(){this.applyOfflineProduction();this.app=new Application();await this.app.init({resizeTo:window,antialias:true,background:0x789daa,resolution:Math.min(devicePixelRatio,2),autoDensity:true});this.mount.appendChild(this.app.canvas);await loadVisualAssets();this.world=new Container();this.city=new CityScene(this);this.worldMap=new WorldScene(this);this.worldMap.visible=false;this.world.addChild(this.city,this.worldMap);this.app.stage.addChild(this.world);this.fitWorld();this.hud=new Hud(this);this.app.stage.addChild(this.hud);this.setupCamera();this.app.ticker.add(()=>this.update());window.addEventListener('resize',()=>{if(!this.drag&&!this.pinch)this.fitWorld(false);this.hud.layout()});this.hud.refresh();saveState(this.state)}
 fitWorld(resetScale=true){const target=this.mode==='world'?clamp(window.innerWidth/760,.45,.86):clamp(window.innerWidth/900,.42,.72);if(resetScale||!this.world?.scale?.x)this.world.scale.set(target);this.world.position.set(window.innerWidth/2,window.innerHeight/2+(this.mode==='world'?55:120))}
 setupCamera(){const s=this.app.stage;s.eventMode='static';s.hitArea=this.app.screen;const point=e=>({x:e.global.x,y:e.global.y})
  s.on('pointerdown',e=>{this.pointers.set(e.pointerId,point(e));if(this.pointers.size===1)this.drag={id:e.pointerId,x:e.global.x,y:e.global.y,wx:this.world.x,wy:this.world.y};else if(this.pointers.size===2){const [a,b]=[...this.pointers.values()];this.pinch={dist:Math.hypot(a.x-b.x,a.y-b.y),scale:this.world.scale.x};this.drag=null}})
  s.on('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;this.pointers.set(e.pointerId,point(e));if(this.pointers.size>=2&&this.pinch){const [a,b]=[...this.pointers.values()],dist=Math.hypot(a.x-b.x,a.y-b.y);this.world.scale.set(clamp(this.pinch.scale*(dist/Math.max(1,this.pinch.dist)),.30,1.45));return}if(this.drag&&this.drag.id===e.pointerId)this.world.position.set(this.drag.wx+e.global.x-this.drag.x,this.drag.wy+e.global.y-this.drag.y)})
  const end=e=>{this.pointers.delete(e.pointerId);this.pinch=null;if(this.pointers.size===1){const [id,p]=[...this.pointers.entries()][0];this.drag={id,x:p.x,y:p.y,wx:this.world.x,wy:this.world.y}}else this.drag=null};s.on('pointerup',end);s.on('pointerupoutside',end);s.on('pointercancel',end);this.app.canvas.addEventListener('wheel',e=>{e.preventDefault();this.world.scale.set(clamp(this.world.scale.x*(e.deltaY>0?.9:1.1),.30,1.45))},{passive:false})
 }
 showCity(){this.mode='city';this.city.visible=true;this.worldMap.visible=false;this.clearSelection();this.fitWorld();this.hud.refresh()}
 showWorld(){this.mode='world';this.city.visible=false;this.worldMap.visible=true;this.clearSelection();this.fitWorld();this.worldMap.refresh();this.hud.refresh()}
 selectBuilding(id){if(this.mode!=='city')return;this.hud.showBuilding(id)}
 selectWorldTile(id){if(this.mode!=='world')return;this.hud.showWorldTile(id)}
 clearSelection(){if(!this.hud)return;this.hud.detail.visible=false;this.hud.researchPanel.visible=false;this.hud.worldPanel.visible=false;this.hud.armyPanel.visible=false}
 focusBuilding(id){if(this.mode!=='city')this.showCity();const p=this.city.getBuildingPosition(id);if(!p)return;this.clearSelection();const z=this.world.scale.x;this.world.position.set(window.innerWidth/2-p.x*z,window.innerHeight/2+80-p.y*z);this.city.focus(id);this.toast(`${BUILDINGS[id].name} located`)}
 upgradeBuilding(id){const r=startConstruction(this.state,id);this.toast(r.ok?`${BUILDINGS[id].name} construction started`:r.error);saveState(this.state);this.city.refresh();this.hud.refresh()}
 helpConstruction(){const ok=allianceHelp(this.state);this.toast(ok?'Alliance help applied':'No construction in progress');saveState(this.state)}
 research(id){const r=startResearch(this.state,id);this.toast(r.ok?'Research started':r.error);saveState(this.state);this.hud.refresh()}
 isCollectReady(id){return Date.now()>=(this.state.collectReady?.[id]??0)}
 collectResource(id){const def=BUILDINGS[id],lvl=this.state.buildings[id]??0;if(!def?.production||!lvl||!this.isCollectReady(id))return;const bonus=1+researchBonus(this.state,'allOutput')+researchBonus(this.state,`${def.production.resource}Output`),amount=Math.max(1,Math.round(def.production.base*lvl*45*bonus));this.state.resources[def.production.resource]=(this.state.resources[def.production.resource]??0)+amount;this.state.collectReady[id]=Date.now()+30000;this.toast(`+${amount} ${def.production.resource.toUpperCase()}`);saveState(this.state);this.city.refresh();this.hud.refresh()}
 armyPower(){const w=this.state.world,t=w.troops??{};return Math.round((w.armyPower??0)+Object.entries(TROOP_POWER).reduce((a,[k,p])=>a+(t[k]??0)*p,0)+(this.state.buildings.infantryCamp??0)*45+(this.state.buildings.lancerCamp??0)*55+(this.state.buildings.marksmanCamp??0)*65)}
 assignedTroops(){const out={infantry:0,lancer:0,marksman:0};for(const m of this.state.world.marches??[])for(const k of Object.keys(out))out[k]+=m.troops?.[k]??0;return out}
 freeTroops(){const used=this.assignedTroops(),all=this.state.world.troops;return Object.fromEntries(Object.keys(TROOP_POWER).map(k=>[k,Math.max(0,(all[k]??0)-used[k])]))}
 freeArmyPower(){const t=this.freeTroops();return Math.round((this.state.world.armyPower??0)+Object.entries(TROOP_POWER).reduce((a,[k,p])=>a+(t[k]??0)*p,0))}
 marchCapacity(){return 2+((this.state.buildings.embassy??0)>=8?1:0)}
 activeMarchFor(id){return (this.state.world.marches??[]).find(m=>m.target===id)??null}
 worldNodeReady(id){return Date.now()>=(this.state.world.nodeReady?.[id]??0)}
 travelMs(id){return 2200+manhattan(id)*1450}
 makeTroopDetachment(type){const free=this.freeTroops();if(type==='attack')return{infantry:Math.max(0,Math.floor(free.infantry*.7)),lancer:Math.max(0,Math.floor(free.lancer*.7)),marksman:Math.max(0,Math.floor(free.marksman*.7))};const n=Math.min(6,free.infantry);return{infantry:n,lancer:0,marksman:0}}
 detachmentPower(t){return Object.entries(TROOP_POWER).reduce((a,[k,p])=>a+(t[k]??0)*p,0)+(this.state.world.armyPower??0)}
 dispatchMarch(type,id,cost={}){const w=this.state.world;if(w.marches.length>=this.marchCapacity()){this.toast('All march queues are busy');return false}if(this.activeMarchFor(id)){this.toast('A march is already moving to this tile');return false}if(!has(this.state.resources,cost)){this.toast('Not enough resources for this march');return false}const troops=this.makeTroopDetachment(type);if(Object.values(troops).reduce((a,b)=>a+b,0)<1){this.toast('No free troops');return false}if(type==='attack'){const [x,y]=parseTile(id),d=worldTile(x,y);if(this.detachmentPower(troops)<d.strength){this.toast(`Need more troops · enemy ${d.strength}`);return false}}spend(this.state.resources,cost);const now=Date.now(),travel=this.travelMs(id);w.marches.push({id:`m${now}${Math.floor(Math.random()*999)}`,type,target:id,phase:'outbound',phaseStartedAt:now,arriveAt:now+travel,travelMs:travel,troops,cargo:null});saveState(this.state);this.worldMap.refresh();this.hud.refresh();this.toast(`${type.toUpperCase()} march dispatched`);return true}
 scoutTile(id){const w=this.state.world;if(w.scouted.includes(id)||!adjacentTo(id,w.scouted))return;this.dispatchMarch('scout',id,{meat:25,wood:15})}
 claimTile(id){const [x,y]=parseTile(id),d=worldTile(x,y),w=this.state.world;if(w.owned.includes(id)||!w.scouted.includes(id)||d.kind==='camp'||!adjacentTo(id,w.owned))return;this.dispatchMarch('claim',id,{wood:60,coal:20,iron:4})}
 attackTile(id){const [x,y]=parseTile(id),d=worldTile(x,y),w=this.state.world;if(d.kind!=='camp'||w.defeated.includes(id)||!w.scouted.includes(id)||!adjacentTo(id,w.owned))return;this.dispatchMarch('attack',id,{meat:Math.ceil(d.strength*.08)})}
 gatherTile(id){const [x,y]=parseTile(id),d=worldTile(x,y),w=this.state.world;if(d.kind!=='resource'||!w.owned.includes(id)||!this.worldNodeReady(id))return;this.dispatchMarch('gather',id,{meat:12})}
 resolveAttack(m){const [x,y]=parseTile(m.target),d=worldTile(x,y),w=this.state.world,power=this.detachmentPower(m.troops);const win=power>=d.strength;let losses=0;if(win){losses=Math.max(1,Math.round(d.strength/220));const total=Object.values(m.troops).reduce((a,b)=>a+b,0)||1;for(const k of Object.keys(m.troops)){const loss=Math.min(this.state.world.troops[k]??0,Math.round(losses*(m.troops[k]/total)));this.state.world.troops[k]-=loss}if(!w.defeated.includes(m.target))w.defeated.push(m.target);if(!w.owned.includes(m.target))w.owned.push(m.target);for(const [k,v] of Object.entries(d.reward))this.state.resources[k]=(this.state.resources[k]??0)+v;w.armyPower+=Math.round(d.strength*.025);this.state.power+=Math.round(d.strength*.08)}else{losses=Math.max(1,Math.round(Object.values(m.troops).reduce((a,b)=>a+b,0)*.18));for(const k of Object.keys(m.troops))this.state.world.troops[k]=Math.max(0,(this.state.world.troops[k]??0)-Math.round(losses/3))}w.battleReports.unshift({at:Date.now(),target:m.target,enemy:d.strength,power,win,losses});w.battleReports=w.battleReports.slice(0,12);this.toast(win?`Victory · ${losses} casualties`:`Defeat · ${losses} casualties`)}
 finishOutbound(m,now){const w=this.state.world;if(m.type==='scout'){if(!w.scouted.includes(m.target))w.scouted.push(m.target);this.toast('Scout report received')}else if(m.type==='claim'){if(!w.owned.includes(m.target)){w.owned.push(m.target);this.state.power+=55}this.toast('Territory occupied')}else if(m.type==='attack')this.resolveAttack(m);else if(m.type==='gather'){m.phase='gathering';m.phaseStartedAt=now;m.gatherDoneAt=now+6000;this.toast('Gatherers working');return}m.phase='returning';m.phaseStartedAt=now;m.arriveAt=now+m.travelMs}
 tickMarches(){const w=this.state.world,now=Date.now();let changed=false;for(const m of w.marches){if(m.phase==='outbound'&&now>=m.arriveAt){this.finishOutbound(m,now);changed=true}else if(m.phase==='gathering'&&now>=m.gatherDoneAt){const [x,y]=parseTile(m.target),d=worldTile(x,y),amount=Math.round(d.yield*(1+researchBonus(this.state,'allOutput')));m.cargo={resource:d.resource,amount};m.phase='returning';m.phaseStartedAt=now;m.arriveAt=now+m.travelMs;changed=true;this.toast(`Gather complete · returning with ${amount}`)}}const keep=[];for(const m of w.marches){if(m.phase==='returning'&&now>=m.arriveAt){if(m.cargo){this.state.resources[m.cargo.resource]=(this.state.resources[m.cargo.resource]??0)+m.cargo.amount;w.nodeReady[m.target]=now+30000;this.toast(`+${m.cargo.amount} ${m.cargo.resource.toUpperCase()} delivered`)}changed=true}else keep.push(m)}if(keep.length!==w.marches.length)w.marches=keep;return changed}
 trainTroops(type){const w=this.state.world;if(w.trainingJob){this.toast('Training queue is busy');return}const camp=CAMP_BY_TROOP[type],lvl=this.state.buildings[camp]??0;if(lvl<1){this.toast(`Build ${BUILDINGS[camp].name} first`);return}const amount=20+lvl*10,cost={meat:amount*2,wood:amount,coal:Math.ceil(amount*.2)};if(!has(this.state.resources,cost)){this.toast('Not enough resources to train');return}spend(this.state.resources,cost);const now=Date.now();w.trainingJob={type,amount,startedAt:now,finishAt:now+9000+lvl*800};saveState(this.state);this.hud.armyPanel.open();this.toast(`Training ${amount} ${type}`)}
 tickTraining(){const j=this.state.world.trainingJob;if(!j||Date.now()<j.finishAt)return false;this.state.world.troops[j.type]=(this.state.world.troops[j.type]??0)+j.amount;this.state.world.trainingJob=null;this.state.power+=j.amount*2;this.toast(`${j.amount} ${j.type} ready`);return true}
 claimChapter(chapter){if(!chapter||this.state.claimedChapters?.[chapter.id])return;for(const [k,v] of Object.entries(chapter.reward))this.state.resources[k]=(this.state.resources[k]??0)+v;this.state.claimedChapters[chapter.id]=true;this.toast('Chapter reward claimed');saveState(this.state);this.hud.refresh()}
 toast(message){if(!this.hud)return;this.hud.queue.text=message;clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>this.hud.refresh(),1700)}
 productionRates(){const base=resourceProduction(this.state),all=1+researchBonus(this.state,'allOutput');for(const k of Object.keys(base))base[k]*=all*(1+researchBonus(this.state,`${k}Output`));return base}
 applyOfflineProduction(){const last=this.state.lastSavedAt??Date.now(),seconds=Math.min(8*3600,Math.max(0,(Date.now()-last)/1000));if(seconds<3)return;const rates=this.productionRates();for(const [k,v] of Object.entries(rates))this.state.resources[k]=(this.state.resources[k]??0)+v*seconds}
 update(){const now=performance.now(),dt=Math.min(1,(now-this.lastResourceTick)/1000);this.lastResourceTick=now;const rates=this.productionRates();for(const [k,v] of Object.entries(rates))this.state.resources[k]=(this.state.resources[k]??0)+v*dt;const changed=Boolean(tickConstruction(this.state)|tickResearch(this.state)|this.tickMarches()|this.tickTraining());if(changed){this.city.refresh();this.worldMap.refresh();saveState(this.state);if(this.hud.researchPanel.visible)this.hud.openResearch();if(this.hud.worldPanel.visible)this.hud.worldPanel.refresh();if(this.hud.armyPanel.visible)this.hud.armyPanel.refresh()}if(this.city.visible)this.city.animate();if(this.worldMap.visible)this.worldMap.animate();this.hud.refresh();if(Math.floor(now)%1800<20)saveState(this.state)}
 reset(){this.state=resetState();this.city.refresh();this.worldMap.refresh();this.showCity();saveState(this.state)}
}
