using UnityEngine;
using UnityEngine.UI;
namespace Achu.BusinessHub
{
    public sealed class AchuHud : MonoBehaviour
    {
        private GameDirector game; private SceneModeController modes; private Text cash,sup,rep,tal,mission,status;
        private static readonly Color Mint=new(0.24f,0.75f,0.58f,1),Panel=new(.88f,.93f,.89f,.95f),Ink=new(.04f,.16f,.13f,1),Dark=new(.05f,.18f,.15f,.94f);
        public void Configure(GameDirector g,SceneModeController m){game=g;modes=m;Build();game.StateChanged+=Refresh;Refresh();}
        private Text Txt(Transform p,string text,int size,TextAnchor align){var go=new GameObject("Text",typeof(RectTransform),typeof(Text));go.transform.SetParent(p,false);var t=go.GetComponent<Text>();t.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.text=text;t.fontSize=size;t.color=Ink;t.alignment=align;t.resizeTextForBestFit=true;Stretch(go.GetComponent<RectTransform>());return t;}
        private GameObject PanelObj(Transform p,string name,Color color,Vector2 amin,Vector2 amax,Vector2 omin,Vector2 omax){var go=new GameObject(name,typeof(RectTransform),typeof(Image));go.transform.SetParent(p,false);var r=go.GetComponent<RectTransform>();r.anchorMin=amin;r.anchorMax=amax;r.offsetMin=omin;r.offsetMax=omax;go.GetComponent<Image>().color=color;return go;}
        private Button Btn(Transform p,string name,string label,Vector2 amin,Vector2 amax,System.Action click){var go=PanelObj(p,name,Panel,amin,amax,new Vector2(5,5),new Vector2(-5,-5));var b=go.AddComponent<Button>();b.onClick.AddListener(()=>click());Txt(go.transform,label,18,TextAnchor.MiddleCenter);return b;}
        private void Build(){var canvas=new GameObject("ACHU HUD",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster),typeof(SafeAreaFitter));canvas.transform.SetParent(transform,false);var c=canvas.GetComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;c.sortingOrder=100;var s=canvas.GetComponent<CanvasScaler>();s.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;s.referenceResolution=new Vector2(390,844);s.matchWidthOrHeight=.55f;
            var top=PanelObj(canvas.transform,"Top",Panel,new Vector2(.02f,.88f),new Vector2(.98f,.98f),Vector2.zero,Vector2.zero);cash=Txt(top.transform,"£",22,TextAnchor.MiddleLeft);cash.rectTransform.anchorMin=new Vector2(.02f,0);cash.rectTransform.anchorMax=new Vector2(.27f,1);sup=Txt(top.transform,"◆",22,TextAnchor.MiddleCenter);sup.rectTransform.anchorMin=new Vector2(.27f,0);sup.rectTransform.anchorMax=new Vector2(.5f,1);rep=Txt(top.transform,"★",22,TextAnchor.MiddleCenter);rep.rectTransform.anchorMin=new Vector2(.5f,0);rep.rectTransform.anchorMax=new Vector2(.73f,1);tal=Txt(top.transform,"●",22,TextAnchor.MiddleRight);tal.rectTransform.anchorMin=new Vector2(.73f,0);tal.rectTransform.anchorMax=new Vector2(.98f,1);
            var missionPanel=PanelObj(canvas.transform,"Mission",Panel,new Vector2(.02f,.79f),new Vector2(.98f,.87f),Vector2.zero,Vector2.zero);mission=Txt(missionPanel.transform,"Build the company",20,TextAnchor.MiddleLeft);mission.rectTransform.offsetMin=new Vector2(16,0);mission.rectTransform.offsetMax=new Vector2(-16,0);
            var bottom=PanelObj(canvas.transform,"BottomNav",Panel,new Vector2(.02f,.02f),new Vector2(.98f,.11f),Vector2.zero,Vector2.zero);Btn(bottom.transform,"City","CITY",new Vector2(0,0),new Vector2(.25f,1),()=>modes.ShowCity());Btn(bottom.transform,"Base","BASE",new Vector2(.25f,0),new Vector2(.5f,1),()=>modes.ShowBase());Btn(bottom.transform,"Upgrade","UPGRADE HQ",new Vector2(.5f,0),new Vector2(.75f,1),()=>game.TryUpgrade(AchuIds.Headquarters));Btn(bottom.transform,"Reset","RESET",new Vector2(.75f,0),new Vector2(1,1),()=>game.ResetProgress());
            var st=PanelObj(canvas.transform,"Status",Dark,new Vector2(.12f,.12f),new Vector2(.88f,.17f),Vector2.zero,Vector2.zero);status=Txt(st.transform,"Operation ready",16,TextAnchor.MiddleCenter);status.color=Color.white;}
        private static void Stretch(RectTransform r){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;}
        private void Refresh(){if(game?.State==null)return;var r=game.State.resources;cash.text=$"£ {r.cash/1000d:0.0}K";sup.text=$"◆ {r.supplies/1000d:0.0}K";rep.text=$"★ {r.reputation/1000d:0.0}K";tal.text=$"● {r.talent/1000d:0.0}K";var h=game.State.GetBuildingLevel(AchuIds.Headquarters);mission.text=$"CHAPTER {h}  ·  Grow ACHU  ·  Headquarters → level {Mathf.Min(12,h+1)}";status.text=game.State.construction==null?"Operation ready":"Development in progress";}
    }
}
