import { Container } from 'pixi.js'
import { BUILDINGS,RESOURCES,buildingRequirements,nextBuildingLevel } from '../../data/buildings.js'
import { panel,text,button,fmt } from './primitives.js'
function locateRequirement(state,id,target){const d=BUILDINGS[id];if(d.unlockFurnace&&(state.buildings.furnace??0)<d.unlockFurnace)return'furnace';if(d.gate&&id!=='furnace'&&target>(state.buildings.furnace??0))return'furnace';for(const [other,lvl] of(d.requires?.[target]??[]))if((state.buildings[other]??0)<lvl)return other;return null}
export class BuildingSheet extends Container{
 constructor(game){super();this.game=game;this.visible=false}
 open(id){this.removeChildren();this.visible=true;const d=BUILDINGS[id],lvl=this.game.state.buildings[id]??0,target=nextBuildingLevel(this.game.state,id),req=d.levels[target]?buildingRequirements(this.game.state,id,target):[],locateId=d.levels[target]?locateRequirement(this.game.state,id,target):null,w=Math.min(410,window.innerWidth-20),hasProd=d.production&&lvl>0,h=250+(hasProd?26:0)+(locateId?42:0);this.sheetW=w;this.sheetH=h;const p=panel(w,h,.98,0x0f2935,22);this.addChild(p);const title=text(d.name,20,0xffffff,'900');title.position.set(18,14);const sub=text(`LEVEL ${lvl} · ${d.category.toUpperCase()}`,10,0x9fc6d5,'800');sub.position.set(18,42);p.addChild(title,sub);let y=70
  if(hasProd){const prod=d.production.base*lvl*Math.pow(1.10,Math.max(0,lvl-1)),q=text(`${RESOURCES[d.production.resource].label} output  ${prod.toFixed(1)}/s`,11,0xa8e7b8);q.position.set(18,y);p.addChild(q);y+=26}
  if(d.levels[target]){const cost=d.levels[target].cost,costText=text(`UPGRADE TO ${target}\nMEAT ${fmt(cost.meat)}   WOOD ${fmt(cost.wood)}\nCOAL ${fmt(cost.coal)}   IRON ${fmt(cost.iron)}`,11,0xffffff,'800');costText.position.set(18,y);p.addChild(costText);y+=62;const rq=text(req.length?`Requires  ${req.join(' · ')}`:'Requirements met',10,req.length?0xffae9f:0xa8e7b8,'800');rq.position.set(18,y);p.addChild(rq);y+=28;if(locateId){const go=button(`LOCATE ${BUILDINGS[locateId].name.toUpperCase()}`,w-36,34,0xa76434);go.position.set(18,y);go.on('pointertap',()=>this.game.focusBuilding(locateId));p.addChild(go)}const upW=Math.floor((w-54)*.58),up=button(lvl===0?'CONSTRUCT':'UPGRADE',upW,42);up.position.set(18,h-56);up.on('pointertap',()=>this.game.upgradeBuilding(id));p.addChild(up);const close=button('CLOSE',Math.floor((w-54)*.38),42,0x526b76);close.position.set(30+upW,h-56);close.on('pointertap',()=>this.visible=false);p.addChild(close)}else{const max=text('Maximum level reached',12,0xffd777);max.position.set(18,y+10);p.addChild(max);const close=button('CLOSE',120,42,0x526b76);close.position.set(18,h-56);close.on('pointertap',()=>this.visible=false);p.addChild(close)}}
}
