import {Container} from 'pixi.js'
import {worldTile,parseTile,adjacentTo} from '../../data/world.js'
import {panel,text,button,fmt} from './primitives.js'

export class WorldSheet extends Container{
 constructor(game){super();this.game=game;this.visible=false;this.sheetW=390;this.sheetH=270}
 open(id){this.removeChildren();this.visible=true;const [x,y]=parseTile(id),d=worldTile(x,y),w=this.game.state.world,scouted=w.scouted.includes(id),owned=w.owned.includes(id),defeated=w.defeated.includes(id),canScout=!scouted&&adjacentTo(id,w.scouted),canClaim=scouted&&!owned&&d.kind!=='camp'&&adjacentTo(id,w.owned),canAttack=scouted&&d.kind==='camp'&&!defeated&&adjacentTo(id,w.owned),canGather=scouted&&owned&&d.kind==='resource';const width=Math.min(390,window.innerWidth-20),h=270;this.sheetW=width;this.sheetH=h;const p=panel(width,h,.98,0x0c2732,22);this.addChild(p);const title=text(scouted?d.name:'Unexplored territory',20,0xffffff,'900');title.position.set(18,16);p.addChild(title);const status=text(owned?'CONTROLLED':scouted?'SCOUTED':'FOG OF WAR',10,owned?0x8be5ae:0xa8c9d5,'900');status.position.set(18,46);p.addChild(status);let info='Explore the frontier to reveal resources and enemies.';if(d.kind==='resource'&&scouted)info=`Resource node: ${d.resource.toUpperCase()} · yield ${fmt(d.yield)}`;if(d.kind==='camp'&&scouted)info=`Enemy power ${fmt(d.strength)} · your army ${fmt(this.game.armyPower())}`;if(d.kind==='wild'&&scouted)info='Open territory. Claim it to expand your settlement border.';if(d.kind==='base')info='Your settlement. Expand outward from here.';const desc=text(info,11,0xcfe6ee,'700');desc.position.set(18,75);p.addChild(desc)
  let action=null;if(canScout)action=button('SCOUT',width-36,42,0x3a7fa2);else if(canClaim)action=button('CLAIM TERRITORY',width-36,42,0x4d8767);else if(canAttack)action=button('ATTACK',width-36,42,0x9a4f4f);else if(canGather)action=button(this.game.worldNodeReady(id)?'GATHER':'NODE RECOVERING',width-36,42,this.game.worldNodeReady(id)?0xa67636:0x53666f);else if(!scouted)action=button('OUT OF SCOUT RANGE',width-36,42,0x53666f);else action=button(owned?'CONTROLLED':'EXPAND FROM ADJACENT LAND',width-36,42,0x53666f);action.position.set(18,160);action.on('pointertap',()=>{if(canScout)this.game.scoutTile(id);else if(canClaim)this.game.claimTile(id);else if(canAttack)this.game.attackTile(id);else if(canGather&&this.game.worldNodeReady(id))this.game.gatherTile(id)});p.addChild(action);const close=button('CLOSE',110,38,0x526b76);close.position.set(width-128,216);close.on('pointertap',()=>this.visible=false);p.addChild(close)}
}
