import * as THREE from 'three'
import { BUILDINGS } from '../data/buildings.js'

const ACCENT={furnace:0x50d4a1,shelter:0x67b9e8,sawmill:0xe9aa54,huntersHut:0xe88170,coalMine:0xe6c159,storehouse:0x76aee3,infantryCamp:0x62d99b,infirmary:0x61cfc6,ironMine:0xb991e5,lancerCamp:0x5fa8e0,embassy:0xe9c06a,marksmanCamp:0xe486ad,researchCenter:0x69d5df}
const ASSET={furnace:'achuHq',shelter:'achuClient',sawmill:'achuDepot',huntersHut:'cityA',coalMine:'achuStudio',storehouse:'achuWarehouse',infantryCamp:'cityL',infirmary:'cityC',ironMine:'cityN',lancerCamp:'achuDepot',embassy:'cityE',marksmanCamp:'cityG',researchCenter:'cityS'}
const LOTS={
 furnace:[0,1.35,0],coalMine:[-5.25,2.05,.25],huntersHut:[-5.15,-1.65,.18],embassy:[-4.65,5.35,.2],researchCenter:[-1.45,6.0,.02],
 shelter:[4.55,2.15,-.24],infirmary:[4.7,5.35,-.28],ironMine:[1.7,6.0,-.04],infantryCamp:[-5.15,-5.35,.12],marksmanCamp:[-1.55,-5.6,.04],
 sawmill:[2.1,-5.55,-.05],storehouse:[5.4,-5.25,-.1],lancerCamp:[5.95,-1.8,-.22]
}
const mat=(color,rough=.88,metal=.02)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})
const box=(w,h,d,m)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.castShadow=true;o.receiveShadow=true;return o}
const curve=(pts,closed=false)=>new THREE.CatmullRomCurve3(pts.map(([x,z])=>new THREE.Vector3(x,0,z)),closed,'centripetal',.16)

function fit(view,{w=2,h=2,d=2}){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=Math.min(w/Math.max(.001,s.x),h/Math.max(.001,s.y),d/Math.max(.001,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function fitRoad(view,size=2.1){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=size/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function roadAsset(root,bank,key,x,z,rot=0,size=2.1,y=.03){if(!bank?.models?.[key])return;const v=fitRoad(bank.clone(key),size);v.position.set(x,y,z);v.rotation.y=rot;root.add(v)}
function propAsset(root,bank,key,x,z,rot=0,{w=.18,h=1.05,d=.18}={}){if(!bank?.models?.[key])return;const v=fit(bank.clone(key),{w,h,d});v.position.set(x,.02,z);v.rotation.y=rot;root.add(v)}
function tree(root,bank,x,z,h=1.05,i=0){const v=bank?.cloneTree?.(i,h);if(!v)return;v.position.set(x,0,z);v.rotation.y=(i*.81)%6.283;root.add(v)}
function tag(root,id){root.userData.buildingId=id;root.traverse(o=>o.userData.buildingId=id);return root}
function unlocked(state,id){return id==='furnace'||(state.buildings.furnace??1)>=(BUILDINGS[id]?.unlockFurnace??1)}
function label(text,color){const c=document.createElement('canvas');c.width=520;c.height=90;const x=c.getContext('2d');x.fillStyle='rgba(8,24,21,.9)';x.roundRect(8,9,504,72,16);x.fill();x.strokeStyle=`#${color.toString(16).padStart(6,'0')}`;x.lineWidth=3;x.stroke();x.fillStyle='#eef2eb';x.font='800 20px Inter,Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text.toUpperCase(),260,45,450);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(2.2,.38,1);return s}
function building(bank,id,lvl){const hq=id==='furnace',industrial=['sawmill','storehouse','lancerCamp'].includes(id),growth=1+Math.min(12,Math.max(1,lvl))*.008,target=hq?{w:2.8*growth,h:2.75*growth,d:2.35*growth}:industrial?{w:2.2*growth,h:1.75*growth,d:1.95*growth}:{w:1.86*growth,h:1.92*growth,d:1.62*growth};const g=new THREE.Group(),pad=box(target.w+.48,.055,target.d+.42,mat(hq?0x587264:industrial?0x4f6359:0x687d71,.98));pad.position.y=.02;pad.castShadow=false;g.add(pad);const v=fit(bank?.clone?.(ASSET[id]??'achuOffice')??new THREE.Group(),target);v.position.y=.07;g.add(v);const l=label(hq?'ACHU HQ':BUILDINGS[id]?.name??id,ACCENT[id]??0x50d4a1);l.position.set(0,target.h+.28,0);l.scale.multiplyScalar(hq?.82:.66);g.add(l);return tag(g,id)}
function plot(id,active=false){const g=new THREE.Group(),c=ACCENT[id]??0x50d4a1,p=box(1.8,.05,1.45,mat(active?0x7a6847:0x53655b,.98));p.position.y=.02;g.add(p);const l=label(active?'DEVELOPING':BUILDINGS[id]?.name??id,c);l.position.set(0,.7,0);l.scale.multiplyScalar(.58);g.add(l);return tag(g,id)}
function ribbonGeometry(c,width,y=.012,segments=120){const verts=[],idx=[];for(let i=0;i<=segments;i++){const u=i/segments,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),nx=-t.z,nz=t.x;verts.push(p.x+nx*width/2,y,p.z+nz*width/2,p.x-nx*width/2,y,p.z-nz*width/2)}for(let i=0;i<segments;i++){const q=i*2;idx.push(q,q+1,q+2,q+1,q+3,q+2)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g}
function ribbon(root,c,width,color,y=.012){const m=new THREE.Mesh(ribbonGeometry(c,width,y),mat(color,.98));m.receiveShadow=true;m.castShadow=false;root.add(m);return m}
function road(root,c,width=1.48){ribbon(root,c,width+.56,0xa9b3ad,-.004);ribbon(root,c,width,0x34403e,.016);const dm=mat(0xe2e4dc,.7);for(let i=1;i<46;i+=2){const u=i/46,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),d=box(.045,.012,.38,dm);d.position.set(p.x,.055,p.z);d.rotation.y=Math.atan2(t.x,t.z);d.castShadow=false;root.add(d)}}
function footpath(root,c,width=.34){ribbon(root,c,width,0xd0d6cf,.032)}
function parking(root,bank,x,z,rot=0,count=4,logistics=false,user=false){const g=new THREE.Group();g.position.set(x,.04,z);g.rotation.y=rot;const p=box(3.0,.035,1.85,mat(0x3b4643,.99));p.castShadow=false;g.add(p);for(let i=-2;i<=2;i++){const l=box(.03,.012,1.52,mat(0xe7e8df,.75));l.position.set(i*.55,.03,0);l.castShadow=false;g.add(l)}for(let i=0;i<count;i++){let v;if(user&&bank?.cloneCar)v=fit(bank.cloneCar(i),{w:.65,h:.52,d:.92});else v=fit(bank?.clone?.(logistics?['carVan','carDelivery','carTruck'][i%3]:i%2?'carSuv':'carSedan')??new THREE.Group(),{w:.65,h:.52,d:.92});v.position.set(-.82+i*.55,.05,0);g.add(v)}root.add(g)}
function fitVehicle(view,target=.78){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),longX=s.x>s.z*1.08,sc=target/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);if(longX)view.rotation.y=-Math.PI/2;view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;view.userData.forwardOffset=0;return view}
function vehicle(root,bank,key='carSedan',target=.78){const v=fitVehicle(bank?.clone?.(key)??new THREE.Group(),target);root.add(v);return v}
function bench(root,x,z,r=0){const g=new THREE.Group(),wood=mat(0x6c5947,.9),metal=mat(0x303937,.82,.14);const seat=box(.8,.09,.26,wood);seat.position.y=.32;g.add(seat);for(const xx of[-.3,.3]){const leg=box(.06,.3,.06,metal);leg.position.set(xx,.15,0);g.add(leg)}g.position.set(x,0,z);g.rotation.y=r;root.add(g)}

const ENTRY=curve([[0,-9.1],[0,-7.2],[0,-5.0],[0,-3.2]])
const LOOP=curve([[0,-3.2],[-3.3,-3.0],[-5.6,-1.2],[-5.8,2.5],[-4.4,5.0],[-1.6,6.3],[1.8,6.25],[4.4,5.0],[5.8,2.5],[5.6,-1.2],[3.2,-3.0],[0,-3.2]],true)
const SERVICE=curve([[3.4,-2.9],[5.2,-3.6],[6.8,-4.8],[6.8,-6.6]])
const ADMIN=curve([[-4.5,4.8],[-5.7,5.6],[-6.4,6.5]])
const WALK_HQ=curve([[-2.4,.2],[-2.6,1.7],[-1.8,3.0],[0,3.7],[1.9,3.0],[2.5,1.6],[2.3,.2],[0,-.65],[-2.4,.2]],true)
export const BASE_WALK_ROUTES=[WALK_HQ,curve([[-5.3,-2.0],[-5.2,.2],[-5.0,2.5],[-4.4,4.7]]),curve([[4.8,-1.8],[5.1,.3],[5.0,2.8],[4.4,4.8]]),curve([[-3.0,-5.6],[-1.4,-4.5],[0,-3.7],[1.5,-4.4],[3.1,-5.5]]),curve([[-3.4,5.2],[-1.8,5.8],[0,6.0],[1.8,5.8],[3.4,5.1]])]

function buildGround(root,bank){const outer=box(18.6,.16,18.2,mat(0x486157,1));outer.position.y=-.2;outer.castShadow=false;root.add(outer);const inner=box(17.5,.05,17.1,mat(0x789286,1));inner.position.y=-.09;inner.castShadow=false;root.add(inner);const centre=new THREE.Mesh(new THREE.CircleGeometry(3.45,52),mat(0xaeb9b1,.98));centre.rotation.x=-Math.PI/2;centre.position.set(0,.006,1.3);centre.receiveShadow=true;root.add(centre);const lawn=box(5.4,.03,3.5,mat(0x668874,1));lawn.position.set(-.1,-.045,4.7);lawn.castShadow=false;root.add(lawn);bench(root,-2.0,3.2,.2);bench(root,2.0,3.2,-.2);bench(root,-.2,4.7,0);for(let i=0;i<22;i++){const a=i*1.73,r=7.7+(i%3)*.25,x=Math.cos(a)*r,z=Math.sin(a)*r*.93;if(z<-6.7&&Math.abs(x)<2.2)continue;tree(root,bank,x,z,1.0+(i%4)*.1,i)}}
function buildRoads(root,bank){road(root,ENTRY,1.62);road(root,LOOP,1.5);road(root,SERVICE,1.38);road(root,ADMIN,1.22);roadAsset(root,bank,'roadRoundabout',0,-3.15,0,3.05);roadAsset(root,bank,'roadCrossing',0,.05,Math.PI/2,1.8);roadAsset(root,bank,'roadDrivewayDouble',5.7,-3.9,-.75,1.65);roadAsset(root,bank,'roadDrivewaySingle',-5.0,4.9,.7,1.55);roadAsset(root,bank,'roadSplit',0,-5.0,0,1.9);propAsset(root,bank,'roadSignStop',-3.4,-3.0,.1,{w:.22,h:.68,d:.22});propAsset(root,bank,'roadSignStreet',.55,-6.1,Math.PI,{w:.22,h:.72,d:.22});for(const [x,z,r] of[[-5.2,.3,.1],[-4.5,4.0,.2],[5.2,.3,Math.PI],[4.6,4.0,Math.PI],[0,5.8,Math.PI/2],[0,-7.2,-Math.PI/2]])propAsset(root,bank,'roadLightCurved',x,z,r,{w:.16,h:1.0,d:.16});for(const [x,z,r] of[[6.9,-5.6,0],[6.9,-6.2,0],[6.9,-6.8,0]])propAsset(root,bank,'roadFence',x,z,r,{w:.75,h:.55,d:.12});propAsset(root,bank,'roadBarrier',6.1,-6.8,0,{w:.7,h:.38,d:.16})}
function buildBuildings(root,bank,state){for(const id of Object.keys(BUILDINGS)){const spec=LOTS[id];if(!spec)continue;const lvl=state.buildings[id]??0,active=state.construction?.id===id;let v=null;if(lvl>0||id==='furnace')v=building(bank,id,Math.max(1,lvl));else if(unlocked(state,id))v=plot(id,active);if(v){v.position.set(spec[0],.08,spec[1]);v.rotation.y=spec[2];root.add(v)}}}
function buildParking(root,bank){parking(root,bank,-6.15,-6.35,.08,4,false,true);parking(root,bank,5.75,-6.35,-.08,4,true,false);parking(root,bank,6.0,6.35,Math.PI,3,false,false)}
function buildFootpaths(root){footpath(root,WALK_HQ,.36);footpath(root,curve([[-5.0,-1.0],[-4.5,.6],[-3.2,1.3]]),.32);footpath(root,curve([[5.0,-1.0],[4.6,.7],[3.2,1.3]]),.32);footpath(root,curve([[-3.0,5.4],[-1.5,4.7],[0,4.25],[1.5,4.7],[3.0,5.35]]),.31)}
function buildTraffic(root,bank){const routes=[LOOP,LOOP,ENTRY,SERVICE],traffic=[];for(let i=0;i<6;i++){const v=vehicle(root,bank,['carSedan','carSuv','carVan','carDelivery','carSedan','carVan'][i],.72+(i%2)*.04);traffic.push({view:v,curve:routes[i%routes.length],offset:(i*.173)%1,speed:.0000062+(i%3)*.00000065,pingpong:i>=2});v.position.y=.09}return traffic}

export function buildBaseV15(bank,state){const root=new THREE.Group();root.name='achu-base-v15';buildGround(root,bank);buildRoads(root,bank);buildFootpaths(root);buildBuildings(root,bank,state);buildParking(root,bank);root.userData.traffic=buildTraffic(root,bank);return root}
export function baseBuildingPositionV15(id){const p=LOTS[id]??[0,0,0];return new THREE.Vector3(p[0],0,p[1])}
export function animateBaseTrafficV15(traffic,now){for(const t of traffic??[]){let u=(t.offset+now*t.speed)%1,dir=1;if(t.pingpong){const raw=(t.offset+now*t.speed)%2;u=raw<=1?raw:2-raw;dir=raw<=1?1:-1}const p=t.curve.getPointAt(u),tan=t.curve.getTangentAt(u).normalize().multiplyScalar(dir);t.view.position.set(p.x,.09,p.z);t.view.rotation.y=Math.atan2(tan.x,tan.z)+(t.view.userData.forwardOffset??0)}}