import * as THREE from 'three'
import { BUILDINGS } from '../data/buildings.js'

const ACCENT={furnace:0x50d4a1,shelter:0x67b9e8,sawmill:0xe9aa54,huntersHut:0xe88170,coalMine:0xe6c159,storehouse:0x76aee3,infantryCamp:0x62d99b,infirmary:0x61cfc6,ironMine:0xb991e5,lancerCamp:0x5fa8e0,embassy:0xe9c06a,marksmanCamp:0xe486ad,researchCenter:0x69d5df}
const ASSET={furnace:'achuHq',shelter:'achuClient',sawmill:'achuDepot',huntersHut:'achuSmallOffice',coalMine:'achuStudio',storehouse:'achuWarehouse',infantryCamp:'achuOffice',infirmary:'achuClient',ironMine:'achuSmallOffice',lancerCamp:'achuDepot',embassy:'achuStudio',marksmanCamp:'achuSmallOffice',researchCenter:'achuOffice'}
const INDUSTRIAL=new Set(['sawmill','storehouse','lancerCamp'])
const BASE_LAYOUT={furnace:{p:[0,1.6],r:0},shelter:{p:[5.1,1.2],r:-1.25},huntersHut:{p:[8.6,5.8],r:-1.6},coalMine:{p:[4.4,8.7],r:-2.7},marksmanCamp:{p:[0,10.7],r:Math.PI},embassy:{p:[-4.5,8.6],r:2.6},researchCenter:{p:[-8.5,5.8],r:1.55},infirmary:{p:[-9.0,1.1],r:1.15},infantryCamp:{p:[-8.0,-4.5],r:.55},ironMine:{p:[-4.9,-8.5],r:.18},sawmill:{p:[0,-10.0],r:0},storehouse:{p:[5.1,-8.7],r:-.18},lancerCamp:{p:[9.0,-4.8],r:-.7}}
const mat=(color,rough=.82,metal=.03)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})
const box=(w,h,d,m)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.castShadow=true;o.receiveShadow=true;return o}
const curve=points=>new THREE.CatmullRomCurve3(points.map(([x,z])=>new THREE.Vector3(x,0,z)),false,'centripetal',.22)
const closedCurve=points=>new THREE.CatmullRomCurve3(points.map(([x,z])=>new THREE.Vector3(x,0,z)),true,'centripetal',.22)
function ribbonGeometry(c,width,y=.02,segments=110){const verts=[],idx=[];for(let i=0;i<=segments;i++){const u=i/segments,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),nx=-t.z,nz=t.x;verts.push(p.x+nx*width/2,y,p.z+nz*width/2,p.x-nx*width/2,y,p.z-nz*width/2)}for(let i=0;i<segments;i++){const q=i*2;idx.push(q,q+1,q+2,q+1,q+3,q+2)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g}
function ribbon(parent,c,width,color,y=.02){const m=new THREE.Mesh(ribbonGeometry(c,width,y),mat(color,.97));m.receiveShadow=true;m.castShadow=false;parent.add(m);return m}
function dashed(parent,c,count=58,y=.075){const dm=mat(0xe7e9e3,.7);for(let i=1;i<count;i+=2){const u=i/count,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),d=box(.055,.018,.50,dm);d.position.set(p.x,y,p.z);d.rotation.y=Math.atan2(t.x,t.z);d.castShadow=false;parent.add(d)}}
function fit(view,{w=2,h=2,d=2}){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=Math.min(w/Math.max(.001,s.x),h/Math.max(.001,s.y),d/Math.max(.001,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function fitRoad(view,size=2.7){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=size/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function roadAsset(parent,bank,key,x,z,rot=0,size=2.7,y=.04){const v=fitRoad(bank?.clone?.(key)??new THREE.Group(),size);v.position.set(x,y,z);v.rotation.y=rot;parent.add(v);return v}
function tag(root,id){root.userData.buildingId=id;root.traverse(o=>o.userData.buildingId=id);return root}
function sign(text,color){const c=document.createElement('canvas');c.width=640;c.height=128;const x=c.getContext('2d');x.fillStyle='rgba(12,26,23,.92)';x.roundRect(12,17,616,94,22);x.fill();x.strokeStyle=`#${color.toString(16).padStart(6,'0')}`;x.lineWidth=3;x.stroke();x.fillStyle='#eef2eb';x.font='800 29px Inter,Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text.toUpperCase(),320,64,560);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(4.05,.82,1);return s}
function ring(parent,r,color,opacity=.35){const m=new THREE.Mesh(new THREE.RingGeometry(r*.82,r,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.y=.09;parent.add(m)}
function tree(parent,bank,x,z,h=1.5,i=0){const v=bank?.cloneTree?.(i,h);if(!v)return;v.position.set(x,0,z);v.rotation.y=(i*.91)%6.283;parent.add(v)}
function buildingView(bank,id,lvl){const g=new THREE.Group(),key=ASSET[id],hq=id==='furnace',industrial=INDUSTRIAL.has(id),growth=1+Math.min(12,Math.max(1,lvl))*.012;const target=hq?{w:3.25*growth,h:3.15*growth,d:2.85*growth}:industrial?{w:2.9*growth,h:2.0*growth,d:2.45*growth}:{w:2.45*growth,h:2.35*growth,d:2.1*growth};const pad=box(target.w+.46,.07,target.d+.46,mat(hq?0x4f6b5e:industrial?0x556760:0x61766b,.98));pad.position.y=.025;pad.castShadow=false;g.add(pad);const model=fit(bank?.clone?.(key)??new THREE.Group(),target);g.add(model);const label=sign(hq?'ACHU HQ':BUILDINGS[id]?.name??id,ACCENT[id]??0x50d4a1);label.position.set(0,target.h+.55,0);label.scale.multiplyScalar(.82);g.add(label);ring(g,hq?1.48:1.08,ACCENT[id]??0x50d4a1,hq?.58:.28);return tag(g,id)}
function plot(id,active=false){const g=new THREE.Group(),c=ACCENT[id]??0x50d4a1,pad=box(2.65,.06,2.18,mat(active?0x756544:0x596c63,.98));pad.position.y=.025;pad.castShadow=false;g.add(pad);ring(g,1.0,c,.44);const l=sign(active?'DEVELOPING':BUILDINGS[id]?.name??id,c);l.position.set(0,1.0,0);l.scale.multiplyScalar(.70);g.add(l);return tag(g,id)}
function unlocked(state,id){return id==='furnace'||(state.buildings.furnace??1)>=(BUILDINGS[id]?.unlockFurnace??1)}
function fitVehicle(view,target=1.18){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),longX=s.x>s.z*1.08,sc=target/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;view.userData.forwardOffset=longX?-Math.PI/2:0;return view}
function vehicle(parent,bank,index=0,target=1.18){const v=fitVehicle(bank?.cloneCar?.(index)??bank?.clone?.('carSedan')??new THREE.Group(),target);parent.add(v);return v}
function parking(parent,bank,x,z,rot=0,count=4){const g=new THREE.Group();g.position.set(x,.05,z);g.rotation.y=rot;const pad=box(4.2,.05,2.5,mat(0x3b4645,.99));pad.castShadow=false;g.add(pad);for(let i=-2;i<=2;i++){const line=box(.035,.018,2.04,mat(0xe3e5de,.78));line.position.set(i*.78,.045,0);line.castShadow=false;g.add(line)}for(let i=0;i<count;i++){const v=vehicle(g,bank,i,.92+(i%2)*.05);v.position.set(-1.18+i*.78,.07,(i%2)*.12-.08);v.rotation.y=v.userData.forwardOffset??0}parent.add(g)}
function roadLight(parent,bank,x,z,rot=0){if(!bank?.models?.roadLightCurved)return;const v=fit(bank.clone('roadLightCurved'),{w:.23,h:1.55,d:.23});v.position.set(x,.04,z);v.rotation.y=rot;parent.add(v)}
const RING=closedCurve([[0,-4.8],[-5.3,-4.9],[-8.8,-1.7],[-8.9,3.8],[-5.7,7.7],[0,9.4],[5.8,7.7],[8.9,3.8],[8.8,-1.7],[5.3,-4.9]])
const ENTRANCE=curve([[0,-14.2],[0,-9.5],[0,-4.8]])
const NORTH=curve([[0,-4.8],[0,-1.2],[0,2.3],[0,6.8],[0,9.3]])
const WEST=curve([[-3.8,-4.9],[-6.2,-6.1],[-8.7,-7.4]])
const EAST=curve([[3.8,-4.9],[6.2,-6.2],[9.7,-7.4]])
const NW=curve([[-8.3,2.4],[-10.2,4.8],[-10.5,7.7]])
const NE=curve([[8.3,2.4],[10.2,4.8],[10.5,7.7]])
export const BASE_WALK_ROUTES=[curve([[-2.4,-1.7],[-4.5,-.7],[-6.8,1.4],[-7.8,4.2]]),curve([[2.2,-1.5],[4.3,-.3],[6.3,2.0],[7.5,4.4]]),curve([[-5.5,6.5],[-2.3,7.4],[1.8,7.4],[5.2,6.4]]),curve([[-6.2,-4.6],[-4.2,-5.5],[-2.1,-6.6],[0,-7.0]]),curve([[2.0,-6.9],[4.4,-6.2],[6.8,-5.0],[8.1,-3.8]]),curve([[-1.5,2.1],[0,3.2],[2.0,2.8],[3.8,1.2]])]
function buildRoads(root,bank){for(const c of[RING,ENTRANCE,NORTH,WEST,EAST,NW,NE]){ribbon(root,c,3.0,0x7f8e88,.015);ribbon(root,c,2.14,0x263334,.04);dashed(root,c,c===RING?76:40)}roadAsset(root,bank,'roadRoundabout',0,-4.8,0,3.6,.055);roadAsset(root,bank,'roadRoundabout',0,3.0,0,3.0,.055);roadAsset(root,bank,'roadSplit',0,-7.1,0,2.75,.055);roadAsset(root,bank,'roadDrivewayDouble',5.0,-8.0,.55,2.45,.055);roadAsset(root,bank,'roadDrivewayDouble',-5.0,-7.9,-.55,2.45,.055);roadAsset(root,bank,'roadDrivewaySingle',8.1,1.6,-1.1,2.2,.055);roadAsset(root,bank,'roadCrossing',0,-1.0,Math.PI/2,2.35,.055);for(const [x,z,r] of[[-8.2,0.2,.7],[-7.2,6.8,2.2],[2.0,8.8,-2.7],[8.0,5.5,-2.3],[8.4,-1.2,-1.1],[5.4,-7.2,-.2],[-2.8,-6.1,.5],[0,-11.8,0]])roadLight(root,bank,x,z,r)}
function landscaping(root,bank){const ground=new THREE.Mesh(new THREE.PlaneGeometry(32,30),mat(0x4f6b5e,1));ground.rotation.x=-Math.PI/2;ground.position.y=-.14;ground.receiveShadow=true;root.add(ground);const campus=new THREE.Mesh(new THREE.CircleGeometry(14.9,72),mat(0x6c8477,1));campus.rotation.x=-Math.PI/2;campus.position.y=-.10;campus.receiveShadow=true;root.add(campus);const plaza=new THREE.Mesh(new THREE.CircleGeometry(3.25,48),mat(0xaebbb2,.98));plaza.rotation.x=-Math.PI/2;plaza.position.y=.015;root.add(plaza);for(let i=0;i<30;i++){const a=i*2.399,r=11.4+(i%4)*.7,x=Math.cos(a)*r,z=Math.sin(a)*r;if(z<-11&&Math.abs(x)<2.3)continue;tree(root,bank,x,z,1.25+(i%4)*.16,i)}for(const [x,z] of[[-4,2.5],[-4.8,3.8],[4,4.1],[4.8,5.3],[-2.8,5.6],[2.3,6.0]])tree(root,bank,x,z,1.15,90+Math.round(x*10+z));const fountainBase=box(1.5,.18,1.5,mat(0x8b9b94,.9));fountainBase.position.set(0,.10,3.0);root.add(fountainBase);const water=new THREE.Mesh(new THREE.CylinderGeometry(.55,.65,.10,28),mat(0x58a2a5,.34));water.position.set(0,.22,3.0);root.add(water)}
function buildBuildings(root,bank,state){for(const id of Object.keys(BUILDINGS)){const spec=BASE_LAYOUT[id];if(!spec)continue;const lvl=state.buildings[id]??0,active=state.construction?.id===id;let v=null;if(lvl>0||id==='furnace')v=buildingView(bank,id,Math.max(1,lvl));else if(unlocked(state,id))v=plot(id,active);if(v){v.position.set(spec.p[0],.09,spec.p[1]);v.rotation.y=spec.r;root.add(v)}}}
function buildParking(root,bank){parking(root,bank,4.4,-4.5,-.35,4);parking(root,bank,7.2,1.2,-1.05,3);parking(root,bank,-6.7,-3.8,.4,3);parking(root,bank,5.4,-11.1,0,4)}
function buildTraffic(root,bank){const routes=[RING,RING,EAST,ENTRANCE,NORTH],traffic=[];for(let i=0;i<7;i++){const v=vehicle(root,bank,i,1.02+(i%3)*.07);traffic.push({view:v,curve:routes[i%routes.length],offset:(i*.17)%1,speed:.0000062+(i%3)*.0000008,pingpong:i>=4});v.position.y=.11}return traffic}
export function buildBaseV10(bank,state){const root=new THREE.Group();root.name='achu-base-v10-campus';landscaping(root,bank);buildRoads(root,bank);buildBuildings(root,bank,state);buildParking(root,bank);root.userData.traffic=buildTraffic(root,bank);return root}
export function baseBuildingPositionV10(id){const p=BASE_LAYOUT[id]?.p??[0,0];return new THREE.Vector3(p[0],0,p[1])}
export function animateBaseTrafficV10(traffic,now){for(const t of traffic??[]){let u=(t.offset+now*t.speed)%1,dir=1;if(t.pingpong){const raw=(t.offset+now*t.speed)%2;u=raw<=1?raw:2-raw;dir=raw<=1?1:-1}const p=t.curve.getPointAt(u),tan=t.curve.getTangentAt(u).normalize().multiplyScalar(dir);t.view.position.set(p.x,.11,p.z);t.view.rotation.y=Math.atan2(tan.x,tan.z)+(t.view.userData.forwardOffset??0)}}
