import * as THREE from 'three'
import { BUILDINGS } from '../data/buildings.js'

const ACCENT={furnace:0x50d4a1,shelter:0x67b9e8,sawmill:0xe9aa54,huntersHut:0xe88170,coalMine:0xe6c159,storehouse:0x76aee3,infantryCamp:0x62d99b,infirmary:0x61cfc6,ironMine:0xb991e5,lancerCamp:0x5fa8e0,embassy:0xe9c06a,marksmanCamp:0xe486ad,researchCenter:0x69d5df}
const ASSET={furnace:'achuHq',shelter:'achuClient',sawmill:'achuDepot',huntersHut:'achuSmallOffice',coalMine:'achuStudio',storehouse:'achuWarehouse',infantryCamp:'achuOffice',infirmary:'achuClient',ironMine:'achuSmallOffice',lancerCamp:'achuDepot',embassy:'achuStudio',marksmanCamp:'achuSmallOffice',researchCenter:'achuOffice'}
const INDUSTRIAL=new Set(['sawmill','storehouse','lancerCamp'])
const BASE_LAYOUT={furnace:{p:[0,0],r:0},shelter:{p:[5.6,1.2],r:-Math.PI/2},huntersHut:{p:[7.9,5.2],r:-Math.PI/2},coalMine:{p:[-4.9,5.4],r:Math.PI},marksmanCamp:{p:[-8,5],r:Math.PI/2},embassy:{p:[-5.8,-4.2],r:.45},researchCenter:{p:[-8.1,.2],r:Math.PI/2},infirmary:{p:[4.8,-5],r:-.55},infantryCamp:{p:[-2.2,-7],r:.15},ironMine:{p:[2,-7.2],r:-.12},sawmill:{p:[8.3,-4.2],r:-Math.PI/2},storehouse:{p:[10.1,-.7],r:-Math.PI/2},lancerCamp:{p:[9.8,3.6],r:-Math.PI/2}}
const mat=(color,rough=.82,metal=.03)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})
const box=(w,h,d,m)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.castShadow=true;o.receiveShadow=true;return o}
const curve=points=>new THREE.CatmullRomCurve3(points.map(([x,z])=>new THREE.Vector3(x,0,z)),false,'centripetal',.25)
const closedCurve=points=>new THREE.CatmullRomCurve3(points.map(([x,z])=>new THREE.Vector3(x,0,z)),true,'centripetal',.25)
function ribbonGeometry(c,width,y=.006,segments=120){const verts=[],idx=[];for(let i=0;i<=segments;i++){const u=i/segments,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),nx=-t.z,nz=t.x;verts.push(p.x+nx*width/2,y,p.z+nz*width/2,p.x-nx*width/2,y,p.z-nz*width/2)}for(let i=0;i<segments;i++){const q=i*2;idx.push(q,q+1,q+2,q+1,q+3,q+2)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g}
function ribbon(parent,c,width,color,y=.006){const m=new THREE.Mesh(ribbonGeometry(c,width,y),mat(color,.96));m.receiveShadow=true;m.castShadow=false;parent.add(m);return m}
function laneMarks(parent,c,count=42,y=.035){const dm=mat(0xe1e3da,.72);for(let i=1;i<count;i+=2){const u=i/count,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),d=box(.055,.012,.46,dm);d.position.set(p.x,y,p.z);d.rotation.y=Math.atan2(t.x,t.z);d.castShadow=false;parent.add(d)}}
function fit(view,{w=2,h=2,d=2}){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=Math.min(w/Math.max(.001,s.x),h/Math.max(.001,s.y),d/Math.max(.001,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function fitRoad(view,size=2.6){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=size/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function roadAsset(parent,bank,key,x,z,rot=0,size=2.6,y=.02){const v=fitRoad(bank?.clone?.(key)??new THREE.Group(),size);v.position.set(x,y,z);v.rotation.y=rot;parent.add(v);return v}
function sign(text,color){const c=document.createElement('canvas');c.width=640;c.height=128;const x=c.getContext('2d');x.fillStyle='rgba(12,26,23,.9)';x.roundRect(12,17,616,94,22);x.fill();x.strokeStyle=`#${color.toString(16).padStart(6,'0')}`;x.lineWidth=3;x.stroke();x.fillStyle='#eef2eb';x.font='800 29px Inter,Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text.toUpperCase(),320,64,560);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(4.15,.84,1);return s}
function tag(root,id){root.userData.buildingId=id;root.traverse(o=>o.userData.buildingId=id);return root}
function tree(parent,bank,x,z,h=1.55,i=0){const v=bank?.cloneTree?.(i,h);if(!v)return;v.position.set(x,0,z);v.rotation.y=(i*.91)%6.283;parent.add(v)}
function ring(parent,r,color,opacity=.42){const m=new THREE.Mesh(new THREE.RingGeometry(r*.82,r,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.y=.07;parent.add(m)}
function buildingView(bank,id,lvl){const g=new THREE.Group(),key=ASSET[id],hq=id==='furnace',industrial=INDUSTRIAL.has(id),growth=1+Math.min(12,Math.max(1,lvl))*.012;const target=hq?{w:3.3*growth,h:3.2*growth,d:2.9*growth}:industrial?{w:2.85*growth,h:2*growth,d:2.45*growth}:{w:2.35*growth,h:2.25*growth,d:2.05*growth};const pad=box(target.w+.5,.055,target.d+.5,mat(hq?0x4f6b5e:industrial?0x52645d:0x60756a,.98));pad.position.y=.02;pad.castShadow=false;g.add(pad);const model=fit(bank?.clone?.(key)??new THREE.Group(),target);model.position.y=.07;g.add(model);const label=sign(hq?'ACHU HQ':BUILDINGS[id]?.name??id,ACCENT[id]??0x50d4a1);label.position.set(0,target.h+.55,0);label.scale.multiplyScalar(.83);g.add(label);ring(g,hq?1.48:1.05,ACCENT[id]??0x50d4a1,hq?.58:.25);return tag(g,id)}
function plot(id,active=false){const g=new THREE.Group(),c=ACCENT[id]??0x50d4a1,pad=box(2.55,.05,2.1,mat(active?0x756544:0x53655d,.98));pad.position.y=.02;pad.castShadow=false;g.add(pad);ring(g,.96,c,.4);const l=sign(active?'DEVELOPING':BUILDINGS[id]?.name??id,c);l.position.set(0,.95,0);l.scale.multiplyScalar(.7);g.add(l);return tag(g,id)}
function unlocked(state,id){return id==='furnace'||(state.buildings.furnace??1)>=(BUILDINGS[id]?.unlockFurnace??1)}
function fitVehicle(view,target=1.18){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),longX=s.x>s.z*1.08,sc=target/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;view.userData.forwardOffset=longX?Math.PI/2:0;return view}
function vehicle(parent,bank,index=0,target=1.18,key=null){const source=key?bank?.clone?.(key):bank?.cloneCar?.(index);const v=fitVehicle(source??bank?.clone?.('carSedan')??new THREE.Group(),target);parent.add(v);return v}
function parking(parent,bank,x,z,rot=0,count=4,logistics=false){const g=new THREE.Group();g.position.set(x,.02,z);g.rotation.y=rot;const pad=box(4.4,.035,2.55,mat(0x3e4948,.99));pad.castShadow=false;g.add(pad);for(let i=-2;i<=2;i++){const line=box(.035,.012,2.08,mat(0xe1e3da,.78));line.position.set(i*.82,.03,0);line.castShadow=false;g.add(line)}for(let i=0;i<count;i++){const key=logistics?['carVan','carDelivery','carTruck'][i%3]:null;const v=vehicle(g,bank,i,.9+(i%2)*.06,key);v.position.set(-1.23+i*.82,.05,(i%2)*.1-.05);v.rotation.y=v.userData.forwardOffset??0}parent.add(g)}
function roadLight(parent,bank,x,z,rot=0){if(!bank?.models?.roadLightCurved)return;const v=fit(bank.clone('roadLightCurved'),{w:.23,h:1.65,d:.23});v.position.set(x,.02,z);v.rotation.y=rot;parent.add(v)}
const ACCESS=curve([[0,-15],[0,-11],[0,-8.4],[0,-5]])
const CENTRAL=closedCurve([[0,-5],[-5.6,-4.4],[-8.7,-.6],[-8.4,4.5],[-5,8.2],[-.5,9.2],[4.8,8.1],[8.2,4.6],[8.3,.2],[5.5,-3.5],[0,-5]])
const EAST_SERVICE=curve([[5.5,-3.5],[8.6,-5.3],[11.2,-4.3],[11.5,.5],[10.2,4.7]])
const WEST_OFFICE=curve([[-5.6,-4.4],[-8.4,-5.6],[-10.5,-3.3],[-10.4,2.2],[-8.4,4.5]])
const NORTH_TRAINING=curve([[-.5,9.2],[1,11],[5,11.3],[8,9.1]])
const INNER_WALK=closedCurve([[-3.7,-2.2],[-4.6,1.3],[-3.1,4.1],[0,4.8],[3.4,3.8],[4.3,.6],[3.1,-2.4],[0,-3.1],[-3.7,-2.2]])
export const BASE_WALK_ROUTES=[INNER_WALK,curve([[-7.8,3.4],[-6.1,2.7],[-4.5,1.9],[-3.6,.8]]),curve([[4,-1.4],[5.2,-2.8],[6.8,-3.8],[8,-4]]),curve([[-2.3,7.5],[0,7.8],[2.5,7.4],[4.5,6.5]]),curve([[-6.8,-3.7],[-5.1,-2.9],[-3.9,-1.9],[-3.2,-.8]]),curve([[3.4,3.4],[4.8,4.4],[6.2,5.2],[7.1,5.7]])]
function buildRoads(root,bank){for(const c of[CENTRAL,ACCESS,EAST_SERVICE,WEST_OFFICE,NORTH_TRAINING]){ribbon(root,c,2.45,0x87958e,-.006);ribbon(root,c,1.68,0x394746,.014);laneMarks(root,c)}roadAsset(root,bank,'roadRoundabout',0,-5,0,3.5,.025);roadAsset(root,bank,'roadIntersectionPath',0,4.6,0,2.6,.025);roadAsset(root,bank,'roadSplit',5.5,-3.5,-.8,2.55,.025);roadAsset(root,bank,'roadDrivewayDouble',8.7,-4.5,-1,2.2,.025);roadAsset(root,bank,'roadDrivewaySingle',-8.8,-4.9,.8,2.05,.025);roadAsset(root,bank,'roadCrossing',0,-1.9,Math.PI/2,2.2,.025);roadAsset(root,bank,'roadSideEntry',8.4,.3,-Math.PI/2,2.15,.025);roadAsset(root,bank,'roadSideExit',-8.4,.4,Math.PI/2,2.15,.025);for(const [x,z,r] of[[-7.7,1.2,.8],[-6.4,6.8,2.3],[-1.8,8.8,-2.8],[5.2,7.3,-2.4],[8,2.8,-1.5],[7,-3.9,-.5],[-4.4,-4.7,.5],[0,-11.8,0]])roadLight(root,bank,x,z,r);if(bank?.models?.roadTrafficLight)for(const [x,z,r] of[[-1.1,4,0],[1.1,4.1,Math.PI],[-.5,5.2,Math.PI/2]]){const v=fit(bank.clone('roadTrafficLight'),{w:.24,h:1.25,d:.24});v.position.set(x,.02,z);v.rotation.y=r;root.add(v)}if(bank?.models?.highwaySign){const s=fit(bank.clone('highwaySign'),{w:1.9,h:1.2,d:.35});s.position.set(0,.02,-13.1);s.rotation.y=Math.PI;root.add(s)}}
function landscaping(root,bank){const ground=box(26,.12,24,mat(0x5f786b,1));ground.position.set(0,-.16,-.5);ground.castShadow=false;root.add(ground);const campus=box(23.6,.045,20.8,mat(0x80988b,1));campus.position.set(0,-.07,.2);campus.castShadow=false;root.add(campus);const plaza=new THREE.Mesh(new THREE.CircleGeometry(4,56),mat(0xaebbb2,.98));plaza.rotation.x=-Math.PI/2;plaza.position.y=.008;plaza.receiveShadow=true;root.add(plaza);for(let i=0;i<30;i++){const a=i*2.399,r=10.2+(i%4)*.65,x=Math.cos(a)*r,z=Math.sin(a)*r*.84;if(z<-9&&Math.abs(x)<2.7)continue;tree(root,bank,x,z,1.3+(i%4)*.15,i)}for(const [x,z,i] of[[-4,2.7,60],[-4.8,4,61],[3.8,4.2,62],[4.7,5.2,63],[-2.6,5.4,64],[2.2,6,65]])tree(root,bank,x,z,1.12,i);const pond=new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.35,.10,36),mat(0x5a9ca0,.38));pond.position.set(1,.03,2.6);root.add(pond);const island=new THREE.Mesh(new THREE.CylinderGeometry(.35,.42,.08,24),mat(0x82988a,1));island.position.set(1,.09,2.6);root.add(island)}
function buildBuildings(root,bank,state){for(const id of Object.keys(BUILDINGS)){const spec=BASE_LAYOUT[id];if(!spec)continue;const lvl=state.buildings[id]??0,active=state.construction?.id===id;let v=null;if(lvl>0||id==='furnace')v=buildingView(bank,id,Math.max(1,lvl));else if(unlocked(state,id))v=plot(id,active);if(v){v.position.set(spec.p[0],.08,spec.p[1]);v.rotation.y=spec.r;root.add(v)}}}
function buildParking(root,bank){parking(root,bank,4.6,-3.7,-.35,4);parking(root,bank,7.2,2.1,-1.05,3);parking(root,bank,-6.8,-3,.45,3);parking(root,bank,8.5,-7,0,4,true)}
function buildIndustrialDetails(root,bank){for(const [x,z,r] of[[9.6,-6.2,0],[10.7,-6.2,0],[11.8,-6.2,0]])roadAsset(root,bank,'roadFence',x,z,r,1.05,.02);roadAsset(root,bank,'roadBarrier',7.8,-6.2,0,1,.02);roadAsset(root,bank,'roadCone',7.4,-5.8,0,.75,.02);roadAsset(root,bank,'roadSignWarning',7.2,-5.3,0,.85,.02);roadAsset(root,bank,'roadSignStop',0,-8.5,0,.8,.02);roadAsset(root,bank,'roadSignStreet',-8.5,-1.2,Math.PI/2,.85,.02)}
function buildTraffic(root,bank){const routes=[CENTRAL,CENTRAL,EAST_SERVICE,ACCESS,WEST_OFFICE,NORTH_TRAINING],traffic=[];for(let i=0;i<8;i++){const key=i===5?'carVan':i===6?'carDelivery':i===7?'carTruck':null;const v=vehicle(root,bank,i,1.06+(i%3)*.06,key);traffic.push({view:v,curve:routes[i%routes.length],offset:(i*.137)%1,speed:.0000062+(i%4)*.0000007,pingpong:i>=2});v.position.y=.09}return traffic}
export function buildBaseV11(bank,state){const root=new THREE.Group();root.name='achu-base-v11-campus';landscaping(root,bank);buildRoads(root,bank);buildBuildings(root,bank,state);buildParking(root,bank);buildIndustrialDetails(root,bank);root.userData.traffic=buildTraffic(root,bank);return root}
export function baseBuildingPositionV11(id){const p=BASE_LAYOUT[id]?.p??[0,0];return new THREE.Vector3(p[0],0,p[1])}
export function animateBaseTrafficV11(traffic,now){for(const t of traffic??[]){let u=(t.offset+now*t.speed)%1,dir=1;if(t.pingpong){const raw=(t.offset+now*t.speed)%2;u=raw<=1?raw:2-raw;dir=raw<=1?1:-1}const p=t.curve.getPointAt(u),tan=t.curve.getTangentAt(u).normalize().multiplyScalar(dir);t.view.position.set(p.x,.09,p.z);t.view.rotation.y=Math.atan2(tan.x,tan.z)+(t.view.userData.forwardOffset??0)}}
