import * as THREE from 'three'
import { BUILDINGS } from '../data/buildings.js'

const ACCENT={furnace:0x50d4a1,shelter:0x67b9e8,sawmill:0xe9aa54,huntersHut:0xe88170,coalMine:0xe6c159,storehouse:0x76aee3,infantryCamp:0x62d99b,infirmary:0x61cfc6,ironMine:0xb991e5,lancerCamp:0x5fa8e0,embassy:0xe9c06a,marksmanCamp:0xe486ad,researchCenter:0x69d5df}
const ASSET={furnace:'achuHq',shelter:'cityC',sawmill:'achuDepot',huntersHut:'cityA',coalMine:'cityJ',storehouse:'achuWarehouse',infantryCamp:'cityL',infirmary:'achuClient',ironMine:'cityS',lancerCamp:'achuDepot',embassy:'cityE',marksmanCamp:'cityG',researchCenter:'cityN'}
const BASE_LAYOUT={
 furnace:{p:[0,1.0],r:0},shelter:{p:[4.1,3.8],r:-.55},huntersHut:{p:[7.5,5.3],r:-1.0},coalMine:{p:[-4.1,4.2],r:.5},marksmanCamp:{p:[-7.4,5.1],r:.9},embassy:{p:[-6.5,-1.5],r:1.15},researchCenter:{p:[-7.7,1.6],r:1.15},infirmary:{p:[4.7,-1.2],r:-.85},infantryCamp:{p:[-3.3,-5.6],r:.15},ironMine:{p:[2.2,-5.9],r:-.1},sawmill:{p:[8.3,-3.8],r:-1.35},storehouse:{p:[9.1,-.3],r:-1.35},lancerCamp:{p:[8.8,2.9],r:-1.35}
}
const mat=(color,rough=.84,metal=.025)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})
const box=(w,h,d,m)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.castShadow=true;o.receiveShadow=true;return o}
const curve=(pts,closed=false)=>new THREE.CatmullRomCurve3(pts.map(([x,z])=>new THREE.Vector3(x,0,z)),closed,'centripetal',.22)
function ribbonGeometry(c,width,y=.012,segments=120){const verts=[],idx=[];for(let i=0;i<=segments;i++){const u=i/segments,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),nx=-t.z,nz=t.x;verts.push(p.x+nx*width/2,y,p.z+nz*width/2,p.x-nx*width/2,y,p.z-nz*width/2)}for(let i=0;i<segments;i++){const q=i*2;idx.push(q,q+1,q+2,q+1,q+3,q+2)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g}
function ribbon(parent,c,width,color,y=.012){const o=new THREE.Mesh(ribbonGeometry(c,width,y),mat(color,.97));o.receiveShadow=true;o.castShadow=false;parent.add(o);return o}
function laneMarks(parent,c,count=44){const m=mat(0xe5e7dd,.7);for(let i=1;i<count;i+=2){const u=i/count,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),d=box(.055,.012,.44,m);d.position.set(p.x,.055,p.z);d.rotation.y=Math.atan2(t.x,t.z);d.castShadow=false;parent.add(d)}}
function sidewalk(parent,c,width){ribbon(parent,c,width+.7,0x87988f,-.002);ribbon(parent,c,width,0x354241,.016);laneMarks(parent,c)}
function fit(view,{w=2,h=2,d=2}){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=Math.min(w/Math.max(.001,s.x),h/Math.max(.001,s.y),d/Math.max(.001,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function fitRoad(view,size=2.4){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=size/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function roadAsset(parent,bank,key,x,z,rot=0,size=2.4,y=.025){const v=fitRoad(bank?.clone?.(key)??new THREE.Group(),size);v.position.set(x,y,z);v.rotation.y=rot;parent.add(v);return v}
function tree(parent,bank,x,z,h=1.4,i=0){const v=bank?.cloneTree?.(i,h);if(!v)return;v.position.set(x,0,z);v.rotation.y=(i*.79)%6.283;parent.add(v)}
function ring(parent,r,color,opacity=.38){const o=new THREE.Mesh(new THREE.RingGeometry(r*.82,r,36),new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}));o.rotation.x=-Math.PI/2;o.position.y=.08;parent.add(o)}
function labelSprite(text,color){const c=document.createElement('canvas');c.width=600;c.height=112;const x=c.getContext('2d');x.fillStyle='rgba(10,25,22,.88)';x.roundRect(8,12,584,88,20);x.fill();x.strokeStyle=`#${color.toString(16).padStart(6,'0')}`;x.lineWidth=3;x.stroke();x.fillStyle='#edf2ea';x.font='800 25px Inter,Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text.toUpperCase(),300,56,535);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(3.2,.6,1);return s}
function tag(root,id){root.userData.buildingId=id;root.traverse(o=>o.userData.buildingId=id);return root}
function unlocked(state,id){return id==='furnace'||(state.buildings.furnace??1)>=(BUILDINGS[id]?.unlockFurnace??1)}
function buildingView(bank,id,lvl){const g=new THREE.Group(),key=ASSET[id]??'achuOffice',hq=id==='furnace',industrial=['sawmill','storehouse','lancerCamp'].includes(id),growth=1+Math.min(12,Math.max(1,lvl))*.012;const target=hq?{w:3.25*growth,h:3.15*growth,d:2.8*growth}:industrial?{w:2.65*growth,h:1.95*growth,d:2.3*growth}:{w:2.18*growth,h:2.15*growth,d:1.9*growth};const pad=box(target.w+.5,.055,target.d+.45,mat(hq?0x5a7567:industrial?0x4d6258:0x647c6f,.98));pad.position.y=.02;pad.castShadow=false;g.add(pad);const model=fit(bank?.clone?.(key)??new THREE.Group(),target);model.position.y=.07;g.add(model);const l=labelSprite(hq?'ACHU HQ':BUILDINGS[id]?.name??id,ACCENT[id]??0x50d4a1);l.position.set(0,target.h+.42,0);l.scale.multiplyScalar(.68);g.add(l);ring(g,hq?1.35:.92,ACCENT[id]??0x50d4a1,hq?.52:.2);return tag(g,id)}
function plot(id,active=false){const g=new THREE.Group(),c=ACCENT[id]??0x50d4a1,pad=box(2.35,.05,1.9,mat(active?0x786445:0x4f6258,.98));pad.position.y=.02;g.add(pad);ring(g,.82,c,.38);const l=labelSprite(active?'DEVELOPING':BUILDINGS[id]?.name??id,c);l.position.set(0,.9,0);l.scale.multiplyScalar(.62);g.add(l);return tag(g,id)}
function fitVehicle(view,target=1.05){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),longX=s.x>s.z*1.08,sc=target/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);if(longX)view.rotation.y=-Math.PI/2;view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;view.userData.forwardOffset=0;return view}
function vehicle(parent,bank,key='carSedan',target=1.05){const v=fitVehicle(bank?.clone?.(key)??new THREE.Group(),target);parent.add(v);return v}
function userCar(parent,bank,index=0,target=.9){const v=fitVehicle(bank?.cloneCar?.(index)??bank?.clone?.('carSedan')??new THREE.Group(),target);parent.add(v);return v}
function parking(parent,bank,x,z,rot=0,count=4,logistics=false,user=false){const g=new THREE.Group();g.position.set(x,.025,z);g.rotation.y=rot;const pad=box(4.15,.035,2.35,mat(0x35403f,.99));pad.castShadow=false;g.add(pad);for(let i=-2;i<=2;i++){const line=box(.035,.012,1.95,mat(0xe7e8df,.78));line.position.set(i*.77,.03,0);line.castShadow=false;g.add(line)}for(let i=0;i<count;i++){const v=user?userCar(g,bank,i,.82+(i%2)*.05):vehicle(g,bank,logistics?['carVan','carDelivery','carTruck'][i%3]:i%2?'carSuv':'carSedan',.82+(i%2)*.05);v.position.set(-1.15+i*.77,.05,(i%2)*.08-.04);v.rotation.y=0}parent.add(g)}
function roadLight(parent,bank,x,z,rot=0){if(!bank?.models?.roadLightCurved)return;const v=fit(bank.clone('roadLightCurved'),{w:.22,h:1.55,d:.22});v.position.set(x,.02,z);v.rotation.y=rot;parent.add(v)}
function bench(parent,x,z,r=0){const g=new THREE.Group(),wood=mat(0x6d5944,.9),metal=mat(0x343d3b,.8,.18);const seat=box(1.05,.12,.32,wood);seat.position.y=.38;g.add(seat);for(const xx of[-.42,.42]){const leg=box(.08,.38,.08,metal);leg.position.set(xx,.2,0);g.add(leg)}g.position.set(x,0,z);g.rotation.y=r;parent.add(g)}
function bollard(parent,x,z){const o=new THREE.Mesh(new THREE.CylinderGeometry(.08,.1,.5,10),mat(0x3b4845,.75,.12));o.position.set(x,.25,z);parent.add(o)}
const ENTRY=curve([[0,-13.5],[0,-10.2],[0,-7.8],[0,-5.5]])
const SPINE=curve([[0,-5.5],[0,-2.2],[0,1],[0,4.2],[0,7.2]])
const RING=curve([[0,-5.5],[-4.6,-5.0],[-8,-2.9],[-9,1.1],[-7.6,5.0],[-4.0,7.3],[0,8.0],[4.3,7.2],[8,5],[9.4,1.3],[8.7,-2.7],[5.2,-5],[0,-5.5]],true)
const EAST=curve([[5.2,-5],[7.5,-5.8],[10,-4.8],[10.8,-1.2],[10.4,3.4],[8,5]])
const WEST=curve([[-4.6,-5],[-7.6,-5.8],[-10,-3.7],[-10.5,.4],[-9,3.5],[-7.6,5]])
const NORTH=curve([[-4,7.3],[-2,9.2],[2.2,9.4],[4.3,7.2]])
const HQ_WALK=curve([[-3.4,-1.7],[-4.1,1],[-3.1,3.4],[0,4.1],[3.1,3.4],[4,1],[3.1,-1.8],[0,-2.7],[-3.4,-1.7]],true)
export const BASE_WALK_ROUTES=[HQ_WALK,curve([[-7.8,4.4],[-6,3.7],[-4.6,2.7],[-3.5,1.6]]),curve([[3.6,-1],[5.4,-2.4],[7.2,-3.7],[8.8,-4.2]]),curve([[-3.4,7],[-1,7.3],[1.6,7.1],[4.1,6.6]]),curve([[-8.4,-2],[-6.6,-1.3],[-4.9,-.5],[-3.5,.2]]),curve([[4.4,3],[5.7,4],[7.1,4.8],[8.1,5.2]])]
function buildGround(root,bank){const base=box(24.5,.14,22.5,mat(0x496357,1));base.position.set(0,-.18,-.2);base.castShadow=false;root.add(base);const grass=box(22.7,.05,20.6,mat(0x789487,1));grass.position.set(0,-.08,.1);grass.castShadow=false;root.add(grass);const admin=box(8.2,.035,8.0,mat(0x879d92,1));admin.position.set(-6.4,-.045,2.3);admin.rotation.y=.03;admin.castShadow=false;root.add(admin);const ops=box(8.6,.035,9.2,mat(0x71897d,1));ops.position.set(7.1,-.045,.3);ops.rotation.y=-.03;ops.castShadow=false;root.add(ops);const centre=new THREE.Mesh(new THREE.CircleGeometry(4.35,56),mat(0xaebbb2,.98));centre.rotation.x=-Math.PI/2;centre.position.y=.006;centre.receiveShadow=true;root.add(centre);const pond=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.15,.08,30),new THREE.MeshStandardMaterial({color:0x58a5a8,roughness:.32,transparent:true,opacity:.92}));pond.position.set(-1.7,.04,-1.5);root.add(pond);for(const [x,z,r] of[[-3.3,-1.5,0],[-2.8,-.4,.3],[2.8,2.9,-.6],[3.2,1.7,-.2]])bench(root,x,z,r);for(const [x,z] of[[-.7,-3.1],[.7,-3.1],[-.7,4.6],[.7,4.6]])bollard(root,x,z);for(let i=0;i<38;i++){const a=i*2.399,r=9.5+(i%5)*.5,x=Math.cos(a)*r,z=Math.sin(a)*r*.88;if(z<-8.5&&Math.abs(x)<2.2)continue;tree(root,bank,x,z,1.22+(i%4)*.14,i)}}
function buildRoads(root,bank){for(const c of[RING,ENTRY,SPINE,EAST,WEST,NORTH])sidewalk(root,c,c===SPINE?1.86:1.66);roadAsset(root,bank,'roadRoundabout',0,-5.5,0,3.55,.03);roadAsset(root,bank,'roadRoundabout',0,4.2,0,3.15,.03);roadAsset(root,bank,'roadIntersectionPath',0,1.0,0,2.55,.03);roadAsset(root,bank,'roadSplit',5.2,-5,-.78,2.5,.03);roadAsset(root,bank,'roadDrivewayDouble',8.8,-4.4,-1.05,2.2,.03);roadAsset(root,bank,'roadDrivewaySingle',-8.5,-4.6,.8,2.05,.03);roadAsset(root,bank,'roadCrossing',0,-1.9,Math.PI/2,2.2,.03);roadAsset(root,bank,'roadSideEntry',9.4,1.2,-Math.PI/2,2.1,.03);roadAsset(root,bank,'roadSideExit',-9,1.2,Math.PI/2,2.1,.03);roadAsset(root,bank,'highwaySign',0,-11.3,Math.PI,2.1,.03);for(const [x,z,r] of[[-7.8,4.2,.8],[-5.4,6.4,2.1],[-1.8,7.7,-2.8],[4.6,6.6,-2.3],[8.3,3,-1.4],[7.2,-4.2,-.5],[-5.5,-4.5,.5],[0,-9.8,0]])roadLight(root,bank,x,z,r);if(bank?.models?.roadTrafficLight)for(const [x,z,r] of[[-1.0,.6,0],[1.0,.7,Math.PI],[-.45,1.8,Math.PI/2]]){const v=fit(bank.clone('roadTrafficLight'),{w:.22,h:1.18,d:.22});v.position.set(x,.02,z);v.rotation.y=r;root.add(v)}}
function buildBuildings(root,bank,state){for(const id of Object.keys(BUILDINGS)){const spec=BASE_LAYOUT[id];if(!spec)continue;const lvl=state.buildings[id]??0,active=state.construction?.id===id;let v=null;if(lvl>0||id==='furnace')v=buildingView(bank,id,Math.max(1,lvl));else if(unlocked(state,id))v=plot(id,active);if(v){v.position.set(spec.p[0],.08,spec.p[1]);v.rotation.y=spec.r;root.add(v)}}}
function buildParking(root,bank){parking(root,bank,-5.0,6.2,.1,4,false,true);parking(root,bank,5.7,5.7,-.2,4,false,true);parking(root,bank,6.4,-3.5,-.25,4,true,false);parking(root,bank,-6.4,-3.8,.28,3,false,true);parking(root,bank,9.3,2.0,-1.15,3,true,false)}
function buildServiceYard(root,bank){for(let i=0;i<5;i++)roadAsset(root,bank,'roadFence',10.7,-5.0+i*1.25,Math.PI/2,1.0,.02);for(const [x,z] of[[8.9,-6.1],[9.4,-5.7],[9.9,-5.4]])roadAsset(root,bank,'roadCone',x,z,0,.6,.02);roadAsset(root,bank,'roadBarrier',10.5,-4.7,0,.9,.02)}
function buildTraffic(root,bank){const defs=[{curve:RING,key:'carSedan',offset:.05,speed:.0000072},{curve:RING,key:'carSuv',offset:.35,speed:.0000068},{curve:RING,key:'carDelivery',offset:.66,speed:.0000062},{curve:ENTRY,key:'carVan',offset:.15,speed:.000008,pingpong:true},{curve:EAST,key:'carTruck',offset:.35,speed:.000006,pingpong:true},{curve:WEST,key:'carSedan',offset:.65,speed:.000007,pingpong:true}];return defs.map(d=>{const v=vehicle(root,bank,d.key,d.key==='carTruck'?1.18:1.05);v.position.y=.09;return{view:v,...d}})}
export function buildBaseV12(bank,state){const root=new THREE.Group();root.name='achu-base-v12-campus';buildGround(root,bank);buildRoads(root,bank);buildBuildings(root,bank,state);buildParking(root,bank);buildServiceYard(root,bank);root.userData.traffic=buildTraffic(root,bank);return root}
export function baseBuildingPositionV12(id){const p=BASE_LAYOUT[id]?.p??[0,0];return new THREE.Vector3(p[0],0,p[1])}
export function animateBaseTrafficV12(traffic,now){for(const t of traffic??[]){let u=(t.offset+now*t.speed)%1,dir=1;if(t.pingpong){const raw=(t.offset+now*t.speed)%2;u=raw<=1?raw:2-raw;dir=raw<=1?1:-1}const p=t.curve.getPointAt(u),tan=t.curve.getTangentAt(u).normalize().multiplyScalar(dir);t.view.position.set(p.x,.09,p.z);t.view.rotation.y=Math.atan2(tan.x,tan.z)}}
