import * as THREE from 'three'
import { BUILDINGS } from '../data/buildings.js'

const ACCENT={furnace:0x50d4a1,shelter:0x67b9e8,sawmill:0xe9aa54,huntersHut:0xe88170,coalMine:0xe6c159,storehouse:0x76aee3,infantryCamp:0x62d99b,infirmary:0x61cfc6,ironMine:0xb991e5,lancerCamp:0x5fa8e0,embassy:0xe9c06a,marksmanCamp:0xe486ad,researchCenter:0x69d5df}
const ASSET={furnace:'achuHq',shelter:'achuClient',sawmill:'achuDepot',huntersHut:'cityA',coalMine:'achuStudio',storehouse:'achuWarehouse',infantryCamp:'cityL',infirmary:'cityC',ironMine:'cityN',lancerCamp:'achuDepot',embassy:'cityE',marksmanCamp:'cityG',researchCenter:'cityS'}
const BASE_LAYOUT={furnace:{p:[0,1.6],r:0},coalMine:{p:[-5.7,1.2],r:.28},huntersHut:{p:[-5.5,-2.4],r:.18},embassy:{p:[-6.0,4.8],r:.34},researchCenter:{p:[-2.8,6.1],r:.05},shelter:{p:[4.6,1.5],r:-.3},infirmary:{p:[5.4,4.8],r:-.34},ironMine:{p:[2.1,6.8],r:-.05},infantryCamp:{p:[-.7,7.8],r:.02},marksmanCamp:{p:[-5.8,7.7],r:.22},sawmill:{p:[6.1,-2.0],r:-.25},storehouse:{p:[6.2,-5.4],r:-.08},lancerCamp:{p:[2.2,-5.5],r:.08}}
const mat=(color,rough=.84,metal=.025)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})
const box=(w,h,d,m)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.castShadow=true;o.receiveShadow=true;return o}
const curve=(pts,closed=false)=>new THREE.CatmullRomCurve3(pts.map(([x,z])=>new THREE.Vector3(x,0,z)),closed,'centripetal',.18)
function ribbonGeometry(c,width,y=.012,segments=110){const verts=[],idx=[];for(let i=0;i<=segments;i++){const u=i/segments,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),nx=-t.z,nz=t.x;verts.push(p.x+nx*width/2,y,p.z+nz*width/2,p.x-nx*width/2,y,p.z-nz*width/2)}for(let i=0;i<segments;i++){const q=i*2;idx.push(q,q+1,q+2,q+1,q+3,q+2)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g}
function ribbon(parent,c,width,color,y=.012){const o=new THREE.Mesh(ribbonGeometry(c,width,y),mat(color,.97));o.receiveShadow=true;o.castShadow=false;parent.add(o);return o}
function road(parent,c,width=1.55){ribbon(parent,c,width+.68,0x99a69f,-.003);ribbon(parent,c,width,0x303b3a,.018);const lane=mat(0xe5e6dd,.72);for(let i=1;i<48;i+=2){const u=i/48,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),d=box(.05,.012,.42,lane);d.position.set(p.x,.055,p.z);d.rotation.y=Math.atan2(t.x,t.z);d.castShadow=false;parent.add(d)}}
function footpath(parent,c,width=.42){ribbon(parent,c,width,0xc7d0c7,.03)}
function fit(view,{w=2,h=2,d=2}){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=Math.min(w/Math.max(.001,s.x),h/Math.max(.001,s.y),d/Math.max(.001,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function fitRoad(view,size=2.3){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=size/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function roadAsset(parent,bank,key,x,z,rot=0,size=2.3,y=.026){const v=fitRoad(bank?.clone?.(key)??new THREE.Group(),size);v.position.set(x,y,z);v.rotation.y=rot;parent.add(v);return v}
function tree(parent,bank,x,z,h=1.35,i=0){const v=bank?.cloneTree?.(i,h);if(!v)return;v.position.set(x,0,z);v.rotation.y=(i*.79)%6.283;parent.add(v)}
function ring(parent,r,color,opacity=.34){const o=new THREE.Mesh(new THREE.RingGeometry(r*.84,r,34),new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}));o.rotation.x=-Math.PI/2;o.position.y=.08;parent.add(o)}
function tag(root,id){root.userData.buildingId=id;root.traverse(o=>o.userData.buildingId=id);return root}
function unlocked(state,id){return id==='furnace'||(state.buildings.furnace??1)>=(BUILDINGS[id]?.unlockFurnace??1)}
function labelSprite(text,color){const c=document.createElement('canvas');c.width=520;c.height=96;const x=c.getContext('2d');x.fillStyle='rgba(8,23,20,.9)';x.roundRect(7,10,506,76,18);x.fill();x.strokeStyle=`#${color.toString(16).padStart(6,'0')}`;x.lineWidth=3;x.stroke();x.fillStyle='#eef2eb';x.font='800 22px Inter,Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text.toUpperCase(),260,48,455);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(2.55,.47,1);return s}
function buildingView(bank,id,lvl){const g=new THREE.Group(),key=ASSET[id]??'achuOffice',hq=id==='furnace',industrial=['sawmill','storehouse','lancerCamp'].includes(id),growth=1+Math.min(12,Math.max(1,lvl))*.01;const target=hq?{w:2.9*growth,h:2.8*growth,d:2.55*growth}:industrial?{w:2.25*growth,h:1.75*growth,d:2.05*growth}:{w:1.92*growth,h:1.95*growth,d:1.7*growth};const pad=box(target.w+.42,.055,target.d+.38,mat(hq?0x587465:industrial?0x4c6157:0x657d70,.98));pad.position.y=.02;pad.castShadow=false;g.add(pad);const model=fit(bank?.clone?.(key)??new THREE.Group(),target);model.position.y=.07;g.add(model);const l=labelSprite(hq?'ACHU HQ':BUILDINGS[id]?.name??id,ACCENT[id]??0x50d4a1);l.position.set(0,target.h+.32,0);l.scale.multiplyScalar(hq?.76:.62);g.add(l);ring(g,hq?1.18:.82,ACCENT[id]??0x50d4a1,hq?.5:.18);return tag(g,id)}
function plot(id,active=false){const g=new THREE.Group(),c=ACCENT[id]??0x50d4a1,pad=box(2.0,.05,1.55,mat(active?0x786445:0x4f6258,.98));pad.position.y=.02;g.add(pad);ring(g,.72,c,.34);const l=labelSprite(active?'DEVELOPING':BUILDINGS[id]?.name??id,c);l.position.set(0,.78,0);l.scale.multiplyScalar(.55);g.add(l);return tag(g,id)}
function fitVehicle(view,target=.95){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),longX=s.x>s.z*1.08,sc=target/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);if(longX)view.rotation.y=-Math.PI/2;view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;view.userData.forwardOffset=0;return view}
function vehicle(parent,bank,key='carSedan',target=.95){const v=fitVehicle(bank?.clone?.(key)??new THREE.Group(),target);parent.add(v);return v}
function userCar(parent,bank,index=0,target=.86){const v=fitVehicle(bank?.cloneCar?.(index)??bank?.clone?.('carSedan')??new THREE.Group(),target);parent.add(v);return v}
function parking(parent,bank,x,z,rot=0,count=4,type='user'){const g=new THREE.Group();g.position.set(x,.025,z);g.rotation.y=rot;const pad=box(3.5,.035,2.05,mat(0x343f3e,.99));pad.castShadow=false;g.add(pad);for(let i=-2;i<=2;i++){const line=box(.035,.012,1.72,mat(0xe7e8df,.78));line.position.set(i*.64,.03,0);line.castShadow=false;g.add(line)}for(let i=0;i<count;i++){const v=type==='logistics'?vehicle(g,bank,['carVan','carDelivery','carTruck'][i%3],.74+(i%2)*.04):userCar(g,bank,i,.73+(i%2)*.04);v.position.set(-.96+i*.64,.05,(i%2)*.08-.04);v.rotation.y=0}parent.add(g)}
function roadLight(parent,bank,x,z,rot=0){if(!bank?.models?.roadLightCurved)return;const v=fit(bank.clone('roadLightCurved'),{w:.2,h:1.38,d:.2});v.position.set(x,.02,z);v.rotation.y=rot;parent.add(v)}
function bench(parent,x,z,r=0){const g=new THREE.Group(),wood=mat(0x6c5947,.9),metal=mat(0x303937,.82,.14);const seat=box(.92,.1,.3,wood);seat.position.y=.34;g.add(seat);for(const xx of[-.34,.34]){const leg=box(.07,.32,.07,metal);leg.position.set(xx,.17,0);g.add(leg)}g.position.set(x,0,z);g.rotation.y=r;parent.add(g)}
const ENTRY=curve([[0,-10.2],[0,-7.8],[0,-5.3],[0,-2.7]])
const RING=curve([[0,-2.7],[-3.9,-2.4],[-6.0,-.2],[-6.0,3.4],[-3.8,5.6],[0,6.2],[3.8,5.5],[6.0,3.3],[6.0,-.2],[3.8,-2.4],[0,-2.7]],true)
const EAST=curve([[3.8,-2.4],[5.3,-3.7],[6.7,-5.0],[6.5,-6.6]])
const WEST=curve([[-3.9,-2.4],[-5.2,-3.5],[-6.6,-4.6],[-6.7,-6.0]])
const NORTH=curve([[-3.8,5.6],[-2.2,7.0],[0,7.5],[2.4,7.0],[3.8,5.5]])
const HQ_WALK=curve([[-2.8,-.1],[-3.2,1.6],[-2.6,3.2],[0,4.1],[2.7,3.2],[3.2,1.6],[2.7,-.1],[0,-.8],[-2.8,-.1]],true)
const ADMIN_WALK=curve([[-6.9,-3.5],[-6.8,-.5],[-6.3,2.8],[-5.8,5.7],[-3.3,6.2]])
const OPS_WALK=curve([[3.4,-1.0],[5.2,-1.0],[6.5,-2.8],[6.7,-5.4],[4.8,-6.2]])
export const BASE_WALK_ROUTES=[HQ_WALK,ADMIN_WALK,OPS_WALK,NORTH,curve([[-2.5,5.8],[-1.3,6.7],[0,7.2],[1.6,6.8]]),curve([[3.1,3.5],[4.2,4.5],[5.4,4.9],[6.0,4.5]])]
function buildGround(root,bank){const base=box(18.4,.16,17.4,mat(0x466156,1));base.position.set(0,-.2,-.3);base.castShadow=false;root.add(base);const grass=box(17.5,.05,16.5,mat(0x769184,1));grass.position.set(0,-.09,-.1);grass.castShadow=false;root.add(grass);for(const [x,z,w,d,c] of[[-5.2,2.0,5.7,8.6,0x82978d],[5.1,.3,5.9,10.4,0x70877c],[0,6.9,6.6,3.8,0x879b91]]){const p=box(w,.028,d,mat(c,.99));p.position.set(x,-.045,z);p.castShadow=false;root.add(p)}const plaza=new THREE.Mesh(new THREE.CircleGeometry(3.25,52),mat(0xaebbb2,.98));plaza.rotation.x=-Math.PI/2;plaza.position.set(0,.006,1.3);plaza.receiveShadow=true;root.add(plaza);const water=new THREE.Mesh(new THREE.CylinderGeometry(.72,.8,.07,28),new THREE.MeshStandardMaterial({color:0x59a0a3,roughness:.32,transparent:true,opacity:.94}));water.position.set(-1.6,.04,-.55);root.add(water);bench(root,-2.5,-.45,.18);bench(root,2.25,3.15,-.4);bench(root,-.2,4.5,0);for(let i=0;i<30;i++){const a=i*2.399,r=7.0+(i%4)*.36,x=Math.cos(a)*r,z=Math.sin(a)*r*.92;if(z<-7&&Math.abs(x)<2.0)continue;tree(root,bank,x,z,1.15+(i%4)*.12,i)}}
function buildRoads(root,bank){road(root,ENTRY,1.72);road(root,RING,1.58);road(root,EAST,1.48);road(root,WEST,1.42);road(root,NORTH,1.38);roadAsset(root,bank,'roadRoundabout',0,-2.7,0,3.25,.03);roadAsset(root,bank,'roadCrossing',0,.1,Math.PI/2,2.0,.03);roadAsset(root,bank,'roadDrivewayDouble',5.45,-3.7,-.45,1.9,.03);roadAsset(root,bank,'roadDrivewaySingle',-5.35,-3.4,.48,1.85,.03);roadAsset(root,bank,'roadSplit',0,-5.3,0,2.15,.03);roadAsset(root,bank,'roadSignStreet',.6,-6.1,Math.PI,.72,.03);roadAsset(root,bank,'roadSignStop',-3.8,-2.8,.25,.62,.03);for(const [x,z,r] of[[-5.9,1,.1],[-5.5,4.2,.2],[5.9,1.0,Math.PI],[5.7,4.2,Math.PI],[0,5.7,Math.PI/2],[0,-7.5,-Math.PI/2]])roadLight(root,bank,x,z,r);roadAsset(root,bank,'roadBarrier',7.0,-6.4,0,.8,.03);roadAsset(root,bank,'roadCone',6.5,-6.3,0,.48,.03);roadAsset(root,bank,'roadFence',7.45,-6.25,Math.PI/2,1.0,.03)}
function buildFootpaths(root){footpath(root,HQ_WALK,.38);footpath(root,ADMIN_WALK,.34);footpath(root,OPS_WALK,.34);footpath(root,NORTH,.34)}
function buildBuildings(root,bank,state){for(const id of Object.keys(BUILDINGS)){const spec=BASE_LAYOUT[id];if(!spec)continue;const lvl=state.buildings[id]??0,active=state.construction?.id===id;let v=null;if(lvl>0||id==='furnace')v=buildingView(bank,id,Math.max(1,lvl));else if(unlocked(state,id))v=plot(id,active);if(v){v.position.set(spec.p[0],.08,spec.p[1]);v.rotation.y=spec.r;root.add(v)}}}
function buildParking(root,bank){parking(root,bank,-6.1,-5.4,.1,4,'user');parking(root,bank,5.5,-4.8,-.12,4,'logistics');parking(root,bank,0,8.1,0,4,'user')}
function buildTraffic(root,bank){const routes=[RING,RING,ENTRY,EAST,WEST],traffic=[];for(let i=0;i<7;i++){const v=vehicle(root,bank,['carSedan','carSuv','carVan','carDelivery','carSedan','carSuv','carVan'][i%7],.82+(i%2)*.04);traffic.push({view:v,curve:routes[i%routes.length],offset:(i*.151)%1,speed:.0000063+(i%3)*.0000007,pingpong:i>=2});v.position.y=.09}return traffic}
export function buildBaseV13(bank,state){const root=new THREE.Group();root.name='achu-base-v13-campus';buildGround(root,bank);buildRoads(root,bank);buildFootpaths(root);buildBuildings(root,bank,state);buildParking(root,bank);root.userData.traffic=buildTraffic(root,bank);return root}
export function baseBuildingPositionV13(id){const p=BASE_LAYOUT[id]?.p??[0,0];return new THREE.Vector3(p[0],0,p[1])}
export function animateBaseTrafficV13(traffic,now){for(const t of traffic??[]){let u=(t.offset+now*t.speed)%1,dir=1;if(t.pingpong){const raw=(t.offset+now*t.speed)%2;u=raw<=1?raw:2-raw;dir=raw<=1?1:-1}const p=t.curve.getPointAt(u),tan=t.curve.getTangentAt(u).normalize().multiplyScalar(dir);t.view.position.set(p.x,.09,p.z);t.view.rotation.y=Math.atan2(tan.x,tan.z)+(t.view.userData.forwardOffset??0)}}
