import * as THREE from 'three'
import { BUILDINGS } from '../data/buildings.js'

const LAYOUT={furnace:[0,-1],shelter:[-6.8,3.6],sawmill:[7.5,5.2],huntersHut:[5.8,-6.4],coalMine:[-7.4,-5.8],ironMine:[10.5,-1.2],storehouse:[11.5,6.7],infirmary:[-11,1],embassy:[-2.7,8.6],infantryCamp:[2.8,-9.4],lancerCamp:[9.6,-8.5],marksmanCamp:[-9.8,-9],researchCenter:[4.4,8.9]}
const ACCENT={furnace:0x55e0b5,shelter:0x76d6ff,sawmill:0xffb95a,huntersHut:0xff8e78,coalMine:0xffcf62,storehouse:0x8bc6ff,infantryCamp:0x6ee5a3,infirmary:0x69d9d0,ironMine:0xd3a0ff,lancerCamp:0x66bfff,embassy:0xffd37a,marksmanCamp:0xff8fb4,researchCenter:0x7eeeff}
const PREMIUM={furnace:'downtownLarge',shelter:'downtownSmall',huntersHut:'downtownMedium',coalMine:'downtownSmall',embassy:'downtownSmall',researchCenter:'downtownMedium'}
const INDUSTRIAL=new Set(['sawmill','storehouse','lancerCamp'])
const mat=(color,rough=.9)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.03})
function clone(bank,name,x=0,y=0,z=0,rot=0,s=1,parent=null){const o=bank.clone(name);o.position.set(x,y,z);o.rotation.y=rot;o.scale.setScalar(s);if(parent)parent.add(o);return o}
function tag(root,id){root.userData.buildingId=id;root.traverse(o=>o.userData.buildingId=id);return root}
function disk(parent,r,color,y=.01,opacity=1){const m=new THREE.Mesh(new THREE.CircleGeometry(r,40),new THREE.MeshStandardMaterial({color,roughness:1,transparent:opacity<1,opacity}));m.rotation.x=-Math.PI/2;m.position.y=y;m.receiveShadow=true;parent.add(m);return m}
function ring(parent,r,color){const m=new THREE.Mesh(new THREE.RingGeometry(r*.84,r,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.42,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.y=.03;parent.add(m)}

function signSprite(text,color=0xffffff){const c=document.createElement('canvas');c.width=640;c.height=128;const x=c.getContext('2d');x.fillStyle='rgba(15,34,29,.86)';x.roundRect(12,17,616,94,22);x.fill();x.strokeStyle=`#${color.toString(16).padStart(6,'0')}`;x.lineWidth=3;x.stroke();x.fillStyle='#fff';x.font='900 30px Inter,Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text.toUpperCase(),320,64,570);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(4.7,.95,1);return s}
function pulse(color){const c=document.createElement('canvas');c.width=c.height=96;const x=c.getContext('2d'),g=x.createRadialGradient(48,48,5,48,48,44),h=`#${color.toString(16).padStart(6,'0')}`;g.addColorStop(0,'white');g.addColorStop(.2,h);g.addColorStop(1,'transparent');x.fillStyle=g;x.fillRect(0,0,96,96);const t=new THREE.CanvasTexture(c),s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending})),p=Math.random()*6;s.onBeforeRender=()=>s.scale.setScalar(.82+Math.sin(performance.now()*.003+p)*.12);return s}

function modularOffice(bank,id,level){const g=new THREE.Group(),b=id.charCodeAt(0)%2?'B':'A',door=`wall${b}Door`,win=`wall${b}Window`,roof=`wall${b}Roof`,floors=1+Math.min(2,Math.floor((level-1)/4));for(let f=0;f<floors;f++){for(const x of[-.5,.5]){clone(bank,f===0&&x===-.5?door:win,x,f,.5,0,.85,g);clone(bank,win,x,f,-.5,Math.PI,.85,g)}clone(bank,win,-1,f,0,Math.PI/2,.85,g);clone(bank,win,1,f,0,-Math.PI/2,.85,g)}for(const x of[-.5,.5])for(const z of[-.5,.5])clone(bank,roof,x,floors,z,0,.85,g);ring(g,1.75,ACCENT[id]);const s=signSprite(BUILDINGS[id]?.name??id,ACCENT[id]);s.position.set(0,floors+1.05,0);g.add(s);const p=pulse(ACCENT[id]);p.position.set(1.25,floors+.55,.1);g.add(p);return tag(g,id)}
function premiumOffice(bank,id,level){const g=new THREE.Group(),model=clone(bank,PREMIUM[id],0,0,0,(id.charCodeAt(0)%4)*Math.PI/2,.28+Math.min(12,level)*.008,g);model.traverse(o=>{if(o.isMesh)o.castShadow=id==='furnace'});if(id==='furnace')clone(bank,'downtownAC',-.55,.02,.8,0,.38,g);ring(g,id==='furnace'?2.55:1.95,ACCENT[id]);const s=signSprite(id==='furnace'?'ACHU HQ':BUILDINGS[id]?.name??id,ACCENT[id]);s.position.set(0,id==='furnace'?4.9:3.5,0);g.add(s);const p=pulse(ACCENT[id]);p.position.set(1.35,id==='furnace'?4.2:2.9,.15);g.add(p);return tag(g,id)}
function industrial(bank,id,level){const g=new THREE.Group(),w=id==='storehouse'?4:3;disk(g,w*.74,0xa6a59b);for(let x=0;x<w;x++){const px=x-(w-1)/2;clone(bank,x===Math.floor(w/2)?'garage':'wallBWindow',px,0,1,0,1,g);clone(bank,'wallB',px,0,-1,Math.PI,1,g);for(const z of[-.5,.5])clone(bank,'metalRoof',px,1,z,0,1,g)}clone(bank,'wallB',-w/2,0,0,Math.PI/2,1,g);clone(bank,'wallB',w/2,0,0,-Math.PI/2,1,g);ring(g,w*.7,ACCENT[id]);const s=signSprite(BUILDINGS[id]?.name??id,ACCENT[id]);s.position.set(0,2.05,0);g.add(s);if(id==='lancerCamp'){clone(bank,'truckGreen',-1.2,.03,2,Math.PI,.62,g);clone(bank,'truckGrey',1.2,.03,2,Math.PI,.62,g)}else clone(bank,id==='sawmill'?'truckGreen':'truckGrey',0,.03,2,Math.PI,.6,g);return tag(g,id)}
function construction(bank,id,active){const g=new THREE.Group();disk(g,1.9,active?0xb8a173:0xaab0a5);ring(g,1.8,ACCENT[id]??0x55e0b5);if(active)clone(bank,'scaffold',0,.02,0,0,.8,g);const s=signSprite(active?'COMING TO LIFE':BUILDINGS[id]?.name??id,ACCENT[id]??0x55e0b5);s.position.set(0,active?2.1:1.3,0);g.add(s);return tag(g,id)}

function ribbon(parent,pts,width,color){const curve=new THREE.CatmullRomCurve3(pts.map(([x,z])=>new THREE.Vector3(x,.02,z))),seg=48,v=[],idx=[];for(let i=0;i<=seg;i++){const t=i/seg,p=curve.getPoint(t),tan=curve.getTangent(t),n=new THREE.Vector3(-tan.z,0,tan.x).normalize().multiplyScalar(width/2);v.push(p.x+n.x,p.y,p.z+n.z,p.x-n.x,p.y,p.z-n.z);if(i<seg){const a=i*2;idx.push(a,a+1,a+2,a+1,a+3,a+2)}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(v,3));geo.setIndex(idx);geo.computeVertexNormals();const m=new THREE.Mesh(geo,mat(color,.98));m.receiveShadow=true;parent.add(m)}
function roads(root){ribbon(root,[[-20,2],[-10,1],[-3,-1],[5,0],[20,-2]],2.5,0x3d4444);ribbon(root,[[-11,-18],[-8,-9],[-4,-2],[-2,7],[0,18]],2.3,0x3d4444);ribbon(root,[[1,-18],[3,-10],[6,-3],[9,5],[14,17]],2.1,0x3d4444);ribbon(root,[[-18,10],[-9,8],[0,9],[9,10],[18,7]],2.05,0x3d4444)}
function plaza(bank,root){disk(root,5.1,0xc6c0ad);const pool=new THREE.Mesh(new THREE.CylinderGeometry(1.8,1.95,.2,40),mat(0x87918d));pool.position.y=.08;root.add(pool);const water=disk(root,1.62,0x76bfd0,.2);water.material.roughness=.22;for(let i=0;i<6;i++){const a=i*Math.PI/3;clone(bank,i%2?'downtownTreeA':'downtownTreeB',Math.cos(a)*3.8,0,Math.sin(a)*3.8,a,.34,root)}}
function backdrop(bank,root){const spots=[[-18,-12,'downtownMedium',.4],[-15,15,'downtownSmall',.42],[16,13,'downtownMedium',.38],[18,-11,'downtownSmall',.43]];spots.forEach(([x,z,n,s],i)=>{const b=clone(bank,n,x,0,z,i*Math.PI/2,s,root);b.traverse(o=>{if(o.isMesh){o.castShadow=false;const ms=Array.isArray(o.material)?o.material:[o.material];for(const m of ms)if(m){m.transparent=true;m.opacity=.8}}})});for(let i=0;i<24;i++){const a=i*2.399,r=15+(i%4)*1.4;clone(bank,i%4===0?'downtownTreeA':'pineSmall',Math.cos(a)*r,0,Math.sin(a)*r,a,i%4===0?.28:.42,root)}}
function streetLife(bank,root){for(const [x,z,r,n] of[[-8,1,0,'truckGreen'],[-2,-1,Math.PI,'truckGrey'],[6,1,0,'truckGreen'],[-7,7.4,Math.PI/2,'truckGrey'],[8.5,9.2,-Math.PI/2,'truckGreen']])clone(bank,n,x,.05,z,r,.46,root)}
function unlocked(state,id){return id==='furnace'||(state.buildings.furnace??1)>=(BUILDINGS[id]?.unlockFurnace??1)}

export function buildCity(bank,state){const root=new THREE.Group();root.name='livingBusinessDistrict';const ground=new THREE.Mesh(new THREE.CircleGeometry(28,72),mat(0x87a38c,1));ground.rotation.x=-Math.PI/2;ground.position.y=-.08;ground.receiveShadow=true;root.add(ground);const pad=new THREE.Mesh(new THREE.CircleGeometry(22.5,72),mat(0xb6b5a6,1));pad.rotation.x=-Math.PI/2;pad.position.y=-.055;pad.receiveShadow=true;root.add(pad);roads(root);plaza(bank,root);backdrop(bank,root);streetLife(bank,root);for(const id of Object.keys(BUILDINGS)){const lvl=state.buildings[id]??0,[x,z]=LAYOUT[id]??[0,0],active=state.construction?.id===id;let b=null;if(lvl>0||id==='furnace')b=INDUSTRIAL.has(id)?industrial(bank,id,Math.max(1,lvl)):PREMIUM[id]?premiumOffice(bank,id,Math.max(1,lvl)):modularOffice(bank,id,Math.max(1,lvl));else if(unlocked(state,id))b=construction(bank,id,active);if(b){b.position.set(x,0,z);root.add(b)}}return root}
export function buildingPosition(id){const [x,z]=LAYOUT[id]??[0,0];return new THREE.Vector3(x,0,z)}
