import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
import { AssetBank } from './AssetBank.js'
import { buildCity,buildingPosition } from './cityFactory.js'
import { World3D } from './worldFactory.js'
import { GameUI } from './ui.js'
import { loadState,saveState } from '../systems/state.js'
import { startConstruction,tickConstruction,allianceHelp as applyAllianceHelp } from '../systems/construction.js'
import { startResearch,tickResearch,researchBonus } from '../systems/research.js'
import { BUILDINGS,resourceProduction } from '../data/buildings.js'
import { worldTile,parseTile,adjacentTo,BASE_TILE } from '../data/world.js'
import { currentChapter } from '../data/chapters.js'
import { heroPower } from '../data/heroes.js'
import { tickEvents } from '../systems/events.js'
import { recordBattleWin,recordBattleLoss,checkAchievements } from '../systems/prestige.js'
import { createGuild } from '../systems/guilds.js'
import { recruitHero } from '../systems/heroes.js'

const has=(r,c)=>Object.entries(c).every(([k,v])=>(r[k]??0)>=v)
const spend=(r,c)=>Object.entries(c).forEach(([k,v])=>r[k]-=v)
const TROOP_POWER={infantry:7,lancer:8,marksman:9}
const CAMP_BY_TROOP={infantry:'infantryCamp',lancer:'lancerCamp',marksman:'marksmanCamp'}

export class Retro4XGame{
 constructor(mount){this.mount=mount;this.state=loadState();this.mode='city';this.last=performance.now();this.lastSave=0;this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.down=null}
 async start(){
  this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.renderer.domElement.className='three-canvas';this.mount.appendChild(this.renderer.domElement)
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x23353b);this.scene.fog=new THREE.FogExp2(0x25383e,.018)
  this.camera=new THREE.OrthographicCamera(-12,12,12,-12,.1,160);this.camera.position.set(18,22,18);this.camera.lookAt(0,0,0)
  this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableRotate=false;this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.screenSpacePanning=false;this.controls.minZoom=.55;this.controls.maxZoom=2.4;this.controls.target.set(0,0,0)
  this.scene.add(new THREE.HemisphereLight(0xc6e9ff,0x334138,2.15));const sun=new THREE.DirectionalLight(0xfff1d9,3.4);sun.position.set(-14,24,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-30;sun.shadow.camera.right=30;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;this.scene.add(sun)
  this.assets=await new AssetBank().load();this.city=buildCity(this.assets,this.state);this.world=new World3D(this.assets,this.state);this.world.visible=false;this.scene.add(this.city,this.world);this.addWorkers();this.ui=new GameUI(this);this.bind();this.resize();this.applyOfflineProduction();saveState(this.state);this.loop()
 }
 addWorkers(){if(!this.assets.character)return;this.workers=[];for(let i=0;i<5;i++){const c=this.assets.cloneCharacter();c.scale.setScalar(.008);c.position.set(-3+i*1.4,.02,2+(i%2)*1.7);c.rotation.y=i%2?Math.PI/2:-Math.PI/2;this.city.add(c);this.workers.push({view:c,phase:i*.9})}}
 bind(){window.addEventListener('resize',()=>this.resize());const el=this.renderer.domElement;el.addEventListener('pointerdown',e=>{this.down={x:e.clientX,y:e.clientY}});el.addEventListener('pointerup',e=>{if(!this.down)return;const moved=Math.hypot(e.clientX-this.down.x,e.clientY-this.down.y);this.down=null;if(moved<8)this.pick(e)});document.addEventListener('visibilitychange',()=>{if(document.hidden)saveState(this.state)})}
 resize(){const w=innerWidth,h=innerHeight,aspect=w/h,view=this.mode==='world'?17:13;this.camera.left=-view*aspect;this.camera.right=view*aspect;this.camera.top=view;this.camera.bottom=-view;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false)}
 setMode(mode){if(mode==='world'&&(this.state.buildings.furnace??1)<4){this.ui.toast('World unlocks at Furnace 4');return}this.mode=mode;this.city.visible=mode==='city';this.world.visible=mode==='world';this.controls.target.set(0,0,0);this.camera.position.set(mode==='world'?20:18,mode==='world'?26:22,mode==='world'?20:18);this.camera.zoom=1;this.camera.updateProjectionMatrix();this.resize();this.ui.hideSheet();this.ui.refresh()}
 pick(e){const r=this.renderer.domElement.getBoundingClientRect();this.pointer.x=((e.clientX-r.left)/r.width)*2-1;this.pointer.y=-((e.clientY-r.top)/r.height)*2+1;this.raycaster.setFromCamera(this.pointer,this.camera);const hits=this.raycaster.intersectObject(this.mode==='city'?this.city:this.world,true);for(const h of hits){let o=h.object,id=null;while(o&&!id){id=this.mode==='city'?o.userData.buildingId:o.userData.tileId;o=o.parent}if(id){this.mode==='city'?this.selectBuilding(id):this.selectWorldTile(id);return}}}
 selectBuilding(id){this.ui.openBuilding(id)}
 selectWorldTile(id){this.ui.openWorldTile(id)}
 focusBuilding(id){this.setMode('city');const p=buildingPosition(id);this.controls.target.copy(p);this.camera.position.set(p.x+12,16,p.z+12);this.ui.toast(`${BUILDINGS[id].name} located`)}
 rebuildCity(){this.city.removeFromParent();this.city=buildCity(this.assets,this.state);this.scene.add(this.city);this.addWorkers()}
 upgradeBuilding(id){const r=startConstruction(this.state,id);this.ui.toast(r.ok?`${BUILDINGS[id].name} construction started`:r.error);if(r.ok)saveState(this.state);this.ui.refresh()}
 research(id){const r=startResearch(this.state,id);this.ui.toast(r.ok?'Research started':r.error);if(r.ok)saveState(this.state);this.ui.refresh()}
 createGuild(name){const r=createGuild(this.state,name);this.ui.toast(r.ok?`Guild "${name}" created`:r.error);if(r.ok)saveState(this.state);this.ui.refresh()}
 recruitHero(id){const r=recruitHero(this.state,id);this.ui.toast(r.ok?`${r.hero.name} recruited`:r.error);if(r.ok)saveState(this.state);this.ui.refresh()}
 allianceHelp(){const ok=applyAllianceHelp(this.state);this.ui.toast(ok?'Alliance help applied':'No construction to help');if(ok)saveState(this.state);this.ui.refresh()}
 claimChapter(chapter=currentChapter(this.state)){if(!chapter||this.state.claimedChapters?.[chapter.id])return;for(const [k,v] of Object.entries(chapter.reward??{}))this.state.resources[k]=(this.state.resources[k]??0)+v;this.state.claimedChapters[chapter.id]=true;saveState(this.state);this.ui.toast('Chapter reward claimed');this.ui.refresh()}
 productionRates(){const base=resourceProduction(this.state),all=1+researchBonus(this.state,'allOutput');for(const k of Object.keys(base))base[k]*=all*(1+researchBonus(this.state,`${k}Output`));return base}
 applyOfflineProduction(){const seconds=Math.min(8*3600,Math.max(0,(Date.now()-(this.state.lastSavedAt??Date.now()))/1000));if(seconds<3)return;const rates=this.productionRates();for(const [k,v] of Object.entries(rates))this.state.resources[k]=(this.state.resources[k]??0)+v*seconds}
 armyPower(){const t=this.state.world.troops??{},troops=Object.entries(TROOP_POWER).reduce((a,[k,p])=>a+(t[k]??0)*p,0),camps=(this.state.buildings.infantryCamp??0)*45+(this.state.buildings.lancerCamp??0)*55+(this.state.buildings.marksmanCamp??0)*65;return Math.round((this.state.world.armyPower??0)+troops+camps+heroPower(this.state,this.state.world.selectedHero??'astrid'))}
 marchCapacity(){return 2+((this.state.buildings.embassy??0)>=8?1:0)}
 assignedTroops(){const out={infantry:0,lancer:0,marksman:0};for(const m of this.state.world.marches??[])for(const k of Object.keys(out))out[k]+=m.troops?.[k]??0;return out}
 freeTroops(){const used=this.assignedTroops(),all=this.state.world.troops??{};return Object.fromEntries(Object.keys(TROOP_POWER).map(k=>[k,Math.max(0,(all[k]??0)-used[k])]))}
 detachment(type){const f=this.freeTroops();if(type==='attack')return{infantry:Math.max(1,Math.floor(f.infantry*.7)),lancer:Math.floor(f.lancer*.7),marksman:Math.floor(f.marksman*.7)};return{infantry:Math.min(8,f.infantry),lancer:0,marksman:0}}
 detachmentPower(t){return Object.entries(TROOP_POWER).reduce((a,[k,p])=>a+(t[k]??0)*p,0)+Math.round(heroPower(this.state,this.state.world.selectedHero??'astrid'))}
 travelMs(id){const [x,y]=parseTile(id),[bx,by]=parseTile(BASE_TILE);return 1800+(Math.abs(x-bx)+Math.abs(y-by))*650}
 dispatch(type,id,cost={}){const w=this.state.world;if(w.marches.length>=this.marchCapacity()){this.ui.toast('All march queues are busy');return false}if(w.marches.some(m=>m.target===id)){this.ui.toast('A march is already moving there');return false}if(!has(this.state.resources,cost)){this.ui.toast('Not enough resources');return false}const troops=this.detachment(type);if(Object.values(troops).reduce((a,b)=>a+b,0)<1){this.ui.toast('No free troops');return false}const d=worldTile(...parseTile(id));if(type==='attack'&&this.detachmentPower(troops)<d.strength){this.ui.toast(`Enemy power ${Math.floor(d.strength).toLocaleString()} is too high`);return false}spend(this.state.resources,cost);const now=Date.now(),travel=this.travelMs(id);w.marches.push({id:`m${now}${Math.floor(Math.random()*99)}`,type,target:id,phase:'outbound',phaseStartedAt:now,arriveAt:now+travel,travelMs:travel,troops,cargo:null});saveState(this.state);this.world.refreshMarches();this.ui.refresh();this.ui.toast(`${type.toUpperCase()} march dispatched`);return true}
 scoutTile(id){const w=this.state.world;if(w.scouted.includes(id)||!adjacentTo(id,w.scouted))return;this.dispatch('scout',id,{meat:25,wood:15})}
 claimTile(id){const w=this.state.world,d=worldTile(...parseTile(id));if(w.owned.includes(id)||!w.scouted.includes(id)||['camp','settlement'].includes(d.kind)||!adjacentTo(id,w.owned))return;this.dispatch('claim',id,{wood:60,coal:20,iron:4})}
 gatherTile(id){const w=this.state.world,d=worldTile(...parseTile(id));if(d.kind!=='resource'||!w.owned.includes(id)||Date.now()<(w.nodeReady?.[id]??0))return;this.dispatch('gather',id,{meat:12})}
 attackTile(id){const w=this.state.world,d=worldTile(...parseTile(id));if(!['camp','settlement'].includes(d.kind)||!w.scouted.includes(id))return;if(d.kind==='camp'&&w.defeated.includes(id)){this.ui.toast('Camp already defeated');return}this.dispatch('attack',id,{meat:Math.ceil(d.strength*.08)})}
 finishOutbound(m,now){const w=this.state.world,d=worldTile(...parseTile(m.target));if(m.type==='scout'){if(!w.scouted.includes(m.target))w.scouted.push(m.target);this.ui.toast('Scout report received')}else if(m.type==='claim'){if(!w.owned.includes(m.target)){w.owned.push(m.target);this.state.power+=55}this.ui.toast('Territory occupied')}else if(m.type==='gather'){m.phase='gathering';m.phaseStartedAt=now;m.gatherDoneAt=now+5000;return}else if(m.type==='attack'){const power=this.detachmentPower(m.troops),win=power>=d.strength,losses=Math.max(1,Math.round(Object.values(m.troops).reduce((a,b)=>a+b,0)*(win?.08:.24)));for(const k of Object.keys(m.troops))w.troops[k]=Math.max(0,(w.troops[k]??0)-Math.round(losses/3));if(win){recordBattleWin(this.state);if(d.kind==='camp'&&!w.defeated.includes(m.target))w.defeated.push(m.target);if(!w.owned.includes(m.target)&&d.kind==='camp')w.owned.push(m.target);for(const [k,v] of Object.entries(d.reward??{}))this.state.resources[k]=(this.state.resources[k]??0)+v;this.state.power+=Math.round(d.strength*.05)}else recordBattleLoss(this.state);w.battleReports.unshift({at:now,target:m.target,name:d.name,enemy:d.strength,power,win,losses});w.battleReports=w.battleReports.slice(0,12);this.ui.toast(win?`Victory · ${losses} casualties`:`Defeat · ${losses} casualties`)}m.phase='returning';m.phaseStartedAt=now;m.arriveAt=now+m.travelMs}
 tickMarches(now){let changed=false,w=this.state.world;for(const m of w.marches){if(m.phase==='outbound'&&now>=m.arriveAt){this.finishOutbound(m,now);changed=true}else if(m.phase==='gathering'&&now>=m.gatherDoneAt){const d=worldTile(...parseTile(m.target));m.cargo={resource:d.resource,amount:Math.round(d.yield*(1+researchBonus(this.state,'allOutput')))};m.phase='returning';m.phaseStartedAt=now;m.arriveAt=now+m.travelMs;changed=true}}const keep=[];for(const m of w.marches){if(m.phase==='returning'&&now>=m.arriveAt){if(m.cargo){this.state.resources[m.cargo.resource]=(this.state.resources[m.cargo.resource]??0)+m.cargo.amount;w.nodeReady[m.target]=now+30000;this.ui.toast(`+${m.cargo.amount} ${m.cargo.resource.toUpperCase()} delivered`)}changed=true}else keep.push(m)}if(keep.length!==w.marches.length)w.marches=keep;if(changed)this.world.refresh();return changed}
 trainTroops(type){const w=this.state.world;if(w.trainingJob){this.ui.toast('Training queue is busy');return}const camp=CAMP_BY_TROOP[type],lvl=this.state.buildings[camp]??0;if(lvl<1){this.ui.toast(`Build ${BUILDINGS[camp].name} first`);return}const amount=20+lvl*10,cost={meat:amount*2,wood:amount,coal:Math.ceil(amount*.2)};if(!has(this.state.resources,cost)){this.ui.toast('Not enough resources');return}spend(this.state.resources,cost);w.trainingJob={type,amount,finishAt:Date.now()+7000};saveState(this.state);this.ui.toast(`Training ${amount} ${type}`);this.ui.refresh()}
 tickTraining(now){const j=this.state.world.trainingJob;if(!j||now<j.finishAt)return false;this.state.world.troops[j.type]=(this.state.world.troops[j.type]??0)+j.amount;this.state.world.trainingJob=null;this.state.power+=j.amount*2;this.ui.toast(`${j.amount} ${j.type} ready`);return true}
 animateWorkers(t){for(const [i,w] of (this.workers??[]).entries()){const a=t*.00025+w.phase;w.view.position.x=-4+i*1.7+Math.sin(a*6+i)*.8;w.view.position.z=2+(i%2)*2+Math.cos(a*5+i)*.6}}
 update(){const now=Date.now(),perf=performance.now(),dt=Math.min(1,(perf-this.last)/1000);this.last=perf;for(const [k,v] of Object.entries(this.productionRates()))this.state.resources[k]=(this.state.resources[k]??0)+v*dt;const built=tickConstruction(this.state),researched=tickResearch(this.state),march=this.tickMarches(now),trained=this.tickTraining(now),events=tickEvents(this.state);if(built){this.rebuildCity();this.ui.toast('Construction complete')}if(built||researched||march||trained||events){saveState(this.state);this.ui.refresh()}this.world.updateMarches(now);this.animateWorkers(perf);if(perf-this.lastSave>900){this.lastSave=perf;this.ui.refresh();saveState(this.state)}this.controls.update()}
 loop(){this.update();this.renderer.render(this.scene,this.camera);requestAnimationFrame(()=>this.loop())}
}
