import { BUILDINGS,buildingRequirements,nextBuildingLevel,RESOURCES } from '../data/buildings.js'
import { findResearch,RESEARCH,researchCost } from '../data/research.js'
import { currentChapter,chapterStatus } from '../data/chapters.js'
import { worldTile,parseTile,adjacentTo } from '../data/world.js'

const short=n=>{const v=Math.floor(Number(n)||0);return v>=1e6?`${(v/1e6).toFixed(1)}M`:v>=1e3?`${(v/1e3).toFixed(1)}K`:`${v}`}
const time=ms=>{let s=Math.max(0,Math.ceil(ms/1000));if(s<60)return`${s}s`;const m=Math.floor(s/60);s%=60;return`${m}m ${s}s`}
const costHtml=c=>Object.entries(c??{}).map(([k,v])=>`<span class="cost ${k}">${k.toUpperCase()} ${short(v)}</span>`).join('')

export class GameUI{
 constructor(game){this.game=game;this.root=document.createElement('div');this.root.className='game-ui';document.body.appendChild(this.root);this.renderShell();this.bind();this.refresh()}
 renderShell(){this.root.innerHTML=`
  <div class="topbar"><div class="profile"><b>R</b><div><strong>EMBERFALL</strong><small id="power"></small></div></div><div id="resources" class="resources"></div></div>
  <button id="quest" class="quest-card"></button><div id="mode-tag" class="mode-tag">CITY</div>
  <button id="update-app" class="update-app">UPDATE</button><div id="queue" class="queue-card"></div><div id="toast" class="toast"></div>
  <div id="sheet" class="sheet hidden"></div>
  <nav class="bottom-nav">
   <button data-mode="city"><span>⌂</span><b>CITY</b></button><button data-mode="world"><span>◎</span><b>WORLD</b></button><button data-action="army"><span>⚔</span><b>ARMY</b></button><button data-action="tech"><span>⌬</span><b>TECH</b></button><button data-action="guild"><span>👥</span><b>GUILD</b></button><button data-action="events"><span>✦</span><b>EVENTS</b></button>
  </nav>`}
 bind(){
  this.root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>this.game.setMode(b.dataset.mode))
  this.root.querySelector('[data-action="army"]').onclick=()=>this.openArmy()
  this.root.querySelector('[data-action="tech"]').onclick=()=>this.openTech()
  this.root.querySelector('[data-action="guild"]').onclick=()=>this.openGuild()
  this.root.querySelector('[data-action="events"]').onclick=()=>this.openEvents()
  this.root.querySelector('#quest').onclick=()=>this.questAction()
  this.root.querySelector('#update-app').onclick=()=>window.appUpdater?.checkAndApply?.()
 }
 toast(msg){const el=this.root.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
 hideSheet(){this.root.querySelector('#sheet').classList.add('hidden')}
 openSheet(html){const s=this.root.querySelector('#sheet');s.innerHTML=html;s.classList.remove('hidden');s.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>this.hideSheet())}
 refresh(){this.refreshTop();this.refreshQuest();this.refreshQueue();this.refreshNav()}
 refreshTop(){const s=this.game.state;this.root.querySelector('#power').textContent=`⚡ ${short(s.power)} POWER`;this.root.querySelector('#resources').innerHTML=Object.entries(RESOURCES).map(([k,r])=>`<div class="resource"><i style="--c:#${r.color.toString(16).padStart(6,'0')}"></i><b>${short(s.resources[k])}</b><small>${r.short}</small></div>`).join('')}
 refreshQuest(){const q=this.root.querySelector('#quest'),ch=currentChapter(this.game.state);if(this.game.mode==='world'||!ch){const w=this.game.state.world;q.innerHTML=`<i>✦</i><div><strong>DOMINION</strong><b>${w.scouted.length<12?'Explore the frontier':w.owned.length<5?'Expand your territory':w.defeated.length<1?'Defeat a raider camp':'Exploit, expand and defeat rival cities'}</b><small>${w.owned.length} territories · ${w.defeated.length} camps defeated</small></div><em>›</em>`;return}const st=chapterStatus(this.game.state,ch);q.innerHTML=`<i>✦</i><div><strong>${ch.title}</strong><b>${st.done?'Reward ready':`${BUILDINGS[st.next?.[0]]?.name??'Settlement'} → Lv. ${st.next?.[1]??''}`}</b><small>${st.complete}/${st.total} objectives</small></div><em>›</em>`}
 questAction(){const ch=currentChapter(this.game.state);if(this.game.mode==='world'||!ch){this.game.setMode('world');return}const st=chapterStatus(this.game.state,ch);if(st.done)this.game.claimChapter(ch);else if(st.next)this.game.focusBuilding(st.next[0])}
 refreshQueue(){const s=this.game.state,c=s.construction,r=s.researchJob,w=s.world;this.root.querySelector('#queue').innerHTML=`<b>${c?`🔨 ${BUILDINGS[c.id].name} ${c.target} · ${time(c.finishAt-Date.now())}`:'✓ Settlement ready'}</b><small>${r?`⌬ ${findResearch(r.id)?.name??r.id} ${r.target} · ${time(r.finishAt-Date.now())}`:`Marches ${w.marches.length}/${this.game.marchCapacity()} · command queues ${c?'active':'idle'}`}</small>`}
 refreshNav(){this.root.querySelector('#mode-tag').textContent=this.game.mode.toUpperCase();this.root.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===this.game.mode))}
 openBuilding(id){const d=BUILDINGS[id],lvl=this.game.state.buildings[id]??0,target=nextBuildingLevel(this.game.state,id),spec=d.levels[target],req=spec?buildingRequirements(this.game.state,id,target):[];this.openSheet(`<header><div><small>${d.category.toUpperCase()}</small><h2>${d.name}</h2><p>Level ${lvl}/12</p></div><button data-close>×</button></header><div class="sheet-body">${spec?`<h3>${lvl?'NEXT UPGRADE':'CONSTRUCT'} · LEVEL ${target}</h3><div class="costs">${costHtml(spec.cost)}</div><p class="require ${req.length?'bad':'good'}">${req.length?`Requires ${req.join(' · ')}`:'All requirements met'}</p><button id="upgrade" class="primary">${this.game.state.construction?'BUILDER BUSY':lvl?'UPGRADE':'CONSTRUCT'}</button>`:'<h3>MAXIMUM LEVEL</h3>'}</div>`);const b=this.root.querySelector('#upgrade');if(b&&!this.game.state.construction)b.onclick=()=>{this.game.upgradeBuilding(id);this.hideSheet()}}
 openWorldTile(id){const [x,y]=parseTile(id),d=worldTile(x,y),w=this.game.state.world,scouted=w.scouted.includes(id),owned=w.owned.includes(id);let action='';if(!scouted&&adjacentTo(id,w.scouted))action=`<button id="tile-action" class="primary">SCOUT</button>`;else if(scouted&&!owned&&!['camp','settlement'].includes(d.kind)&&adjacentTo(id,w.owned))action=`<button id="tile-action" class="primary">OCCUPY</button>`;else if(scouted&&d.kind==='resource'&&owned)action=`<button id="tile-action" class="primary">GATHER</button>`;else if(scouted&&['camp','settlement'].includes(d.kind))action=`<button id="tile-action" class="danger">ATTACK · ${short(d.strength)}</button>`;this.openSheet(`<header><div><small>${d.region.toUpperCase()}</small><h2>${scouted?d.name:'Unknown territory'}</h2><p>${scouted?`Level ${d.level??1} · ${d.kind}`:'Fog of war'}</p></div><button data-close>×</button></header><div class="sheet-body">${scouted&&d.reward?`<h3>REWARD</h3><div class="costs">${costHtml(d.reward)}</div>`:''}${action||'<p>Secure adjacent territory to interact.</p>'}</div>`);const b=this.root.querySelector('#tile-action');if(b)b.onclick=()=>{if(!scouted)this.game.scoutTile(id);else if(!owned&&!['camp','settlement'].includes(d.kind))this.game.claimTile(id);else if(d.kind==='resource')this.game.gatherTile(id);else this.game.attackTile(id);this.hideSheet()}}
 openArmy(){const w=this.game.state.world;this.openSheet(`<header><div><small>COMMAND</small><h2>Army</h2><p>Power ${short(this.game.armyPower())}</p></div><button data-close>×</button></header><div class="sheet-body army-list">${['infantry','lancer','marksman'].map(k=>`<div><span><b>${k.toUpperCase()}</b><small>${short(w.troops[k]??0)} troops</small></span><button data-train="${k}">TRAIN</button></div>`).join('')}</div>`);this.root.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>this.game.trainTroops(b.dataset.train))}
 openTech(){const s=this.game.state,items=Object.values(RESEARCH).flatMap(branch=>Object.entries(branch.items).map(([id,d])=>({id,...d})));this.openSheet(`<header><div><small>SCIENCE</small><h2>Research</h2><p>${s.researchJob?'Queue active':'Research queue idle'}</p></div><button data-close>×</button></header><div class="sheet-body tech-list">${items.map(d=>{const lvl=s.research[d.id]??0,c=researchCost(d,Math.min(d.max,lvl+1));return`<button data-research="${d.id}"><span><b>${d.name}</b><small>Lv. ${lvl}/${d.max}</small></span><em>${lvl>=d.max?'MAX':short(Object.values(c).reduce((a,b)=>a+b,0))}</em></button>`}).join('')}</div>`);this.root.querySelectorAll('[data-research]').forEach(b=>b.onclick=()=>{this.game.research(b.dataset.research);this.hideSheet()})}
 openGuild(){const g=this.game.state.guild;if(!g.id){this.openSheet(`<header><div><small>GUILD</small><h2>No Guild</h2><p>Create or join a guild</p></div><button data-close>×</button></header><div class="sheet-body"><h3>CREATE GUILD</h3><input id="guild-name" type="text" placeholder="Guild name (3-20 chars)" maxlength="20"/><button id="create-guild" class="primary">CREATE</button></div>`);this.root.querySelector('#create-guild').onclick=()=>{const name=this.root.querySelector('#guild-name').value;this.game.createGuild(name)}}else{const members=Object.entries(g.members).map(([id,m])=>`<div><span>${id===g.leader?'👑':''}${id}</span><small>${m.role}</small></div>`).join('');this.openSheet(`<header><div><small>GUILD</small><h2>${g.name}</h2><p>Lv. ${g.level} · ${Object.keys(g.members).length} members</p></div><button data-close>×</button></header><div class="sheet-body"><h3>MEMBERS</h3>${members}<h3>TREASURY</h3><div>${Object.entries(g.treasury).map(([k,v])=>`<div><b>${k.toUpperCase()}</b> ${short(v)}</div>`).join('')}</div></div>`)}}
 openEvents(){const events=this.game.state.events.active.map(e=>`<div><span><b>${e.title}</b><small>${e.description}</small></span><em>${short(Object.values(e.reward??{}).reduce((a,b)=>a+b,0))}</em><button data-event-claim="${e.id}">CLAIM</button></div>`).join('');this.openSheet(`<header><div><small>EVENTS</small><h2>Active Events</h2><p>${this.game.state.events.active.length} active</p></div><button data-close>×</button></header><div class="sheet-body events-list">${events||'<p>No active events</p>'}</div>`);this.root.querySelectorAll('[data-event-claim]').forEach(b=>b.onclick=()=>this.game.claimEventReward(b.dataset.eventClaim))}
}
