import { BUILDINGS,buildingRequirements,nextBuildingLevel,RESOURCES } from '../data/buildings.js'
import { buildingEffectLines } from '../data/buildingProgression.js'
import { findResearch,RESEARCH,researchCost,researchEffectLines } from '../data/research.js'
import { currentChapter,chapterStatus } from '../data/chapters.js'
import { worldTile,parseTile,adjacentTo } from '../data/world.js'

const short=n=>{const v=Math.floor(Number(n)||0);return v>=1e6?`${(v/1e6).toFixed(1)}M`:v>=1e3?`${(v/1e3).toFixed(1)}K`:`${v}`}
const time=ms=>{let s=Math.max(0,Math.ceil(ms/1000));if(s<60)return`${s}s`;const m=Math.floor(s/60);s%=60;if(m<60)return`${m}m ${s}s`;const h=Math.floor(m/60),mm=m%60;return`${h}h ${mm}m`}
const costHtml=c=>Object.entries(c??{}).map(([k,v])=>`<span class="cost ${k}"><i>${RESOURCES[k]?.icon??'•'}</i>${short(v)} ${RESOURCES[k]?.short??k}</span>`).join('')
const TEAM={infantry:{name:'Cleaning crew',copy:'Core service team'},lancer:{name:'Mobile crew',copy:'Fast jobs across the city'},marksman:{name:'Specialists',copy:'Premium and difficult work'}}
const STORIES={meat:'A new client is ready to book.',wood:'A supply opportunity can improve your operation.',coal:'A visible job could boost your reputation.',iron:'A strong candidate is available in this area.'}
const listHtml=(items,klass='info-list')=>`<div class="${klass}">${items.map(x=>`<div>${x}</div>`).join('')}</div>`

export class GameUI{
 constructor(game){this.game=game;this.root=document.createElement('div');this.root.className='game-ui';document.body.appendChild(this.root);this.renderShell();this.bind();this.refresh()}
 renderShell(){this.root.innerHTML=`
  <div class="topbar">
   <div class="profile"><b>A</b><div><strong>ACHU</strong><small id="power"></small></div></div>
   <div id="resources" class="resources"></div>
  </div>
  <button id="quest" class="quest-card"></button>
  <div id="mode-tag" class="mode-tag">MY DISTRICT</div><button id="update-app" class="update-app">REFRESH</button>
  <div id="queue" class="queue-card"></div><div id="toast" class="toast"></div><div id="sheet" class="sheet hidden"></div>
  <nav class="bottom-nav">
   <button data-mode="city"><span>⌂</span><b>MY PLACE</b></button>
   <button data-mode="world"><span>⌖</span><b>THE CITY</b></button>
   <button data-action="army"><span>◉</span><b>CREW</b></button>
   <button data-action="tech"><span>✦</span><b>OFFICE</b></button>
   <button data-action="guild"><span>◇</span><b>PARTNERS</b></button>
   <button data-action="events"><span>☰</span><b>INBOX</b></button>
  </nav>`}
 bind(){this.root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>this.game.setMode(b.dataset.mode));this.root.querySelector('[data-action="army"]').onclick=()=>this.openArmy();this.root.querySelector('[data-action="tech"]').onclick=()=>this.openTech();this.root.querySelector('[data-action="guild"]').onclick=()=>this.openGuild();this.root.querySelector('[data-action="events"]').onclick=()=>this.openEvents();this.root.querySelector('#quest').onclick=()=>this.questAction();this.root.querySelector('#update-app').onclick=()=>window.appUpdater?.checkAndApply?.()}
 toast(msg){const el=this.root.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.remove('show'),1900)}
 hideSheet(){this.root.querySelector('#sheet').classList.add('hidden')}
 openSheet(html){const s=this.root.querySelector('#sheet');s.innerHTML=html;s.classList.remove('hidden');s.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>this.hideSheet())}
 refresh(){this.refreshTop();this.refreshQuest();this.refreshQueue();this.refreshNav()}
 refreshTop(){const s=this.game.state;this.root.querySelector('#power').textContent=`£${short(s.resources.meat)} · ${short(s.power)} VALUE`;this.root.querySelector('#resources').innerHTML=Object.entries(RESOURCES).map(([k,r])=>`<div class="resource"><i style="--c:#${r.color.toString(16).padStart(6,'0')}">${r.icon}</i><b>${short(s.resources[k])}</b><small>${r.label}</small></div>`).join('')}
 refreshQuest(){
  const q=this.root.querySelector('#quest'),ch=currentChapter(this.game.state),w=this.game.state.world
  if(this.game.mode==='world'){const text=w.scouted.length<12?'Find out where the next demand is':w.owned.length<5?'Turn a known neighbourhood into a service area':w.defeated.length<1?'Win a commercial contract':'Grow the ACHU footprint across the city';q.innerHTML=`<i>●</i><div><strong>CITY OBJECTIVE</strong><b>${text}</b><small>${w.owned.length} areas active · ${w.defeated.length} contracts won · tap for details</small></div><em>›</em>`;return}
  if(!ch){q.innerHTML=`<i>♥</i><div><strong>THE STORY CONTINUES IN THE CITY</strong><b>ACHU has built the operating foundation</b><small>Find clients, contracts and new territory</small></div><em>›</em>`;return}
  const st=chapterStatus(this.game.state,ch);q.innerHTML=`<i>${st.done?'✓':'✦'}</i><div><strong>${ch.kicker}</strong><b>${ch.title.split(' · ')[1]??ch.title}</b><small>${st.done?'Milestone complete · tap to review and collect':`${st.complete}/${st.total} objectives · tap for the full briefing`}</small></div><em>›</em>`
 }
 questAction(){const ch=currentChapter(this.game.state);if(this.game.mode==='world'||!ch){this.openCityBriefing();return}this.openMission(ch)}
 openMission(ch){
  const st=chapterStatus(this.game.state,ch),nextName=BUILDINGS[st.next?.[0]]?.name
  const tasks=ch.tasks.map(([id,lvl])=>{const current=this.game.state.buildings[id]??0,done=current>=lvl;return`<div class="mission-row ${done?'done':''}"><span>${done?'✓':'○'}</span><div><b>${BUILDINGS[id]?.name??id}</b><small>Reach level ${lvl} · currently ${current}</small></div></div>`}).join('')
  this.openSheet(`<header><div><small>${ch.kicker}</small><h2>${ch.title.split(' · ')[1]??ch.title}</h2><p>${st.complete}/${st.total} objectives complete</p></div><button data-close>×</button></header><div class="sheet-body"><div class="story-card"><b>${ch.story}</b></div><h3>YOUR OBJECTIVE</h3><p class="brief-copy">${ch.objective}</p><div class="mission-list">${tasks}</div><h3>WHY THIS MATTERS</h3><div class="story-card"><p>${ch.why}</p></div><h3>WHEN YOU FINISH</h3><div class="story-card success"><b>${ch.success}</b></div><h3>REWARD</h3><div class="costs">${costHtml(ch.reward)}</div><h3 class="section-gap">WHAT THIS OPENS</h3>${listHtml(ch.unlocks)}<button id="mission-action" class="primary">${st.done?'COLLECT MILESTONE':`GO TO ${nextName?.toUpperCase()??'NEXT OBJECTIVE'}`}</button></div>`)
  this.root.querySelector('#mission-action').onclick=()=>{if(st.done){this.game.claimChapter(ch);this.hideSheet()}else if(st.next){this.hideSheet();this.game.setMode('city');this.game.focusBuilding(st.next[0])}}
 }
 openCityBriefing(){const w=this.game.state.world;this.openSheet(`<header><div><small>THE CITY</small><h2>Grow where the work is</h2><p>${w.owned.length} service areas · ${w.defeated.length} contracts won</p></div><button data-close>×</button></header><div class="sheet-body"><div class="story-card"><b>Your buildings create capacity. The city is where that capacity becomes business.</b><p>Research unknown neighbourhoods, open service areas next to places you already cover, send crews to live opportunities and pitch for commercial contracts. Stronger crews and better systems let ACHU take on harder work.</p></div><h3>THE LOOP</h3>${listHtml(['1. Research a nearby area to discover what is there.','2. Add useful neighbourhoods to your service route.','3. Send crews to opportunities for Cash, Supplies, Reputation or Talent.','4. Build crew strength before pitching for tougher commercial contracts.','5. Use the rewards to improve the company, then expand farther.'])}<button id="city-go" class="primary">OPEN THE CITY</button></div>`);this.root.querySelector('#city-go').onclick=()=>{this.hideSheet();this.game.setMode('world')}}
 refreshQueue(){const s=this.game.state,c=s.construction,r=s.researchJob,w=s.world;let title='The office is calm',sub='No crew is waiting on you';if(c){title=`${BUILDINGS[c.id].name} is changing`;sub=`Ready in ${time(c.finishAt-Date.now())}`}else if(r){title=`Improving ${findResearch(r.id)?.name??'the business'}`;sub=`Ready in ${time(r.finishAt-Date.now())}`}else if(w.marches.length){title=`${w.marches.length} crew${w.marches.length>1?'s':''} out in the city`;sub='They will return automatically'}this.root.querySelector('#queue').innerHTML=`<b>${title}</b><small>${sub}</small>`}
 refreshNav(){this.root.querySelector('#mode-tag').textContent=this.game.mode==='world'?'THE CITY':'MY DISTRICT';this.root.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===this.game.mode))}
 openBuilding(id){
  const d=BUILDINGS[id],lvl=this.game.state.buildings[id]??0,target=nextBuildingLevel(this.game.state,id),spec=d.levels[target],req=spec?buildingRequirements(this.game.state,id,target):[]
  const currentLines=lvl?buildingEffectLines(id,lvl):[],nextLines=spec?buildingEffectLines(id,target):[]
  const currentBlock=lvl?`<h3>WHAT IT DOES NOW</h3>${listHtml(currentLines.length?currentLines:['This division is active.'],'effect-list')}`:''
  const nextBlock=spec?`<h3>${lvl?'WHAT THE NEXT LEVEL CHANGES':'WHAT OPENING IT GIVES YOU'}</h3>${listHtml(nextLines.length?nextLines:['Unlocks this business capability.'],'effect-list')}<div class="upgrade-meta"><span>Development time <b>${time(spec.seconds*1000)}</b></span><span>Company value <b>+${short(spec.power)}</b></span></div>`:''
  this.openSheet(`<header><div><small>${d.category.toUpperCase()}</small><h2>${d.name}</h2><p>${lvl?`Level ${lvl} of 12`:'Not opened yet'}</p></div><button data-close>×</button></header><div class="sheet-body"><div class="story-card"><b>WHY THIS EXISTS</b><p>${d.description??d.role??''}</p></div>${currentBlock}${nextBlock}${spec?`<h3>WHAT IT COSTS</h3><div class="costs">${costHtml(spec.cost)}</div><p class="require ${req.length?'bad':'good'}">${req.length?`Blocked until: ${req.join(' · ')}`:'Ready to develop now'}</p><button id="upgrade" class="primary">${this.game.state.construction?'DEVELOPMENT SLOT IS BUSY':lvl?`UPGRADE TO LEVEL ${target}`:'OPEN THIS DIVISION'}</button>`:'<div class="story-card success"><b>Fully developed.</b><p>This division has reached its maximum level.</p></div>'}</div>`)
  const b=this.root.querySelector('#upgrade');if(b&&!this.game.state.construction)b.onclick=()=>{this.game.upgradeBuilding(id);this.hideSheet()}
 }
 openWorldTile(id){
  const [x,y]=parseTile(id),d=worldTile(x,y),w=this.game.state.world,scouted=w.scouted.includes(id),owned=w.owned.includes(id);let action='',story=''
  if(!scouted){story='You can see activity here, but you do not know the neighbourhood yet. Researching it reveals the type of opportunity, difficulty and potential value.';if(adjacentTo(id,w.scouted))action='<button id="tile-action" class="primary">RESEARCH THIS AREA</button>'}
  else if(d.kind==='resource'){story=STORIES[d.resource]??'There is a live opportunity here.';if(owned)action='<button id="tile-action" class="primary">SEND A CREW</button>';else if(adjacentTo(id,w.owned))action='<button id="tile-action" class="primary">ADD AREA TO YOUR ROUTE</button>'}
  else if(['camp','settlement'].includes(d.kind)){story=d.kind==='camp'?'A commercial client is looking for a company they can trust. Your crew strength is tested against the contract difficulty.':'Another operator is already strong in this part of town. Winning here requires enough operational strength to compete.';action=`<button id="tile-action" class="danger">MAKE A PITCH · DIFFICULTY ${short(d.strength)}</button>`}
  else{story='A quiet part of the city. Adding it to your route extends where ACHU can reach future opportunities.';if(!owned&&adjacentTo(id,w.owned))action='<button id="tile-action" class="primary">ADD TO YOUR ROUTE</button>'}
  this.openSheet(`<header><div><small>${d.region.toUpperCase()}</small><h2>${scouted?d.name:'Unknown neighbourhood'}</h2><p>${owned?'Inside your service area':scouted?'Researched':'Not researched yet'}</p></div><button data-close>×</button></header><div class="sheet-body"><div class="story-card"><b>WHAT THIS MEANS</b><p>${story}</p>${scouted&&d.reward?`<p><strong>Potential reward:</strong> ${Object.entries(d.reward).map(([k,v])=>`${RESOURCES[k]?.label??k} ${short(v)}`).join(' · ')}</p>`:''}</div>${d.strength?`<h3>YOUR POSITION</h3>${listHtml([`Your crew strength: ${short(this.game.armyPower())}`,`Opportunity difficulty: ${short(d.strength)}`,this.game.armyPower()>=d.strength?'You are strong enough to compete.':'Improve or hire crews before taking this on.'],'effect-list')}`:''}${action||'<p class="quiet-copy">Nothing needs your attention here right now.</p>'}</div>`)
  const b=this.root.querySelector('#tile-action');if(b)b.onclick=()=>{if(!scouted)this.game.scoutTile(id);else if(!owned&&!['camp','settlement'].includes(d.kind))this.game.claimTile(id);else if(d.kind==='resource')this.game.gatherTile(id);else this.game.attackTile(id);this.hideSheet()}
 }
 openArmy(){const w=this.game.state.world;this.openSheet(`<header><div><small>YOUR PEOPLE</small><h2>Crew board</h2><p>${short(this.game.armyPower())} total working strength</p></div><button data-close>×</button></header><div class="sheet-body"><div class="story-card"><b>People are the capacity behind every city action.</b><p>Hiring adds working strength. Better training and leadership multiply the value of the people you already have. Harder commercial contracts compare this strength against their difficulty.</p></div><div class="army-list">${Object.entries(TEAM).map(([k,d])=>`<div><span><b>${d.name}</b><small>${d.copy} · ${short(w.troops[k]??0)} people</small></span><button data-train="${k}">HIRE</button></div>`).join('')}</div></div>`);this.root.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>this.game.trainTroops(b.dataset.train))}
 openTech(){
  const s=this.game.state,groups=Object.values(RESEARCH).map(branch=>`<h3>${branch.label.toUpperCase()}</h3><div class="tech-list">${Object.entries(branch.items).map(([id,d])=>{const lvl=s.research[id]??0,next=Math.min(d.max,lvl+1),effects=researchEffectLines(d,next).join(' · ');return`<button data-tech-detail="${id}"><span><b>${d.name}</b><small>${lvl>=d.max?'Fully researched':`${effects} at level ${next}`}</small></span><em>${lvl>=d.max?'MAX':'›'}</em></button>`}).join('')}</div>`).join('')
  this.openSheet(`<header><div><small>HOW ACHU GETS BETTER</small><h2>Business systems</h2><p>${s.researchJob?'One improvement is underway':'Choose an improvement to understand it first'}</p></div><button data-close>×</button></header><div class="sheet-body"><div class="story-card"><b>Research changes the economics of everything you already built.</b><p>Buildings add capacity. Systems make that capacity faster, stronger or more productive. Tap any improvement to see exactly what changes before spending resources.</p></div>${groups}</div>`)
  this.root.querySelectorAll('[data-tech-detail]').forEach(b=>b.onclick=()=>this.openResearch(b.dataset.techDetail))
 }
 openResearch(id){
  const s=this.game.state,d=findResearch(id);if(!d)return
  const lvl=s.research[id]??0,target=Math.min(d.max,lvl+1),cost=lvl<d.max?researchCost(d,target):{},req=(d.requires??[]).map(([rid,n])=>`${findResearch(rid)?.name??rid} ${n}`)
  const current=researchEffectLines(d,lvl),next=researchEffectLines(d,target)
  this.openSheet(`<header><div><small>${d.branchLabel.toUpperCase()} SYSTEM</small><h2>${d.name}</h2><p>Level ${lvl}/${d.max}</p></div><button data-close>×</button></header><div class="sheet-body"><div class="story-card"><b>WHAT PROBLEM IT SOLVES</b><p>${d.description}</p></div><div class="story-card"><b>WHY YOU WOULD BUY IT</b><p>${d.businessCase}</p></div>${lvl?`<h3>CURRENT EFFECT</h3>${listHtml(current,'effect-list')}`:''}${lvl<d.max?`<h3>NEXT LEVEL</h3>${listHtml(next,'effect-list')}<div class="upgrade-meta"><span>Research time <b>${time(d.seconds*1000)}</b></span><span>Level <b>${target}/${d.max}</b></span></div><h3>RESEARCH COST</h3><div class="costs">${costHtml(cost)}</div>${req.length?`<p class="require">Requires: ${req.join(' · ')}</p>`:''}<button id="start-research" class="primary">${s.researchJob?'RESEARCH SLOT IS BUSY':`RESEARCH LEVEL ${target}`}</button>`:'<div class="story-card success"><b>Fully researched.</b><p>You already have the maximum permanent effect from this system.</p></div>'}</div>`)
  const b=this.root.querySelector('#start-research');if(b&&!s.researchJob)b.onclick=()=>{this.game.research(id);this.hideSheet()}
 }
 openGuild(){const g=this.game.state.guild;if(!g.id){this.openSheet(`<header><div><small>PEOPLE AROUND YOU</small><h2>Partners</h2><p>Build relationships that make bigger work possible</p></div><button data-close>×</button></header><div class="sheet-body"><div class="story-card"><b>You do not have to grow alone.</b><p>A partner network gives ACHU shared support and additional operating capacity. As the network develops it can reduce development time and increase the number of field deployments available.</p></div><input id="guild-name" type="text" placeholder="Give the network a name" maxlength="20"/><button id="create-guild" class="primary">CREATE PARTNER NETWORK</button></div>`);this.root.querySelector('#create-guild').onclick=()=>this.game.createGuild(this.root.querySelector('#guild-name').value)}else{const members=Object.entries(g.members).map(([id,m])=>`<div class="network-member"><span>${id===g.leader?'★ ':''}${id}</span><small>${m.role}</small></div>`).join('');this.openSheet(`<header><div><small>PARTNER NETWORK</small><h2>${g.name}</h2><p>Level ${g.level} · ${Object.keys(g.members).length} partners</p></div><button data-close>×</button></header><div class="sheet-body"><div class="story-card"><b>Why this matters</b><p>Your network is shared operating leverage: partners help development and support larger field capacity as it grows.</p></div>${members}</div>`)}}
 openEvents(){const events=this.game.state.events.active.map(e=>`<div><span><b>${e.title}</b><small>${e.description}</small></span><button data-event-claim="${e.id}">${e.claimed?'DONE':'CLAIM'}</button></div>`).join('');this.openSheet(`<header><div><small>WHAT'S HAPPENING</small><h2>Inbox</h2><p>${this.game.state.events.active.length?`${this.game.state.events.active.length} live business situations`:'Nothing urgent'}</p></div><button data-close>×</button></header><div class="sheet-body"><div class="story-card"><b>The business does not stand still.</b><p>Inbox events are temporary situations: demand spikes, tenders, staffing opportunities and disruptions. Rewards are separate from the main chapter story.</p></div><div class="events-list">${events||'<div class="story-card success"><b>Quiet is good sometimes.</b><p>No new deals or surprises right now.</p></div>'}</div></div>`);this.root.querySelectorAll('[data-event-claim]').forEach(b=>b.onclick=()=>this.game.claimEventReward(b.dataset.eventClaim))}
}
