import * as THREE from 'three'
import { worldTile,BASE_TILE,parseTile,FACTIONS } from '../data/world.js'

const SIZE=21
const key=(x,y)=>`${x},${y}`
const hash=(x,y,s=0)=>Math.abs(Math.sin(x*91.17+y*47.31+s*17.71)*43758.5453)%1
const mat=(color,rough=.82,metal=.03)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})
const transparent=(color,opacity)=>new THREE.MeshStandardMaterial({color,roughness:.88,transparent:true,opacity,depthWrite:false})
const box=(w,h,d,m)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.castShadow=true;o.receiveShadow=true;return o}
const curve=(points,closed=false)=>new THREE.CatmullRomCurve3(points.map(([x,z])=>new THREE.Vector3(x,0,z)),closed,'centripetal',.22)
const ROAD_DEFS=[{points:[[-22,6],[-16,7],[-9,6],[-3,3],[2,2.4],[8,3.3],[15,6],[22,7]],width:2.35},{points:[[-3,18],[-2,12],[-1,7],[0,2.5],[1,-4],[3,-10],[5,-16]],width:1.95},{points:[[-20,-12],[-14,-13],[-7,-13],[0,-12],[8,-10.5],[15,-7],[21,-3]],width:1.85},{points:[[-19,11],[-16,14],[-11,15],[-7,12],[-8,8],[-13,7],[-19,11]],width:1.65,closed:true},{points:[[9,12],[14,14],[19,12],[20,7],[17,4],[12,4],[9,7],[9,12]],width:1.65,closed:true},{points:[[-19,0],[-14,1],[-10,.5],[-6,-1.5],[-2,-3],[4,-4],[10,-3],[16,-1],[21,1]],width:1.55},{points:[[-16,-13],[-14,-8],[-12,-4],[-10,1],[-8,6]],width:1.55}]
const ROAD_CURVES=ROAD_DEFS.map(d=>({...d,curve:curve(d.points,d.closed)}))
function closestPointOnSegment(px,pz,a,b){const vx=b[0]-a[0],vz=b[1]-a[1],l=vx*vx+vz*vz||1,t=Math.max(0,Math.min(1,((px-a[0])*vx+(pz-a[1])*vz)/l));return{x:a[0]+vx*t,z:a[1]+vz*t}}
function pushAway(x,z,min=1.15){let px=x,pz=z;for(let pass=0;pass<3;pass++)for(const d of ROAD_DEFS){for(let i=0;i<d.points.length-1;i++){const q=closestPointOnSegment(px,pz,d.points[i],d.points[i+1]),dx=px-q.x,dz=pz-q.z,dist=Math.hypot(dx,dz),limit=min+d.width*.28;if(dist>=limit)continue;let nx=dx,nz=dz;if(dist<.001){const sx=d.points[i+1][0]-d.points[i][0],sz=d.points[i+1][1]-d.points[i][1];nx=-sz;nz=sx}const len=Math.hypot(nx,nz)||1,move=limit-dist+.14;px+=nx/len*move;pz+=nz/len*move}}return new THREE.Vector3(px,0,pz)}
export function worldVisualPositionV10(x,y){if(x===10&&y===10)return new THREE.Vector3(1.6,0,5.2);const gx=Math.floor(x/3)-3,gy=Math.floor(y/3)-3,sx=x%3-1,sy=y%3-1,cx=gx*4.55+(gy%2)*.55,cz=gy*4.25+Math.sin(gx*.72)*.45,ang=gx*.11-gy*.09,ca=Math.cos(ang),sa=Math.sin(ang),ox=(sx*ca-sy*sa)*.72,oz=(sx*sa+sy*ca)*.72;return pushAway(cx+ox,cz+oz)}
function ribbonGeometry(c,width,y=.03,segments=140){const verts=[],idx=[];for(let i=0;i<=segments;i++){const u=i/segments,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),nx=-t.z,nz=t.x;verts.push(p.x+nx*width/2,y,p.z+nz*width/2,p.x-nx*width/2,y,p.z-nz*width/2)}for(let i=0;i<segments;i++){const q=i*2;idx.push(q,q+1,q+2,q+1,q+3,q+2)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g}
function ribbon(parent,c,width,color,y=.03){const m=new THREE.Mesh(ribbonGeometry(c,width,y),mat(color,.97));m.receiveShadow=true;m.castShadow=false;parent.add(m);return m}
function dashed(parent,c,count=64,y=.085){const dm=mat(0xe5e8e1,.72);for(let i=1;i<count;i+=2){const u=i/count,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),d=box(.05,.018,.42,dm);d.position.set(p.x,y,p.z);d.rotation.y=Math.atan2(t.x,t.z);d.castShadow=false;parent.add(d)}}
function fit(view,{w=2,h=2,d=2}){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=Math.min(w/Math.max(.001,s.x),h/Math.max(.001,s.y),d/Math.max(.001,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function building(parent,bank,name,x,z,{w=1.05,h=1.4,d=1,rot=0}={}){const v=fit(bank?.clone?.(name)??new THREE.Group(),{w,h,d});v.position.set(x,0,z);v.rotation.y=rot;parent.add(v);return v}
function tree(parent,bank,x,z,h=1.2,i=0){const v=bank?.cloneTree?.(i,h);if(!v)return;v.position.set(x,0,z);v.rotation.y=(i*.87)%6.283;parent.add(v)}
function fitRoad(view,size=2.5){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=size/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function roadAsset(parent,bank,name,x,z,rot=0,size=2.5,y=.055){const v=fitRoad(bank?.clone?.(name)??new THREE.Group(),size);v.position.set(x,y,z);v.rotation.y=rot;parent.add(v);return v}
function fitCar(view,target=1.0){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),longX=s.x>s.z*1.08,sc=target/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;view.userData.forwardOffset=longX?-Math.PI/2:0;return view}
function car(parent,bank,index=0,target=1.0){const v=fitCar(bank?.cloneCar?.(index)??bank?.clone?.('carSedan')??new THREE.Group(),target);parent.add(v);return v}
function ring(parent,r,color,opacity=.5){const m=new THREE.Mesh(new THREE.RingGeometry(r*.78,r,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.y=.09;parent.add(m);return m}
function disk(parent,r,color,opacity=.12){const m=new THREE.Mesh(new THREE.CircleGeometry(r,40),transparent(color,opacity));m.rotation.x=-Math.PI/2;m.position.y=.05;parent.add(m)}
function labelSprite(text,color=0xffffff,scale=1){const c=document.createElement('canvas');c.width=640;c.height=128;const x=c.getContext('2d');x.fillStyle='rgba(12,26,23,.90)';x.roundRect(12,17,616,94,22);x.fill();x.strokeStyle=`#${color.toString(16).padStart(6,'0')}`;x.lineWidth=3;x.stroke();x.fillStyle='#eef2eb';x.font='800 28px Inter,Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text.toUpperCase(),320,64,570);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(4.05*scale,.82*scale,1);return s}
function riverCurve(){return curve([[-24,-6],[-18,-7],[-11,-6.3],[-5,-7.2],[1,-8],[8,-7],[14,-4.8],[20,-4],[24,-2.8]])}
function buildRiver(root,bank){const c=riverCurve();ribbon(root,c,5.0,0x6b8174,-.055);const water=new THREE.Mesh(ribbonGeometry(c,4.05,-.035,170),new THREE.MeshStandardMaterial({color:0x4b969c,roughness:.34,metalness:.05,transparent:true,opacity:.92}));water.receiveShadow=true;root.add(water);const promenade=new THREE.CatmullRomCurve3(Array.from({length:36},(_,i)=>{const u=i/35,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),n=new THREE.Vector3(-t.z,0,t.x);return p.clone().add(n.multiplyScalar(3.0))}),false,'centripetal',.18);ribbon(root,promenade,.60,0xc7cbc1,.055);for(let i=3;i<33;i+=3){const u=i/35,p=promenade.getPointAt(u),t=promenade.getTangentAt(u).normalize(),n=new THREE.Vector3(-t.z,0,t.x);tree(root,bank,p.x+n.x*.7,p.z+n.z*.7,1.0+(i%4)*.12,400+i)}const p=c.getPointAt(.78),deck=box(.72,.15,5.0,mat(0xbab8ab,.86));deck.position.set(p.x,.45,p.z);deck.rotation.y=-.15;root.add(deck)}
function bridge(root,bank,x,z,rot=0){for(const dz of[-2.0,0,2.0])roadAsset(root,bank,'roadBridge',x+Math.sin(rot)*dz,z+Math.cos(rot)*dz,rot,2.25,.38);roadAsset(root,bank,'roadSlantHigh',x-Math.sin(rot)*3.8,z-Math.cos(rot)*3.8,rot,2.35,.08);roadAsset(root,bank,'roadSlantHigh',x+Math.sin(rot)*3.8,z+Math.cos(rot)*3.8,rot+Math.PI,2.35,.08);for(const dz of[-1.25,1.25])if(bank?.models?.bridgePillarWide){const p=fit(bank.clone('bridgePillarWide'),{w:.72,h:1.0,d:.72});p.position.set(x+Math.sin(rot)*dz,-.02,z+Math.cos(rot)*dz);root.add(p)}}
function roadLight(root,bank,x,z,r=0){if(!bank?.models?.roadLightCurved)return;const v=fit(bank.clone('roadLightCurved'),{w:.22,h:1.5,d:.22});v.position.set(x,.04,z);v.rotation.y=r;root.add(v)}
function buildRoads(root,bank){for(const d of ROAD_CURVES){ribbon(root,d.curve,d.width+.88,0x87968f,.02);ribbon(root,d.curve,d.width,0x273435,.055);dashed(root,d.curve,d.closed?72:58)}roadAsset(root,bank,'roadRoundabout',0,2.5,0,4.2,.07);roadAsset(root,bank,'roadRoundabout',14.5,6.3,0,3.3,.07);roadAsset(root,bank,'roadSplit',5.0,-15.4,-.7,2.6,.07);roadAsset(root,bank,'roadDrivewayDouble',12.0,4.8,.25,2.25,.07);roadAsset(root,bank,'roadDrivewaySingle',-15.0,10.0,-.45,2.1,.07);roadAsset(root,bank,'roadCrossing',-3.3,3.3,1.15,2.25,.07);bridge(root,bank,1.5,-7.4,-.12);bridge(root,bank,-11.2,-6.3,.10);for(const [x,z,r] of[[-17,7,.8],[-8,5,1.0],[4,2.5,-1.2],[11,4,-1],[18,6,-1.3],[-15,-.3,.2],[12,-2.3,-1.1],[6,-15,.4],[-10,-13,1.5]])roadLight(root,bank,x,z,r)}
function lot(parent,x,z,w,d,color=0xaabbb1,rot=0){const p=box(w,.05,d,mat(color,.99));p.position.set(x,-.01,z);p.rotation.y=rot;p.castShadow=false;parent.add(p)}
function parking(parent,bank,x,z,rot=0,count=4){const g=new THREE.Group();g.position.set(x,.04,z);g.rotation.y=rot;const p=box(4.2,.05,2.35,mat(0x465150,.99));p.castShadow=false;g.add(p);for(let i=-2;i<=2;i++){const l=box(.035,.018,1.9,mat(0xe0e2da,.76));l.position.set(i*.78,.045,0);l.castShadow=false;g.add(l)}for(let i=0;i<count;i++){const v=car(g,bank,i,.80+(i%2)*.05);v.position.set(-1.18+i*.78,.07,(i%2)*.1-.05);v.rotation.y=v.userData.forwardOffset??0}parent.add(g)}
function districtLabel(root,text,x,z,color){const l=labelSprite(text,color,.66);l.position.set(x,2.0,z);root.add(l)}
function buildDistricts(root,bank){lot(root,1.8,8.2,10.5,8.2,0xb5c0b8,.08);[[-2.0,5.8,'achuOffice',1.2,2.2,.2],[1.2,6.0,'achuStudio',1.15,1.85,-.15],[4.7,6.2,'achuOffice',1.25,2.3,.08],[-1.1,10.4,'achuSmallOffice',1.0,1.5,.1],[2.2,10.5,'achuOffice',1.15,2.0,-.12],[5.2,10.1,'achuStudio',1.05,1.7,.08]].forEach(([x,z,n,w,h,r])=>building(root,bank,n,x,z,{w,h,d:1.0,rot:r}));parking(root,bank,6.4,8.0,Math.PI/2,4);districtLabel(root,'Central',1.7,12.5,0x52d9a6);lot(root,-14,10,9.5,12.5,0xb9c9bb,-.08);[[-17,6.2],[-12.2,6.5],[-17.1,10],[-12.0,10.2],[-16.8,13.8],[-12.2,14.0]].forEach(([x,z],i)=>{building(root,bank,'achuClient',x,z,{w:.92,h:1.05,d:.9,rot:(i%3)*.2});tree(root,bank,x+(i%2?.8:-.8),z+.8,.8,620+i)});districtLabel(root,'West End',-14,16.0,0x7cc7a5);lot(root,14,9,10.3,10.0,0xb4c0bd,.05);[[11.4,6.3],[16.5,6.6],[11.7,10.8],[16.6,11.0]].forEach(([x,z],i)=>building(root,bank,i%2?'achuOffice':'achuSmallOffice',x,z,{w:1.08,h:1.5+i*.12,d:1.0,rot:Math.PI/2}));parking(root,bank,14,8.8,0,4);districtLabel(root,'Business Park',14.2,14.0,0x77aee3);lot(root,1,-14.7,28,5.0,0xaeb9b2,.02);[[-10.5,-14.6,'achuWarehouse',1.7,1.2],[-5.3,-14.7,'achuDepot',1.5,1.05],[3.6,-14.3,'achuWarehouse',1.8,1.25],[12.7,-12.7,'achuDepot',1.5,1.05]].forEach(([x,z,n,w,h],i)=>building(root,bank,n,x,z,{w,h,d:1.35,rot:i%2?Math.PI/2:0}));parking(root,bank,9.0,-14.1,0,4);districtLabel(root,'Logistics',1,-17.1,0xe0b85a);lot(root,-2,-1.6,19,4.5,0xa9c1aa,.03);for(let i=0;i<14;i++){const x=-11+i*1.55,z=-1.2+(i%3-1)*.75;if(Math.abs(x)<2.1)continue;tree(root,bank,x,z,.82+(i%3)*.08,700+i)}districtLabel(root,'Riverside',-4,-3.2,0x69c7cc)}
function hitPlane(parent,id){const h=new THREE.Mesh(new THREE.CircleGeometry(.55,18),new THREE.MeshBasicMaterial({transparent:true,opacity:.001,side:THREE.DoubleSide,depthWrite:false}));h.rotation.x=-Math.PI/2;h.position.y=.14;h.userData.tileId=id;parent.add(h)}
function tileVisual(parent,bank,d,id,known,owned){if(owned){disk(parent,.50,0x45c996,.12);ring(parent,.49,0x4ed6a0,.30)}if(!known)return;if(id===BASE_TILE){building(parent,bank,'achuHq',0,0,{w:1.18,h:1.72,d:1.02,rot:.12});ring(parent,.68,0x52d9a6,.74);const l=labelSprite('ACHU HQ',0x52d9a6,.46);l.position.set(0,1.92,0);parent.add(l);return}if(d.businessType==='framework'){building(parent,bank,'achuOffice',0,0,{w:.90,h:1.30,d:.84,rot:.22});ring(parent,.56,FACTIONS[d.tag]?.color??0xc397d3,.55);return}if(d.businessType==='tender'){building(parent,bank,'achuSmallOffice',0,0,{w:.86,h:1.02,d:.80,rot:.18});ring(parent,.53,0xf0a64d,.62);return}if(d.businessType==='lead'){building(parent,bank,'achuClient',0,0,{w:.76,h:.88,d:.74,rot:.15});ring(parent,.48,0x4bd39e,.46);return}if(hash(d.x,d.y)<.22)tree(parent,bank,0,0,.72,d.x*31+d.y)}
function nearestRoadPoint(p){let best=null,bestD=Infinity;for(const d of ROAD_CURVES){const steps=d.closed?90:70;for(let i=0;i<=steps;i++){const q=d.curve.getPointAt(i/steps),dist=q.distanceToSquared(p);if(dist<bestD){bestD=dist;best=q}}}return best?.clone()??new THREE.Vector3()}
function marchCurve(targetId){const [tx,ty]=parseTile(targetId),target=worldVisualPositionV10(tx,ty),base=worldVisualPositionV10(10,10),a=nearestRoadPoint(base),b=nearestRoadPoint(target),centre=new THREE.Vector3(0,0,2.5);return new THREE.CatmullRomCurve3([base,a,centre,b,target],false,'centripetal',.22)}
function trafficNetwork(root,bank){const routes=[ROAD_CURVES[0].curve,ROAD_CURVES[1].curve,ROAD_CURVES[2].curve,ROAD_CURVES[3].curve,ROAD_CURVES[4].curve],out=[];for(let i=0;i<15;i++){const v=car(root,bank,i,.95+(i%3)*.06);out.push({view:v,curve:routes[i%routes.length],offset:(i*.071)%1,speed:.0000057+(i%4)*.0000007})}return out}
function moveTraffic(traffic,now){for(const t of traffic??[]){const u=(t.offset+now*t.speed)%1,p=t.curve.getPointAt(u),tan=t.curve.getTangentAt(u).normalize();t.view.position.set(p.x,.11,p.z);t.view.rotation.y=Math.atan2(tan.x,tan.z)+(t.view.userData.forwardOffset??0)}}
export class WorldCityV10 extends THREE.Group{constructor(bank,state){super();this.bank=bank;this.state=state;this.tiles=new Map();this.marchObjects=new Map();this.traffic=[];this.build()}build(){this.clear();this.tiles.clear();this.marchObjects.clear();const ground=new THREE.Mesh(new THREE.PlaneGeometry(46,38),mat(0xb0c1b7,1));ground.rotation.x=-Math.PI/2;ground.position.y=-.13;ground.receiveShadow=true;this.add(ground);buildRiver(this,this.bank);buildRoads(this,this.bank);buildDistricts(this,this.bank);this.traffic=trafficNetwork(this,this.bank);const owned=new Set(this.state.world.owned??[]),scouted=new Set(this.state.world.scouted??[]);for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const d=worldTile(x,y),id=key(x,y),p=worldVisualPositionV10(x,y),g=new THREE.Group();g.position.copy(p);g.userData.tileId=id;hitPlane(g,id);tileVisual(g,this.bank,d,id,scouted.has(id),owned.has(id));g.traverse(o=>o.userData.tileId=id);this.add(g);this.tiles.set(id,g)}this.refreshMarches();moveTraffic(this.traffic,Date.now())}refresh(){this.build()}refreshMarches(){for(const o of this.marchObjects.values())o.removeFromParent();this.marchObjects.clear();for(const m of this.state.world.marches??[]){const o=car(this,this.bank,m.type==='attack'?4:1,.80);o.userData.route=marchCurve(m.target);this.marchObjects.set(m.id,o)}this.updateMarches(Date.now())}updateMarches(now){moveTraffic(this.traffic,now);for(const m of this.state.world.marches??[]){const o=this.marchObjects.get(m.id);if(!o)continue;let p=1,returning=false;if(m.phase==='outbound')p=Math.max(0,Math.min(1,(now-m.phaseStartedAt)/Math.max(1,m.arriveAt-m.phaseStartedAt)));else if(m.phase==='returning'){returning=true;p=1-Math.max(0,Math.min(1,(now-m.phaseStartedAt)/Math.max(1,m.arriveAt-m.phaseStartedAt)))}const c=o.userData.route??marchCurve(m.target),pos=c.getPointAt(p),tan=c.getTangentAt(p).normalize().multiplyScalar(returning?-1:1);o.position.set(pos.x,.11,pos.z);o.rotation.y=Math.atan2(tan.x,tan.z)+(o.userData.forwardOffset??0)}}focusTile(id){const t=this.tiles.get(id);return t?new THREE.Vector3(t.position.x,0,t.position.z):new THREE.Vector3()}}
