import * as THREE from 'three'
import { BASE_TILE,parseTile } from '../data/world.js'
import { fourXFlow } from './fourXFlow.js'
import { worldVisualPositionV13 } from './worldCityV13.js'

export const WORLD_VISUAL_SCALE=.98
const point=id=>{const [x,y]=parseTile(id),p=worldVisualPositionV13(x,y).multiplyScalar(WORLD_VISUAL_SCALE);p.y=.11;return p}
function label(text,color=0xffffff){const c=document.createElement('canvas');c.width=500;c.height=104;const x=c.getContext('2d');x.fillStyle='rgba(12,27,24,.92)';x.roundRect(7,11,486,82,20);x.fill();x.strokeStyle=`#${color.toString(16).padStart(6,'0')}`;x.lineWidth=4;x.stroke();x.fillStyle='#eef2eb';x.font='900 25px Inter,Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text,250,52,445);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(3.25,.68,1);return s}
function marker(parent,p,text,color=0x53d2a0){const g=new THREE.Group();g.position.copy(p);const ring=new THREE.Mesh(new THREE.RingGeometry(.42,.59,38),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.92,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;g.add(ring);const beam=new THREE.Mesh(new THREE.CylinderGeometry(.032,.055,.9,10),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.4,depthWrite:false}));beam.position.y=.45;g.add(beam);const l=label(text,color);l.position.y=1.15;l.scale.multiplyScalar(.58);g.add(l);parent.add(g);return g}
export class WorldClarityOverlay extends THREE.Group{constructor(state){super();this.state=state;this.name='world-clarity-v13';this.objectiveId=null;this.baseMarker=null;this.objective=null;this.buildBase();this.sync(state,true)}buildBase(){this.baseMarker=marker(this,point(BASE_TILE),'ACHU HQ',0x53d2a0);this.baseMarker.scale.setScalar(.8)}sync(state,force=false){this.state=state;const flow=fourXFlow(state),id=flow.target??null;if(!force&&id===this.objectiveId)return;this.objective?.removeFromParent();this.objective=null;this.objectiveId=id;if(!id)return;this.objective=marker(this,point(id),`NEXT · ${flow.label}`,0xe0b85a)}animate(now){if(!this.objective)return;const s=1+Math.sin(now*.004)*.06;this.objective.scale.setScalar(s)}objectivePoint(){return this.objectiveId?point(this.objectiveId):point(BASE_TILE)}basePoint(){return point(BASE_TILE)}}
