import * as THREE from 'three'
import { worldTile,BASE_TILE,parseTile,FACTIONS } from '../data/world.js'
const SIZE=21,key=(x,y)=>`${x},${y}`,mat=(color,rough=.88,metal=.02)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal}),box=(w,h,d,m)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.castShadow=true;o.receiveShadow=true;return o},path=(pts,closed=false)=>new THREE.CatmullRomCurve3(pts.map(([x,z])=>new THREE.Vector3(x,0,z)),closed,'centripetal',.12)
const BLOCK=4.4,SLOT=1.05
function logical(i){const g=Math.floor(i/3)-3,s=i%3-1;return g*BLOCK+s*SLOT}
export function worldVisualPositionV14(x,y){return new THREE.Vector3(logical(x),0,logical(y))}
function fit(view,{w=2,h=2,d=2}){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=Math.min(w/Math.max(.001,s.x),h/Math.max(.001,s.y),d/Math.max(.001,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function fitRoad(view,size=2.15){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=size/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function roadAsset(root,bank,keyName,x,z,rot=0,size=2.15,y=.03){if(!bank?.models?.[keyName])return;const v=fitRoad(bank.clone(keyName),size);v.position.set(x,y,z);v.rotation.y=rot;root.add(v)}
function building(root,bank,name,x,z,{w=1.15,h=1.7,d=1.0,rot=0}={}){const v=fit(bank?.clone?.(name)??new THREE.Group(),{w,h,d});v.position.set(x,0,z);v.rotation.y=rot;root.add(v);return v}
function tree(root,bank,x,z,h=1.12,i=0){const v=bank?.cloneTree?.(i,h);if(!v)return;v.position.set(x,0,z);v.rotation.y=(i*.81)%6.283;root.add(v)}
function label(text,color=0xffffff,scale=1){const c=document.createElement('canvas');c.width=560;c.height=96;const x=c.getContext('2d');x.fillStyle='rgba(9,24,21,.90)';x.roundRect(7,10,546,76,18);x.fill();x.strokeStyle=`#${color.toString(16).padStart(6,'0')}`;x.lineWidth=3;x.stroke();x.fillStyle='#eef2eb';x.font='800 22px Inter,Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text.toUpperCase(),280,48,500);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(2.8*scale,.49*scale,1);return s}
function districtLabel(root,text,x,z,color){const l=label(text,color,.8);l.position.set(x,2.25,z);root.add(l)}
function ring(root,r,color,opacity=.55){const m=new THREE.Mesh(new THREE.RingGeometry(r*.79,r,34),new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.y=.07;root.add(m)}
function disk(root,r,color,opacity=.08){const m=new THREE.Mesh(new THREE.CircleGeometry(r,34),new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.y=.035;root.add(m)}
function roadStrip(root,x,z,w,d,vertical=false,minor=false){const curb=box(w+.36,.035,d+.36,mat(0xc8cec8,.99));curb.position.set(x,-.006,z);curb.castShadow=false;root.add(curb);const r=box(w,.05,d,mat(minor?0x394443:0x303a39,.99));r.position.set(x,.025,z);r.castShadow=false;root.add(r);const dash=mat(0xe8e8df,.72);if(vertical){for(let zz=z-d/2+.8;zz<z+d/2-.6;zz+=1.45){const q=box(.05,.012,.5,dash);q.position.set(x,.058,zz);q.castShadow=false;root.add(q)}}else{for(let xx=x-w/2+.8;xx<x+w/2-.6;xx+=1.45){const q=box(.5,.012,.05,dash);q.position.set(xx,.058,z);q.castShadow=false;root.add(q)}}}
function blockPad(root,x,z,w,d,color){const p=box(w,.03,d,mat(color,.99));p.position.set(x,-.045,z);p.castShadow=false;root.add(p)}
function parking(root,bank,x,z,rot=0,count=4,logistics=false){const g=new THREE.Group();g.position.set(x,.04,z);g.rotation.y=rot;const p=box(3.0,.04,1.9,mat(0x37413f,.99));p.castShadow=false;g.add(p);for(let i=-2;i<=2;i++){const l=box(.03,.012,1.56,mat(0xe7e8df,.75));l.position.set(i*.56,.03,0);l.castShadow=false;g.add(l)}for(let i=0;i<count;i++){const k=logistics?['carVan','carDelivery','carTruck'][i%3]:i%2?'carSuv':'carSedan',v=fit(bank?.clone?.(k)??new THREE.Group(),{w:.7,h:.55,d:.98});v.position.set(-.84+i*.56,.05,0);g.add(v)}root.add(g)}
function bench(root,x,z,r=0){const g=new THREE.Group(),wood=mat(0x6d5944,.9),metal=mat(0x343d3b,.8,.18);const seat=box(.88,.1,.28,wood);seat.position.y=.34;g.add(seat);for(const xx of[-.33,.33]){const leg=box(.07,.32,.07,metal);leg.position.set(xx,.17,0);g.add(leg)}g.position.set(x,0,z);g.rotation.y=r;root.add(g)}
function buildGround(root){const outer=box(34,.15,30,mat(0x4a6459,1));outer.position.y=-.19;outer.castShadow=false;root.add(outer);const inner=box(32.8,.05,28.8,mat(0x789286,1));inner.position.y=-.09;inner.castShadow=false;root.add(inner)}
function buildRoads(root,bank){for(const x of[-11,-6.6,-2.2,2.2,6.6,11])roadStrip(root,x,0,1.05,27.2,true,true);for(const z of[-10.8,-6.4,-2.0,2.4,6.8,11.2])roadStrip(root,0,z,31.2,1.05,false,true);roadStrip(root,0,2.4,31.2,1.5,false,false);roadStrip(root,-2.2,0,1.5,27.2,true,false);roadAsset(root,bank,'roadRoundabout',-2.2,2.4,0,3.25);roadAsset(root,bank,'roadRoundabout',6.6,6.8,0,2.7);roadAsset(root,bank,'roadCrossroad',-11,-6.4,0,2.05);roadAsset(root,bank,'roadCurveIntersection',11,-2.0,0,2.1);roadAsset(root,bank,'roadIntersectionPath',2.2,11.2,0,2.1);roadAsset(root,bank,'roadCrossing',-6.6,2.4,Math.PI/2,1.95);roadAsset(root,bank,'roadSideEntry',11,6.8,-Math.PI/2,1.8);roadAsset(root,bank,'roadSideExit',-11,2.4,Math.PI/2,1.8);roadAsset(root,bank,'highwaySign',-2.2,10.2,Math.PI/2,1.8);for(const [x,z,r] of[[-8.7,3.1,0],[-4.3,3.1,0],[.2,3.1,0],[4.4,3.1,0],[8.8,3.1,0],[-1.5,-8.7,Math.PI/2],[-1.5,-4.3,Math.PI/2],[-1.5,7.7,Math.PI/2]])roadAsset(root,bank,'roadLightCurved',x,z,r,.72)}
function riverGeometry(c,width,y=-.07,segments=120){const verts=[],idx=[];for(let i=0;i<=segments;i++){const u=i/segments,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),nx=-t.z,nz=t.x;verts.push(p.x+nx*width/2,y,p.z+nz*width/2,p.x-nx*width/2,y,p.z-nz*width/2)}for(let i=0;i<segments;i++){const q=i*2;idx.push(q,q+1,q+2,q+1,q+3,q+2)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g}
const RIVER=path([[-17,-8.4],[-12,-8.0],[-7,-8.8],[-2,-8.5],[3,-7.4],[8,-7.0],[13,-7.6],[17,-7.1]])
function buildRiver(root,bank){const bankMesh=new THREE.Mesh(riverGeometry(RIVER,4.6,-.08),mat(0x607c71,.95));bankMesh.receiveShadow=true;root.add(bankMesh);const water=new THREE.Mesh(riverGeometry(RIVER,3.7,-.055),new THREE.MeshStandardMaterial({color:0x4c99a0,roughness:.3,transparent:true,opacity:.94}));water.receiveShadow=true;root.add(water);for(const [x,z,r] of[[-6.6,-8.7,.08],[6.6,-7.1,-.12]]){for(const dz of[-1.45,0,1.45])roadAsset(root,bank,'roadBridge',x+Math.sin(r)*dz,z+Math.cos(r)*dz,r,1.9,.34);roadAsset(root,bank,'roadSlantHigh',x-Math.sin(r)*3.0,z-Math.cos(r)*3.0,r,2.0,.08);roadAsset(root,bank,'roadSlantHigh',x+Math.sin(r)*3.0,z+Math.cos(r)*3.0,r+Math.PI,2.0,.08)}const p=RIVER.getPointAt(.52),deck=box(.7,.14,3.9,mat(0xb5b9af,.88));deck.position.set(p.x,.34,p.z);deck.rotation.y=-.08;root.add(deck);bench(root,p.x-1.8,p.z+2.1,.1);bench(root,p.x+1.8,p.z+2.0,-.1)}
function buildDistricts(root,bank){blockPad(root,-11.0,7.8,8.0,5.4,0x80988a);districtLabel(root,'WEST END',-11.0,10.0,0xd5aa74);for(const [x,z,k,r] of[[-13.5,8.8,'cityA',.1],[-10.9,8.9,'cityC',-.1],[-8.4,8.7,'achuClient',.1],[-13.3,6.7,'cityE',-.15],[-10.7,6.5,'achuSmallOffice',.08],[-8.3,6.4,'cityG',-.1]])building(root,bank,k,x,z,{w:1.25,h:1.75,d:1.1,rot:r});blockPad(root,-1.0,7.9,9.5,5.5,0x879a91);districtLabel(root,'CENTRAL',-1,10.3,0x6bd7b3);for(const [x,z,k,h] of[[-4.0,8.8,'cityD',2.6],[-1.5,8.9,'cityN',2.9],[1.0,8.8,'cityS',2.4],[-3.9,6.5,'cityU',2.2],[-1.2,6.4,'achuOffice',2.3],[1.2,6.5,'cityJ',2.2]])building(root,bank,k,x,z,{w:1.35,h,d:1.1,rot:0});blockPad(root,9.8,7.9,9.2,5.5,0x758d83);districtLabel(root,'BUSINESS PARK',9.7,10.3,0x79a9d7);for(const [x,z,k] of[[6.7,8.8,'cityB'],[9.5,8.8,'cityD'],[12.5,8.8,'cityN'],[6.8,6.4,'achuOffice'],[9.6,6.4,'cityS'],[12.6,6.4,'cityU']])building(root,bank,k,x,z,{w:1.35,h:2.25,d:1.1,rot:0});parking(root,bank,13.2,4.5,0,4,false);blockPad(root,-11.0,-.1,7.8,4.8,0x6f8d78);districtLabel(root,'RIVERSIDE',-11,-1.2,0x67c8cb);for(let i=0;i<12;i++)tree(root,bank,-14+(i%4)*1.7,-.9+Math.floor(i/4)*1.2,1.08+(i%3)*.1,120+i);bench(root,-12.7,1.0,0);bench(root,-9.4,1.0,Math.PI);blockPad(root,-.8,-.1,10.5,5.0,0x84998f);for(const [x,z,k] of[[-4.2,.7,'achuStudio'],[-1.5,.6,'cityC'],[1.1,.7,'achuClient'],[3.8,.6,'cityE'],[-4.0,-1.0,'cityA'],[-1.4,-1.0,'cityG'],[1.2,-1.0,'achuSmallOffice'],[3.9,-1.0,'cityJ']])building(root,bank,k,x,z,{w:1.18,h:1.7,d:1.02,rot:0});blockPad(root,10.0,-3.8,9.0,5.0,0x657d72);districtLabel(root,'LOGISTICS',10,-1.4,0xe4aa58);building(root,bank,'achuWarehouse',8.1,-3.5,{w:2.45,h:1.65,d:2.0,rot:Math.PI/2});building(root,bank,'achuDepot',12.1,-3.4,{w:2.25,h:1.55,d:1.85,rot:Math.PI/2});parking(root,bank,10.0,-5.3,0,4,true)}
function fitCar(view,target=.78){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),longX=s.x>s.z*1.08,sc=target/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);if(longX)view.rotation.y=-Math.PI/2;view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;view.userData.forwardOffset=0;return view}
function car(root,bank,k='carSedan',target=.78){const v=fitCar(bank?.clone?.(k)??new THREE.Group(),target);root.add(v);return v}
const TRAFFIC_ROUTES=[path([[-15,2.4],[-10,2.4],[-5,2.4],[0,2.4],[5,2.4],[10,2.4],[15,2.4]]),path([[-11,-12],[-11,-7],[-11,-2],[-11,3],[-11,8],[-11,12]]),path([[2.2,-12],[2.2,-7],[2.2,-2],[2.2,3],[2.2,8],[2.2,12]]),path([[11,-12],[11,-7],[11,-2],[11,3],[11,8],[11,12]]),path([[-15,11.2],[-10,11.2],[-5,11.2],[0,11.2],[5,11.2],[10,11.2],[15,11.2]])]
function traffic(root,bank){const out=[];for(let i=0;i<16;i++){const v=car(root,bank,['carSedan','carSuv','carVan','carDelivery','carTruck'][i%5],.72+(i%3)*.04);out.push({view:v,curve:TRAFFIC_ROUTES[i%TRAFFIC_ROUTES.length],offset:(i*.067)%1,speed:.0000052+(i%5)*.0000005,pingpong:true})}return out}
function moveTraffic(items,now){for(const t of items??[]){const raw=(t.offset+now*t.speed)%2,u=raw<=1?raw:2-raw,dir=raw<=1?1:-1,p=t.curve.getPointAt(u),tan=t.curve.getTangentAt(u).normalize().multiplyScalar(dir);t.view.position.set(p.x,.09,p.z);t.view.rotation.y=Math.atan2(tan.x,tan.z)+(t.view.userData.forwardOffset??0)}}
function hitPlane(root,id){const m=new THREE.Mesh(new THREE.PlaneGeometry(1.6,1.6),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.y=.12;m.userData.tileId=id;root.add(m)}
function tileVisual(root,bank,d,id,known,owned){if(owned)disk(root,.42,0x45c996,.08);if(!known)return;if(id===BASE_TILE){building(root,bank,'achuHq',0,0,{w:.95,h:1.3,d:.85,rot:.1});ring(root,.55,0x52d9a6,.72);return}if(d.businessType==='framework'){building(root,bank,'achuOffice',0,0,{w:.72,h:.95,d:.66,rot:.18});ring(root,.45,FACTIONS[d.tag]?.color??0xc397d3,.5);return}if(d.businessType==='tender'){building(root,bank,'achuSmallOffice',0,0,{w:.68,h:.84,d:.62,rot:.12});ring(root,.43,0xf0a64d,.55);return}if(d.businessType==='lead'){building(root,bank,'achuClient',0,0,{w:.62,h:.72,d:.58,rot:.12});ring(root,.40,0x4bd39e,.42)}}
function nearestTrafficPoint(p){let best=null,bestD=Infinity;for(const c of TRAFFIC_ROUTES){for(let i=0;i<=50;i++){const q=c.getPointAt(i/50),d=q.distanceToSquared(p);if(d<bestD){bestD=d;best=q}}}return best?.clone()??new THREE.Vector3()}
function marchCurve(targetId){const [tx,ty]=parseTile(targetId),target=worldVisualPositionV14(tx,ty),base=worldVisualPositionV14(10,10),a=nearestTrafficPoint(base),b=nearestTrafficPoint(target);return new THREE.CatmullRomCurve3([base,a,b,target],false,'centripetal',.15)}
export class WorldCityV14 extends THREE.Group{constructor(bank,state){super();this.bank=bank;this.state=state;this.tiles=new Map();this.marchObjects=new Map();this.traffic=[];this.build()}build(){this.clear();this.tiles.clear();this.marchObjects.clear();buildGround(this);buildRoads(this,this.bank);buildRiver(this,this.bank);buildDistricts(this,this.bank);this.traffic=traffic(this,this.bank);const owned=new Set(this.state.world.owned??[]),scouted=new Set(this.state.world.scouted??[]);for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const d=worldTile(x,y),id=key(x,y),p=worldVisualPositionV14(x,y),g=new THREE.Group();g.position.copy(p);g.userData.tileId=id;hitPlane(g,id);tileVisual(g,this.bank,d,id,scouted.has(id),owned.has(id));g.traverse(o=>o.userData.tileId=id);this.add(g);this.tiles.set(id,g)}this.refreshMarches();moveTraffic(this.traffic,Date.now())}refresh(){this.build()}refreshMarches(){for(const o of this.marchObjects.values())o.removeFromParent();this.marchObjects.clear();for(const m of this.state.world.marches??[]){const o=car(this,this.bank,m.type==='attack'?'carSuv':'carDelivery',.7);o.userData.route=marchCurve(m.target);this.marchObjects.set(m.id,o)}this.updateMarches(Date.now())}updateMarches(now){moveTraffic(this.traffic,now);for(const m of this.state.world.marches??[]){const o=this.marchObjects.get(m.id);if(!o)continue;let p=1,returning=false;if(m.phase==='outbound')p=Math.max(0,Math.min(1,(now-m.phaseStartedAt)/Math.max(1,m.arriveAt-m.phaseStartedAt)));else if(m.phase==='returning'){returning=true;p=1-Math.max(0,Math.min(1,(now-m.phaseStartedAt)/Math.max(1,m.arriveAt-m.phaseStartedAt)))}const c=o.userData.route??marchCurve(m.target),pos=c.getPointAt(p),tan=c.getTangentAt(p).normalize().multiplyScalar(returning?-1:1);o.position.set(pos.x,.09,pos.z);o.rotation.y=Math.atan2(tan.x,tan.z)+(o.userData.forwardOffset??0)}}focusTile(id){const t=this.tiles.get(id);return t?new THREE.Vector3(t.position.x,0,t.position.z):new THREE.Vector3()}}