import * as THREE from 'three'
import { worldTile,BASE_TILE,parseTile,FACTIONS } from '../data/world.js'

const SIZE=21
const mat=(color,rough=.82,metal=.03)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})
const transparent=(color,opacity)=>new THREE.MeshStandardMaterial({color,roughness:.88,transparent:true,opacity,depthWrite:false})
const box=(w,h,d,m)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.castShadow=true;o.receiveShadow=true;return o}
const makeCurve=(points,closed=false)=>new THREE.CatmullRomCurve3(points.map(([x,z])=>new THREE.Vector3(x,0,z)),closed,'centripetal',.24)
const key=(x,y)=>`${x},${y}`

const NORTH=makeCurve([[-24,12],[-16,13],[-8,12],[0,11],[8,12],[17,14],[25,13]])
const CENTRAL=makeCurve([[-25,3],[-17,4],[-9,3],[-2,2],[5,3],[13,5],[25,4]])
const SOUTH=makeCurve([[-24,-15],[-16,-16],[-8,-15],[0,-13],[8,-12],[16,-10],[24,-8]])
const WEST=makeCurve([[-18,18],[-18,11],[-17,4],[-16,-3],[-17,-10],[-16,-18]])
const EAST=makeCurve([[16,18],[15,12],[14,6],[14,-1],[16,-8],[18,-15]])
const RIVER_ROAD=makeCurve([[-23,-2],[-16,-1],[-9,-2],[-2,-4],[6,-4],[13,-2],[21,1]])
const BUSINESS=makeCurve([[7,11],[12,14],[18,13],[22,9],[21,5],[16,4],[11,6],[7,11]],true)
const WEST_END=makeCurve([[-21,8],[-24,4],[-23,-2],[-19,-6],[-14,-5],[-12,0],[-14,6],[-21,8]],true)
const LOGISTICS=makeCurve([[5,-10],[10,-14],[16,-14],[22,-11],[22,-6],[18,-3],[12,-4],[7,-7],[5,-10]],true)
const ROAD_CURVES=[NORTH,CENTRAL,SOUTH,WEST,EAST,RIVER_ROAD,BUSINESS,WEST_END,LOGISTICS]

function ribbonGeometry(c,width,y=.006,segments=150){const verts=[],idx=[];for(let i=0;i<=segments;i++){const u=i/segments,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),nx=-t.z,nz=t.x;verts.push(p.x+nx*width/2,y,p.z+nz*width/2,p.x-nx*width/2,y,p.z-nz*width/2)}for(let i=0;i<segments;i++){const q=i*2;idx.push(q,q+1,q+2,q+1,q+3,q+2)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g}
function ribbon(parent,c,width,color,y=.006){const m=new THREE.Mesh(ribbonGeometry(c,width,y),mat(color,.96));m.receiveShadow=true;m.castShadow=false;parent.add(m);return m}
function dashed(parent,c,count=70,y=.045){const dm=mat(0xd6dbd5,.7);for(let i=1;i<count;i+=2){const u=i/count,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),d=box(.055,.014,.42,dm);d.position.set(p.x,y,p.z);d.rotation.y=Math.atan2(t.x,t.z);d.castShadow=false;parent.add(d)}}
function fit(view,{w=2,h=2,d=2}){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=Math.min(w/Math.max(.001,s.x),h/Math.max(.001,s.y),d/Math.max(.001,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function fitRoad(view,size=2.5){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),sc=size/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;return view}
function roadAsset(parent,bank,name,x,z,rot=0,size=2.5,y=.02){const v=fitRoad(bank?.clone?.(name)??new THREE.Group(),size);v.position.set(x,y,z);v.rotation.y=rot;parent.add(v);return v}
function building(parent,bank,name,x,z,{w=1.2,h=1.8,d=1,rot=0}={}){const v=fit(bank?.clone?.(name)??new THREE.Group(),{w,h,d});v.position.set(x,0,z);v.rotation.y=rot;parent.add(v);return v}
function tree(parent,bank,x,z,h=1.25,i=0){const v=bank?.cloneTree?.(i,h);if(!v)return;v.position.set(x,0,z);v.rotation.y=(i*.87)%6.283;parent.add(v)}
function fitCar(view,target=1.02){view.rotation.set(0,0,0);view.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(view),s=b.getSize(new THREE.Vector3()),longX=s.x>s.z*1.08,sc=target/Math.max(.001,Math.max(s.x,s.z));view.scale.multiplyScalar(sc);view.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(view);view.position.x-=(b.min.x+b.max.x)/2;view.position.z-=(b.min.z+b.max.z)/2;view.position.y-=b.min.y;view.userData.forwardOffset=longX?Math.PI/2:0;return view}
function car(parent,bank,index=0,target=1.02,keyName=null){const src=keyName?bank?.clone?.(keyName):bank?.cloneCar?.(index);const v=fitCar(src??bank?.clone?.('carSedan')??new THREE.Group(),target);parent.add(v);return v}
function ring(parent,r,color,opacity=.5){const m=new THREE.Mesh(new THREE.RingGeometry(r*.78,r,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.y=.07;parent.add(m)}
function disk(parent,r,color,opacity=.12){const m=new THREE.Mesh(new THREE.CircleGeometry(r,40),transparent(color,opacity));m.rotation.x=-Math.PI/2;m.position.y=.035;parent.add(m)}
function labelSprite(text,color=0xffffff,scale=1){const c=document.createElement('canvas');c.width=640;c.height=128;const x=c.getContext('2d');x.fillStyle='rgba(12,26,23,.88)';x.roundRect(12,17,616,94,22);x.fill();x.strokeStyle=`#${color.toString(16).padStart(6,'0')}`;x.lineWidth=3;x.stroke();x.fillStyle='#eef2eb';x.font='800 28px Inter,Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text.toUpperCase(),320,64,570);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(4.1*scale,.82*scale,1);return s}
function label(parent,text,x,z,color=0xffffff,scale=.72){const l=labelSprite(text,color,scale);l.position.set(x,2.25,z);parent.add(l)}
function roadLight(root,bank,x,z,r=0){if(!bank?.models?.roadLightCurved)return;const v=fit(bank.clone('roadLightCurved'),{w:.22,h:1.5,d:.22});v.position.set(x,.02,z);v.rotation.y=r;root.add(v)}

function riverCurve(){return makeCurve([[-29,-7],[-22,-6],[-15,-7],[-8,-9],[-1,-8],[6,-6],[13,-6],[21,-8],[29,-6]])}
function buildRiver(root,bank){const c=riverCurve();ribbon(root,c,5.6,0x718d7f,-.08);const water=new THREE.Mesh(ribbonGeometry(c,4.55,-.055,180),new THREE.MeshStandardMaterial({color:0x4d9aa0,roughness:.34,metalness:.04,transparent:true,opacity:.93}));water.receiveShadow=true;root.add(water);const promenade=new THREE.CatmullRomCurve3(Array.from({length:44},(_,i)=>{const u=i/43,p=c.getPointAt(u),t=c.getTangentAt(u).normalize(),n=new THREE.Vector3(-t.z,0,t.x);return p.clone().add(n.multiplyScalar(3.35))}),false,'centripetal',.2);ribbon(root,promenade,.58,0xc9cec4,.02);for(let i=2;i<42;i+=3){const p=promenade.getPointAt(i/43);tree(root,bank,p.x+.4,p.z+.3,1.1+(i%4)*.12,500+i)}const p=c.getPointAt(.72),deck=box(.72,.16,5.1,mat(0xb8b8ad,.88));deck.position.set(p.x,.42,p.z);deck.rotation.y=.18;root.add(deck);for(const q of[-1.5,1.5]){const pillar=box(.24,.84,.24,mat(0x68736d,.92));pillar.position.set(p.x+Math.sin(-.18)*q,0,p.z+Math.cos(-.18)*q);root.add(pillar)}}
function bridge(root,bank,x,z,rot=0){for(const dz of[-2,0,2])roadAsset(root,bank,'roadBridge',x+Math.sin(rot)*dz,z+Math.cos(rot)*dz,rot,2.25,.36);roadAsset(root,bank,'roadSlantHigh',x-Math.sin(rot)*3.95,z-Math.cos(rot)*3.95,rot,2.35,.08);roadAsset(root,bank,'roadSlantHigh',x+Math.sin(rot)*3.95,z+Math.cos(rot)*3.95,rot+Math.PI,2.35,.08);for(const dz of[-1.3,1.3])if(bank?.models?.bridgePillarWide){const p=fit(bank.clone('bridgePillarWide'),{w:.7,h:1,d:.7});p.position.set(x+Math.sin(rot)*dz,-.02,z+Math.cos(rot)*dz);root.add(p)}}
function buildRoads(root,bank){const defs=[[NORTH,2.05],[CENTRAL,2.25],[SOUTH,2],[WEST,1.75],[EAST,1.75],[RIVER_ROAD,1.55],[BUSINESS,1.55],[WEST_END,1.5],[LOGISTICS,1.65]];for(const [c,w] of defs){ribbon(root,c,w+.72,0x8c9992,-.005);ribbon(root,c,w,0x394746,.012);dashed(root,c,c.closed?80:64)}roadAsset(root,bank,'roadRoundabout',-2,2,0,4,.025);roadAsset(root,bank,'roadRoundabout',15,5,0,3.2,.025);roadAsset(root,bank,'roadCurveIntersection',-17,4,.2,2.7,.025);roadAsset(root,bank,'roadIntersectionPath',5,3,0,2.7,.025);roadAsset(root,bank,'roadSplit',9,-11.6,-.6,2.6,.025);roadAsset(root,bank,'roadSideEntry',14,-1,-Math.PI/2,2.2,.025);roadAsset(root,bank,'roadSideExit',-16,-3,Math.PI/2,2.2,.025);roadAsset(root,bank,'roadCrossing',-8.5,3.1,Math.PI/2,2.25,.025);bridge(root,bank,-7.4,-8.6,.08);bridge(root,bank,14.8,-6.1,-.16);for(const [x,z,r] of[[-20,12,.8],[-12,12.5,1.1],[-5,2.4,1.2],[7,3.5,-1.1],[17,13,-1.4],[-17,-1,.1],[13,-2,-1.1],[8,-13,.4],[-10,-15.5,1.5]])roadLight(root,bank,x,z,r);if(bank?.models?.roadTrafficLight)for(const [x,z,r] of[[-3.3,1.1,0],[-.7,1.1,Math.PI],[-2.1,3.2,Math.PI/2]]){const v=fit(bank.clone('roadTrafficLight'),{w:.24,h:1.2,d:.24});v.position.set(x,.02,z);v.rotation.y=r;root.add(v)}roadAsset(root,bank,'highwaySign',0,11.3,Math.PI/2,2,.02);roadAsset(root,bank,'roadSignStop',-17.6,5.3,0,.75,.02);roadAsset(root,bank,'roadSignWarning',9.8,-12.8,0,.75,.02)}
function lot(parent,x,z,w,d,color=0xaabbb1,rot=0){const p=box(w,.04,d,mat(color,.99));p.position.set(x,-.025,z);p.rotation.y=rot;p.castShadow=false;parent.add(p)}
function parking(parent,bank,x,z,rot=0,count=4,logistics=false){const g=new THREE.Group();g.position.set(x,.02,z);g.rotation.y=rot;const p=box(4,.035,2.3,mat(0x454f4e,.99));p.castShadow=false;g.add(p);for(let i=-2;i<=2;i++){const l=box(.035,.012,1.86,mat(0xe0e2da,.76));l.position.set(i*.74,.03,0);l.castShadow=false;g.add(l)}for(let i=0;i<count;i++){const keyName=logistics?['carVan','carDelivery','carTruck'][i%3]:null;const v=car(g,bank,i,.8+(i%2)*.05,keyName);v.position.set(-1.12+i*.74,.05,(i%2)*.1-.05);v.rotation.y=v.userData.forwardOffset??0}parent.add(g)}
function buildDistricts(root,bank){lot(root,-1.5,7,12,7.8,0xaab8b0,.04);[[-5,7.5,'achuOffice',1.4,2.5,1.1,.1],[-2.1,7.8,'achuStudio',1.25,2,1,-.1],[1.2,7,'achuHq',1.5,2.8,1.2,.08],[4,7.6,'achuSmallOffice',1.1,1.7,.9,-.15],[-4.1,10,'achuClient',1.1,1.45,.9,.1],[-.5,10.1,'achuOffice',1.25,2.2,1,.06],[3,10,'achuStudio',1.1,1.7,.9,-.08]].forEach(([x,z,n,w,h,d,r])=>building(root,bank,n,x,z,{w,h,d,rot:r}));parking(root,bank,-5,5.1,.02,4);label(root,'Downtown',-1,12,0x63d4a8);lot(root,-18.5,2.2,10.5,13,0x9fb5a8,-.08);[[-21,5,'achuClient'],[-17.5,5.2,'achuClient'],[-20.5,1.8,'achuSmallOffice'],[-16.8,1.6,'achuClient'],[-20,-2,'achuClient'],[-16.5,-2.1,'achuSmallOffice']].forEach(([x,z,n],i)=>building(root,bank,n,x,z,{w:1.05+(i%2)*.12,h:1.25+(i%3)*.12,d:.88,rot:i%2?-.3:.2}));for(const [x,z,i] of[[-22,7,10],[-18,7.5,11],[-14.5,4,12],[-22,-4,13],[-15,-4,14]])tree(root,bank,x,z,1.45,i);label(root,'West End',-18.5,9,0x8dd7b0);lot(root,16.2,9.1,11.4,9.8,0xa8b5ad,.05);[[12.6,9.7,'achuOffice',1.35,2.4,1.1,.1],[16,10.2,'achuHq',1.45,2.7,1.18,-.08],[19.4,9.4,'achuOffice',1.25,2.2,1,.08],[13.5,6.7,'achuStudio',1.15,1.8,.9,.1],[18.3,6.6,'achuSmallOffice',1.05,1.55,.86,-.12]].forEach(([x,z,n,w,h,d,r])=>building(root,bank,n,x,z,{w,h,d,rot:r}));parking(root,bank,19,12,-.08,4);label(root,'Business Park',16,15.2,0x75c8e8);lot(root,1.5,-2.8,11,6,0xa6bbb1,-.05);[[-2.2,-1.8,'achuClient'],[1.2,-1.7,'achuStudio'],[4.6,-2,'achuClient']].forEach(([x,z,n],i)=>building(root,bank,n,x,z,{w:1.1+i*.08,h:1.55+i*.12,d:.95,rot:.1-i*.1}));for(const [x,z,i] of[[-4.3,-3.5,70],[-2.8,-4.2,71],[.2,-4.7,72],[3.4,-4.5,73],[5.6,-4,74]])tree(root,bank,x,z,1.3,i);label(root,'Riverside',1,-5.2,0x65d4cf);lot(root,15.2,-11,12.5,8.8,0x9daaa4,.03);[[10.8,-9.4,'achuWarehouse',2,1.7,1.45,0],[15,-9.2,'achuDepot',1.8,1.6,1.35,0],[19,-9.6,'achuWarehouse',2.1,1.7,1.45,0],[12.7,-13,'achuDepot',1.7,1.5,1.25,0],[18.2,-13.1,'achuWarehouse',1.9,1.65,1.35,0]].forEach(([x,z,n,w,h,d,r])=>building(root,bank,n,x,z,{w,h,d,rot:r}));parking(root,bank,15.2,-6.7,0,4,true);roadAsset(root,bank,'roadFence',21.2,-11,Math.PI/2,1.1,.02);roadAsset(root,bank,'roadBarrier',9.5,-12.8,0,1,.02);roadAsset(root,bank,'roadCone',10,-12.2,0,.7,.02);label(root,'Logistics',15,-16,0xe0b85a)}
function buildGround(root){const outer=box(58,.10,44,mat(0x728c7e,1));outer.position.y=-.18;outer.castShadow=false;root.add(outer);const inner=box(54,.045,40,mat(0xb2c1b8,1));inner.position.y=-.09;inner.castShadow=false;root.add(inner);for(const [x,z,w,d] of[[-10,9,7,4],[8,8,4,4],[-10,-1,6,4],[4,-14,7,3]]){const p=box(w,.04,d,mat(0x8ca894,1));p.position.set(x,-.035,z);p.castShadow=false;root.add(p)}}
function markerVisual(parent,d,id,known,owned){if(owned){disk(parent,.44,0x45c996,.13);ring(parent,.46,0x4ed6a0,.34)}if(!known)return;if(id===BASE_TILE){const l=labelSprite('ACHU HQ',0x52d9a6,.42);l.position.set(0,1.4,0);parent.add(l);ring(parent,.58,0x52d9a6,.75);return}const color=d.businessType==='tender'?0xf0a64d:d.businessType==='framework'?(FACTIONS[d.tag]?.color??0xc397d3):0x4bd39e;ring(parent,.36,color,.58);const pole=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,.5,8),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.72}));pole.position.y=.25;parent.add(pole)}
function hitPlane(parent,id){const h=new THREE.Mesh(new THREE.CircleGeometry(.58,18),new THREE.MeshBasicMaterial({transparent:true,opacity:.001,side:THREE.DoubleSide,depthWrite:false}));h.rotation.x=-Math.PI/2;h.position.y=.14;h.userData.tileId=id;parent.add(h)}
const DISTRICTS=[{c:[-18,2],span:[8.5,11]},{c:[-1,8],span:[11,7]},{c:[16,9],span:[10,7.5]},{c:[1,-2.5],span:[10,5]},{c:[15,-11],span:[11,7]}]
export function worldVisualPositionV11(x,y){if(x===10&&y===10)return new THREE.Vector3(-2,0,2.4);const zone=x<7?0:x<14?(y<9?3:1):(y<10?4:2),d=DISTRICTS[zone],sx=((x%7)-3)/3,sy=((y%7)-3)/3,ox=sx*d.span[0]*.46+Math.sin((x+1)*(y+3))*.28,oz=sy*d.span[1]*.44+Math.cos((x+2)*(y+1))*.24;return new THREE.Vector3(d.c[0]+ox,0,d.c[1]+oz)}
function nearestRoadPoint(p){let best=null,bestD=Infinity;for(const c of ROAD_CURVES){for(let i=0;i<=90;i++){const q=c.getPointAt(i/90),dist=q.distanceToSquared(p);if(dist<bestD){bestD=dist;best=q}}}return best?.clone()??new THREE.Vector3()}
function marchCurve(targetId){const [tx,ty]=parseTile(targetId),target=worldVisualPositionV11(tx,ty),base=worldVisualPositionV11(10,10),a=nearestRoadPoint(base),b=nearestRoadPoint(target);return new THREE.CatmullRomCurve3([base,a,b,target],false,'centripetal',.25)}
function trafficNetwork(root,bank){const routes=[NORTH,CENTRAL,SOUTH,WEST,EAST,BUSINESS,WEST_END,LOGISTICS,RIVER_ROAD],out=[];for(let i=0;i<16;i++){const keyName=i===12?'carVan':i===13?'carDelivery':i===14?'carTruck':null;const v=car(root,bank,i,1+(i%3)*.05,keyName);out.push({view:v,curve:routes[i%routes.length],offset:(i*.071)%1,speed:.0000056+(i%4)*.0000007,pingpong:!routes[i%routes.length].closed})}return out}
function moveTraffic(traffic,now){for(const t of traffic??[]){let u=(t.offset+now*t.speed)%1,dir=1;if(t.pingpong){const raw=(t.offset+now*t.speed)%2;u=raw<=1?raw:2-raw;dir=raw<=1?1:-1}const p=t.curve.getPointAt(u),tan=t.curve.getTangentAt(u).normalize().multiplyScalar(dir);t.view.position.set(p.x,.09,p.z);t.view.rotation.y=Math.atan2(tan.x,tan.z)+(t.view.userData.forwardOffset??0)}}

export class WorldCityV11 extends THREE.Group{constructor(bank,state){super();this.bank=bank;this.state=state;this.tiles=new Map();this.marchObjects=new Map();this.traffic=[];this.build()}build(){this.clear();this.tiles.clear();this.marchObjects.clear();buildGround(this);buildRiver(this,this.bank);buildRoads(this,this.bank);buildDistricts(this,this.bank);this.traffic=trafficNetwork(this,this.bank);const owned=new Set(this.state.world.owned??[]),scouted=new Set(this.state.world.scouted??[]);for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const d=worldTile(x,y),id=key(x,y),p=worldVisualPositionV11(x,y),g=new THREE.Group();g.position.copy(p);g.userData.tileId=id;hitPlane(g,id);markerVisual(g,d,id,scouted.has(id),owned.has(id));g.traverse(o=>o.userData.tileId=id);this.add(g);this.tiles.set(id,g)}this.refreshMarches();moveTraffic(this.traffic,Date.now())}refresh(){this.build()}refreshMarches(){for(const o of this.marchObjects.values())o.removeFromParent();this.marchObjects.clear();for(const m of this.state.world.marches??[]){const o=car(this,this.bank,m.type==='attack'?4:1,.82);o.userData.route=marchCurve(m.target);this.marchObjects.set(m.id,o)}this.updateMarches(Date.now())}updateMarches(now){moveTraffic(this.traffic,now);for(const m of this.state.world.marches??[]){const o=this.marchObjects.get(m.id);if(!o)continue;let p=1,returning=false;if(m.phase==='outbound')p=Math.max(0,Math.min(1,(now-m.phaseStartedAt)/Math.max(1,m.arriveAt-m.phaseStartedAt)));else if(m.phase==='returning'){returning=true;p=1-Math.max(0,Math.min(1,(now-m.phaseStartedAt)/Math.max(1,m.arriveAt-m.phaseStartedAt)))}const c=o.userData.route??marchCurve(m.target),pos=c.getPointAt(p),tan=c.getTangentAt(p).normalize().multiplyScalar(returning?-1:1);o.position.set(pos.x,.09,pos.z);o.rotation.y=Math.atan2(tan.x,tan.z)+(o.userData.forwardOffset??0)}}focusTile(id){const t=this.tiles.get(id);return t?new THREE.Vector3(t.position.x,0,t.position.z):new THREE.Vector3()}}
